server:
  #port: 8989
  port: 12346
# session 过期时间，单位：秒 从用户最后一次操作开始计算过期时间 最小值60
  servlet:
    session:
      timeout: 60000

spring:
  datasource:
    name: mysql
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://192.168.18.113/db_ymcx_log_pdjs
#    username: kiss
#    password: kiss@123

#    url: jdbc:mysql://polardb-pdjs-001.rwlb.rds.aliyuncs.com/db_ymcx_log_pdjs
#    username: webquery
#    password: 0737876BE721a

    url: jdbc:mysql://111.231.62.166/db_ymcx_log_pdjs
    username: ymcxroot
    password: ymcxroot



    # 下面为连接池的补充设置，应用到上面所有数据源中 p.conf
    # 初始化大小，最小，最大
    initialSize: 5
    minIdle: 5
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    useGlobalDataSourceStat: true
  thymeleaf:
    cache: false
  main:
    allow-bean-definition-overriding: true

mybatis:
  type-aliases-package: com.yoooum.domain
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  returnPageInfo: check


