// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.yoooum.tars.gfx;

import com.qq.tars.rpc.protocol.tars.support.TarsAbstractCallback;

public abstract class IdipServantPrxCallback extends TarsAbstractCallback {

	public abstract void callback_SendMail(int ret, java.util.List<com.yoooum.tars.account.TAccountID> vecSuccAccountID, java.util.List<com.yoooum.tars.account.TAccountID> vecFailAccountID);

	public abstract void callback_DelMail(int ret, java.util.List<com.yoooum.tars.account.TAccountID> vecSuccAccountID, java.util.List<com.yoooum.tars.account.TAccountID> vecFailAccountID);

	public abstract void callback_QueryPlayerData(int ret, com.yoooum.tars.account.TAccountData stAccountData);

	public abstract void callback_QueryPalyerGameData(int ret, java.util.List<com.yoooum.tars.account.TPlayerRoleInfo> vecPlayerGameInfo);

}
