// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.yoooum.tars.account;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class TAccountData {

	@TarsStructProperty(order = 0, isRequire = true)
	public TAccountID stAccountID = null;
	@TarsStructProperty(order = 1, isRequire = true)
	public long lLastLoginTm = 0L;
	@TarsStructProperty(order = 2, isRequire = true)
	public long lCreateTime = 0;
	@TarsStructProperty(order = 3, isRequire = true)
	public TUserBaseInfo stUserBaseInfo = null;
	@TarsStructProperty(order = 4, isRequire = false)
	public short nBan = (short)0;
	@TarsStructProperty(order = 5, isRequire = false)
	public long lBanTime = 0L;
	@TarsStructProperty(order = 6, isRequire = false)
	public TExtData1 stExtData1 = null;
	@TarsStructProperty(order = 7, isRequire = false)
	public long lLastLogoutTm = 0L;
	@TarsStructProperty(order = 8, isRequire = false)
	public TEquipmentInfo stEquipmentData = null;
	@TarsStructProperty(order = 9, isRequire = false)
	public TDBBagInfo stBagInfo = null;
	@TarsStructProperty(order = 10, isRequire = false)
	public TNaturalSkillInfo stNaturalSkillData = null;
	@TarsStructProperty(order = 11, isRequire = false)
	public TSoldierInfo stSoldierData = null;
	@TarsStructProperty(order = 12, isRequire = false)
	public THeroInfo stHeroInfo = null;
	@TarsStructProperty(order = 13, isRequire = false)
	public TStageInfo stStageInfo = null;

	public TAccountID getStAccountID() {
		return stAccountID;
	}

	public void setStAccountID(TAccountID stAccountID) {
		this.stAccountID = stAccountID;
	}

	public long getLLastLoginTm() {
		return lLastLoginTm;
	}

	public void setLLastLoginTm(long lLastLoginTm) {
		this.lLastLoginTm = lLastLoginTm;
	}

	public long getLCreateTime() {
		return lCreateTime;
	}

	public void setLCreateTime(long lCreateTime) {
		this.lCreateTime = lCreateTime;
	}

	public TUserBaseInfo getStUserBaseInfo() {
		return stUserBaseInfo;
	}

	public void setStUserBaseInfo(TUserBaseInfo stUserBaseInfo) {
		this.stUserBaseInfo = stUserBaseInfo;
	}

	public short getNBan() {
		return nBan;
	}

	public void setNBan(short nBan) {
		this.nBan = nBan;
	}

	public long getLBanTime() {
		return lBanTime;
	}

	public void setLBanTime(long lBanTime) {
		this.lBanTime = lBanTime;
	}

	public TExtData1 getStExtData1() {
		return stExtData1;
	}

	public void setStExtData1(TExtData1 stExtData1) {
		this.stExtData1 = stExtData1;
	}

	public long getLLastLogoutTm() {
		return lLastLogoutTm;
	}

	public void setLLastLogoutTm(long lLastLogoutTm) {
		this.lLastLogoutTm = lLastLogoutTm;
	}

	public TEquipmentInfo getStEquipmentData() {
		return stEquipmentData;
	}

	public void setStEquipmentData(TEquipmentInfo stEquipmentData) {
		this.stEquipmentData = stEquipmentData;
	}

	public TDBBagInfo getStBagInfo() {
		return stBagInfo;
	}

	public void setStBagInfo(TDBBagInfo stBagInfo) {
		this.stBagInfo = stBagInfo;
	}

	public TNaturalSkillInfo getStNaturalSkillData() {
		return stNaturalSkillData;
	}

	public void setStNaturalSkillData(TNaturalSkillInfo stNaturalSkillData) {
		this.stNaturalSkillData = stNaturalSkillData;
	}

	public TSoldierInfo getStSoldierData() {
		return stSoldierData;
	}

	public void setStSoldierData(TSoldierInfo stSoldierData) {
		this.stSoldierData = stSoldierData;
	}

	public THeroInfo getStHeroInfo() {
		return stHeroInfo;
	}

	public void setStHeroInfo(THeroInfo stHeroInfo) {
		this.stHeroInfo = stHeroInfo;
	}

	public TStageInfo getStStageInfo() {
		return stStageInfo;
	}

	public void setStStageInfo(TStageInfo stStageInfo) {
		this.stStageInfo = stStageInfo;
	}

	public TAccountData() {
	}

	public TAccountData(TAccountID stAccountID, long lLastLoginTm, long lCreateTime, TUserBaseInfo stUserBaseInfo, short nBan, long lBanTime, TExtData1 stExtData1, long lLastLogoutTm, TEquipmentInfo stEquipmentData, TDBBagInfo stBagInfo, TNaturalSkillInfo stNaturalSkillData, TSoldierInfo stSoldierData, THeroInfo stHeroInfo, TStageInfo stStageInfo) {
		this.stAccountID = stAccountID;
		this.lLastLoginTm = lLastLoginTm;
		this.lCreateTime = lCreateTime;
		this.stUserBaseInfo = stUserBaseInfo;
		this.nBan = nBan;
		this.lBanTime = lBanTime;
		this.stExtData1 = stExtData1;
		this.lLastLogoutTm = lLastLogoutTm;
		this.stEquipmentData = stEquipmentData;
		this.stBagInfo = stBagInfo;
		this.stNaturalSkillData = stNaturalSkillData;
		this.stSoldierData = stSoldierData;
		this.stHeroInfo = stHeroInfo;
		this.stStageInfo = stStageInfo;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(stAccountID);
		result = prime * result + TarsUtil.hashCode(lLastLoginTm);
		result = prime * result + TarsUtil.hashCode(lCreateTime);
		result = prime * result + TarsUtil.hashCode(stUserBaseInfo);
		result = prime * result + TarsUtil.hashCode(nBan);
		result = prime * result + TarsUtil.hashCode(lBanTime);
		result = prime * result + TarsUtil.hashCode(stExtData1);
		result = prime * result + TarsUtil.hashCode(lLastLogoutTm);
		result = prime * result + TarsUtil.hashCode(stEquipmentData);
		result = prime * result + TarsUtil.hashCode(stBagInfo);
		result = prime * result + TarsUtil.hashCode(stNaturalSkillData);
		result = prime * result + TarsUtil.hashCode(stSoldierData);
		result = prime * result + TarsUtil.hashCode(stHeroInfo);
		result = prime * result + TarsUtil.hashCode(stStageInfo);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof TAccountData)) {
			return false;
		}
		TAccountData other = (TAccountData) obj;
		return (
			TarsUtil.equals(stAccountID, other.stAccountID) &&
			TarsUtil.equals(lLastLoginTm, other.lLastLoginTm) &&
			TarsUtil.equals(lCreateTime, other.lCreateTime) &&
			TarsUtil.equals(stUserBaseInfo, other.stUserBaseInfo) &&
			TarsUtil.equals(nBan, other.nBan) &&
			TarsUtil.equals(lBanTime, other.lBanTime) &&
			TarsUtil.equals(stExtData1, other.stExtData1) &&
			TarsUtil.equals(lLastLogoutTm, other.lLastLogoutTm) &&
			TarsUtil.equals(stEquipmentData, other.stEquipmentData) &&
			TarsUtil.equals(stBagInfo, other.stBagInfo) &&
			TarsUtil.equals(stNaturalSkillData, other.stNaturalSkillData) &&
			TarsUtil.equals(stSoldierData, other.stSoldierData) &&
			TarsUtil.equals(stHeroInfo, other.stHeroInfo) &&
			TarsUtil.equals(stStageInfo, other.stStageInfo) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(stAccountID, 0);
		_os.write(lLastLoginTm, 1);
		_os.write(lCreateTime, 2);
		_os.write(stUserBaseInfo, 3);
		_os.write(nBan, 4);
		_os.write(lBanTime, 5);
		if (null != stExtData1) {
			_os.write(stExtData1, 6);
		}
		_os.write(lLastLogoutTm, 7);
		if (null != stEquipmentData) {
			_os.write(stEquipmentData, 8);
		}
		if (null != stBagInfo) {
			_os.write(stBagInfo, 9);
		}
		if (null != stNaturalSkillData) {
			_os.write(stNaturalSkillData, 10);
		}
		if (null != stSoldierData) {
			_os.write(stSoldierData, 11);
		}
		if (null != stHeroInfo) {
			_os.write(stHeroInfo, 12);
		}
		if (null != stStageInfo) {
			_os.write(stStageInfo, 13);
		}
	}

	static TAccountID cache_stAccountID;
	static { 
		cache_stAccountID = new TAccountID();
	}
	static TUserBaseInfo cache_stUserBaseInfo;
	static { 
		cache_stUserBaseInfo = new TUserBaseInfo();
	}
	static TExtData1 cache_stExtData1;
	static { 
		cache_stExtData1 = new TExtData1();
	}
	static TEquipmentInfo cache_stEquipmentData;
	static { 
		cache_stEquipmentData = new TEquipmentInfo();
	}
	static TDBBagInfo cache_stBagInfo;
	static { 
		cache_stBagInfo = new TDBBagInfo();
	}
	static TNaturalSkillInfo cache_stNaturalSkillData;
	static { 
		cache_stNaturalSkillData = new TNaturalSkillInfo();
	}
	static TSoldierInfo cache_stSoldierData;
	static { 
		cache_stSoldierData = new TSoldierInfo();
	}
	static THeroInfo cache_stHeroInfo;
	static { 
		cache_stHeroInfo = new THeroInfo();
	}
	static TStageInfo cache_stStageInfo;
	static { 
		cache_stStageInfo = new TStageInfo();
	}

	public void readFrom(TarsInputStream _is) {
		this.stAccountID = (TAccountID) _is.read(cache_stAccountID, 0, true);
		this.lLastLoginTm = _is.read(lLastLoginTm, 1, true);
		this.lCreateTime = _is.read(lCreateTime, 2, true);
		this.stUserBaseInfo = (TUserBaseInfo) _is.read(cache_stUserBaseInfo, 3, true);
		this.nBan = _is.read(nBan, 4, false);
		this.lBanTime = _is.read(lBanTime, 5, false);
		this.stExtData1 = (TExtData1) _is.read(cache_stExtData1, 6, false);
		this.lLastLogoutTm = _is.read(lLastLogoutTm, 7, false);
		this.stEquipmentData = (TEquipmentInfo) _is.read(cache_stEquipmentData, 8, false);
		this.stBagInfo = (TDBBagInfo) _is.read(cache_stBagInfo, 9, false);
		this.stNaturalSkillData = (TNaturalSkillInfo) _is.read(cache_stNaturalSkillData, 10, false);
		this.stSoldierData = (TSoldierInfo) _is.read(cache_stSoldierData, 11, false);
		this.stHeroInfo = (THeroInfo) _is.read(cache_stHeroInfo, 12, false);
		this.stStageInfo = (TStageInfo) _is.read(cache_stStageInfo, 13, false);
	}

}
