// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.yoooum.tars.account;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class TBackRoomGameInfo {

	@TarsStructProperty(order = 0, isRequire = false)
	public int itypeid = 0;
	@TarsStructProperty(order = 1, isRequire = false)
	public short shlvl = (short)0;
	@TarsStructProperty(order = 2, isRequire = false)
	public long ulastgametime = 0L;

	public int getItypeid() {
		return itypeid;
	}

	public void setItypeid(int itypeid) {
		this.itypeid = itypeid;
	}

	public short getShlvl() {
		return shlvl;
	}

	public void setShlvl(short shlvl) {
		this.shlvl = shlvl;
	}

	public long getUlastgametime() {
		return ulastgametime;
	}

	public void setUlastgametime(long ulastgametime) {
		this.ulastgametime = ulastgametime;
	}

	public TBackRoomGameInfo() {
	}

	public TBackRoomGameInfo(int itypeid, short shlvl, long ulastgametime) {
		this.itypeid = itypeid;
		this.shlvl = shlvl;
		this.ulastgametime = ulastgametime;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(itypeid);
		result = prime * result + TarsUtil.hashCode(shlvl);
		result = prime * result + TarsUtil.hashCode(ulastgametime);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof TBackRoomGameInfo)) {
			return false;
		}
		TBackRoomGameInfo other = (TBackRoomGameInfo) obj;
		return (
			TarsUtil.equals(itypeid, other.itypeid) &&
			TarsUtil.equals(shlvl, other.shlvl) &&
			TarsUtil.equals(ulastgametime, other.ulastgametime) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(itypeid, 0);
		_os.write(shlvl, 1);
		_os.write(ulastgametime, 2);
	}


	public void readFrom(TarsInputStream _is) {
		this.itypeid = _is.read(itypeid, 0, false);
		this.shlvl = _is.read(shlvl, 1, false);
		this.ulastgametime = _is.read(ulastgametime, 2, false);
	}

}
