// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.yoooum.tars.account;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class TBackYardLogData {

	@TarsStructProperty(order = 0, isRequire = false)
	public long utrigtime = 0L;
	@TarsStructProperty(order = 1, isRequire = false)
	public short shlogtype = (short)0;
	@TarsStructProperty(order = 2, isRequire = false)
	public java.util.List<java.lang.Integer> veclogdata = null;
	@TarsStructProperty(order = 3, isRequire = false)
	public byte cmakeresult = 0;

	public long getUtrigtime() {
		return utrigtime;
	}

	public void setUtrigtime(long utrigtime) {
		this.utrigtime = utrigtime;
	}

	public short getShlogtype() {
		return shlogtype;
	}

	public void setShlogtype(short shlogtype) {
		this.shlogtype = shlogtype;
	}

	public java.util.List<java.lang.Integer> getVeclogdata() {
		return veclogdata;
	}

	public void setVeclogdata(java.util.List<java.lang.Integer> veclogdata) {
		this.veclogdata = veclogdata;
	}

	public byte getCmakeresult() {
		return cmakeresult;
	}

	public void setCmakeresult(byte cmakeresult) {
		this.cmakeresult = cmakeresult;
	}

	public TBackYardLogData() {
	}

	public TBackYardLogData(long utrigtime, short shlogtype, java.util.List<java.lang.Integer> veclogdata, byte cmakeresult) {
		this.utrigtime = utrigtime;
		this.shlogtype = shlogtype;
		this.veclogdata = veclogdata;
		this.cmakeresult = cmakeresult;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(utrigtime);
		result = prime * result + TarsUtil.hashCode(shlogtype);
		result = prime * result + TarsUtil.hashCode(veclogdata);
		result = prime * result + TarsUtil.hashCode(cmakeresult);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof TBackYardLogData)) {
			return false;
		}
		TBackYardLogData other = (TBackYardLogData) obj;
		return (
			TarsUtil.equals(utrigtime, other.utrigtime) &&
			TarsUtil.equals(shlogtype, other.shlogtype) &&
			TarsUtil.equals(veclogdata, other.veclogdata) &&
			TarsUtil.equals(cmakeresult, other.cmakeresult) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(utrigtime, 0);
		_os.write(shlogtype, 1);
		if (null != veclogdata) {
			_os.write(veclogdata, 2);
		}
		_os.write(cmakeresult, 3);
	}

	static java.util.List<java.lang.Integer> cache_veclogdata;
	static { 
		cache_veclogdata = new java.util.ArrayList<java.lang.Integer>();
		int var_74 = 0;
		cache_veclogdata.add(var_74);
	}

	public void readFrom(TarsInputStream _is) {
		this.utrigtime = _is.read(utrigtime, 0, false);
		this.shlogtype = _is.read(shlogtype, 1, false);
		this.veclogdata = (java.util.List<java.lang.Integer>) _is.read(cache_veclogdata, 2, false);
		this.cmakeresult = _is.read(cmakeresult, 3, false);
	}

}
