// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.yoooum.tars.account;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class TBackGarden {

	@TarsStructProperty(order = 0, isRequire = false)
	public byte cstatus = (byte)0;

	public byte getCstatus() {
		return cstatus;
	}

	public void setCstatus(byte cstatus) {
		this.cstatus = cstatus;
	}

	public TBackGarden() {
	}

	public TBackGarden(byte cstatus) {
		this.cstatus = cstatus;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(cstatus);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof TBackGarden)) {
			return false;
		}
		TBackGarden other = (TBackGarden) obj;
		return (
			TarsUtil.equals(cstatus, other.cstatus) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(cstatus, 0);
	}


	public void readFrom(TarsInputStream _is) {
		this.cstatus = _is.read(cstatus, 0, false);
	}

}
