// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.yoooum.tars.account;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class TBackRoomData {

	@TarsStructProperty(order = 0, isRequire = false)
	public short shcuruseboyfriend = (short)0;
	@TarsStructProperty(order = 1, isRequire = false)
	public long ulastawardcollecttime = 0L;
	@TarsStructProperty(order = 2, isRequire = false)
	public java.util.List<java.lang.Integer> veccollectorawardpoint = null;
	@TarsStructProperty(order = 3, isRequire = false)
	public TBRCollecInfo stlimitquantityinfo = null;
	@TarsStructProperty(order = 4, isRequire = false)
	public TBRCollecInfo stlovefateinfo = null;
	@TarsStructProperty(order = 5, isRequire = false)
	public TBRCollecInfo stnpccollecinfo = null;
	@TarsStructProperty(order = 6, isRequire = false)
	public TBRCollecInfo stcatcollecinfo = null;
	@TarsStructProperty(order = 7, isRequire = false)
	public TGameCollectInfo stgamecollectinfo = null;
	@TarsStructProperty(order = 8, isRequire = false)
	public TBRCollecInfo stcgcollect = null;

	public short getShcuruseboyfriend() {
		return shcuruseboyfriend;
	}

	public void setShcuruseboyfriend(short shcuruseboyfriend) {
		this.shcuruseboyfriend = shcuruseboyfriend;
	}

	public long getUlastawardcollecttime() {
		return ulastawardcollecttime;
	}

	public void setUlastawardcollecttime(long ulastawardcollecttime) {
		this.ulastawardcollecttime = ulastawardcollecttime;
	}

	public java.util.List<java.lang.Integer> getVeccollectorawardpoint() {
		return veccollectorawardpoint;
	}

	public void setVeccollectorawardpoint(java.util.List<java.lang.Integer> veccollectorawardpoint) {
		this.veccollectorawardpoint = veccollectorawardpoint;
	}

	public TBRCollecInfo getStlimitquantityinfo() {
		return stlimitquantityinfo;
	}

	public void setStlimitquantityinfo(TBRCollecInfo stlimitquantityinfo) {
		this.stlimitquantityinfo = stlimitquantityinfo;
	}

	public TBRCollecInfo getStlovefateinfo() {
		return stlovefateinfo;
	}

	public void setStlovefateinfo(TBRCollecInfo stlovefateinfo) {
		this.stlovefateinfo = stlovefateinfo;
	}

	public TBRCollecInfo getStnpccollecinfo() {
		return stnpccollecinfo;
	}

	public void setStnpccollecinfo(TBRCollecInfo stnpccollecinfo) {
		this.stnpccollecinfo = stnpccollecinfo;
	}

	public TBRCollecInfo getStcatcollecinfo() {
		return stcatcollecinfo;
	}

	public void setStcatcollecinfo(TBRCollecInfo stcatcollecinfo) {
		this.stcatcollecinfo = stcatcollecinfo;
	}

	public TGameCollectInfo getStgamecollectinfo() {
		return stgamecollectinfo;
	}

	public void setStgamecollectinfo(TGameCollectInfo stgamecollectinfo) {
		this.stgamecollectinfo = stgamecollectinfo;
	}

	public TBRCollecInfo getStcgcollect() {
		return stcgcollect;
	}

	public void setStcgcollect(TBRCollecInfo stcgcollect) {
		this.stcgcollect = stcgcollect;
	}

	public TBackRoomData() {
	}

	public TBackRoomData(short shcuruseboyfriend, long ulastawardcollecttime, java.util.List<java.lang.Integer> veccollectorawardpoint, TBRCollecInfo stlimitquantityinfo, TBRCollecInfo stlovefateinfo, TBRCollecInfo stnpccollecinfo, TBRCollecInfo stcatcollecinfo, TGameCollectInfo stgamecollectinfo, TBRCollecInfo stcgcollect) {
		this.shcuruseboyfriend = shcuruseboyfriend;
		this.ulastawardcollecttime = ulastawardcollecttime;
		this.veccollectorawardpoint = veccollectorawardpoint;
		this.stlimitquantityinfo = stlimitquantityinfo;
		this.stlovefateinfo = stlovefateinfo;
		this.stnpccollecinfo = stnpccollecinfo;
		this.stcatcollecinfo = stcatcollecinfo;
		this.stgamecollectinfo = stgamecollectinfo;
		this.stcgcollect = stcgcollect;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(shcuruseboyfriend);
		result = prime * result + TarsUtil.hashCode(ulastawardcollecttime);
		result = prime * result + TarsUtil.hashCode(veccollectorawardpoint);
		result = prime * result + TarsUtil.hashCode(stlimitquantityinfo);
		result = prime * result + TarsUtil.hashCode(stlovefateinfo);
		result = prime * result + TarsUtil.hashCode(stnpccollecinfo);
		result = prime * result + TarsUtil.hashCode(stcatcollecinfo);
		result = prime * result + TarsUtil.hashCode(stgamecollectinfo);
		result = prime * result + TarsUtil.hashCode(stcgcollect);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof TBackRoomData)) {
			return false;
		}
		TBackRoomData other = (TBackRoomData) obj;
		return (
			TarsUtil.equals(shcuruseboyfriend, other.shcuruseboyfriend) &&
			TarsUtil.equals(ulastawardcollecttime, other.ulastawardcollecttime) &&
			TarsUtil.equals(veccollectorawardpoint, other.veccollectorawardpoint) &&
			TarsUtil.equals(stlimitquantityinfo, other.stlimitquantityinfo) &&
			TarsUtil.equals(stlovefateinfo, other.stlovefateinfo) &&
			TarsUtil.equals(stnpccollecinfo, other.stnpccollecinfo) &&
			TarsUtil.equals(stcatcollecinfo, other.stcatcollecinfo) &&
			TarsUtil.equals(stgamecollectinfo, other.stgamecollectinfo) &&
			TarsUtil.equals(stcgcollect, other.stcgcollect) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(shcuruseboyfriend, 0);
		_os.write(ulastawardcollecttime, 1);
		if (null != veccollectorawardpoint) {
			_os.write(veccollectorawardpoint, 2);
		}
		if (null != stlimitquantityinfo) {
			_os.write(stlimitquantityinfo, 3);
		}
		if (null != stlovefateinfo) {
			_os.write(stlovefateinfo, 4);
		}
		if (null != stnpccollecinfo) {
			_os.write(stnpccollecinfo, 5);
		}
		if (null != stcatcollecinfo) {
			_os.write(stcatcollecinfo, 6);
		}
		if (null != stgamecollectinfo) {
			_os.write(stgamecollectinfo, 7);
		}
		if (null != stcgcollect) {
			_os.write(stcgcollect, 8);
		}
	}

	static java.util.List<java.lang.Integer> cache_veccollectorawardpoint;
	static { 
		cache_veccollectorawardpoint = new java.util.ArrayList<java.lang.Integer>();
		int var_112 = 0;
		cache_veccollectorawardpoint.add(var_112);
	}
	static TBRCollecInfo cache_stlimitquantityinfo;
	static { 
		cache_stlimitquantityinfo = new TBRCollecInfo();
	}
	static TBRCollecInfo cache_stlovefateinfo;
	static { 
		cache_stlovefateinfo = new TBRCollecInfo();
	}
	static TBRCollecInfo cache_stnpccollecinfo;
	static { 
		cache_stnpccollecinfo = new TBRCollecInfo();
	}
	static TBRCollecInfo cache_stcatcollecinfo;
	static { 
		cache_stcatcollecinfo = new TBRCollecInfo();
	}
	static TGameCollectInfo cache_stgamecollectinfo;
	static { 
		cache_stgamecollectinfo = new TGameCollectInfo();
	}
	static TBRCollecInfo cache_stcgcollect;
	static { 
		cache_stcgcollect = new TBRCollecInfo();
	}

	public void readFrom(TarsInputStream _is) {
		this.shcuruseboyfriend = _is.read(shcuruseboyfriend, 0, false);
		this.ulastawardcollecttime = _is.read(ulastawardcollecttime, 1, false);
		this.veccollectorawardpoint = (java.util.List<java.lang.Integer>) _is.read(cache_veccollectorawardpoint, 2, false);
		this.stlimitquantityinfo = (TBRCollecInfo) _is.read(cache_stlimitquantityinfo, 3, false);
		this.stlovefateinfo = (TBRCollecInfo) _is.read(cache_stlovefateinfo, 4, false);
		this.stnpccollecinfo = (TBRCollecInfo) _is.read(cache_stnpccollecinfo, 5, false);
		this.stcatcollecinfo = (TBRCollecInfo) _is.read(cache_stcatcollecinfo, 6, false);
		this.stgamecollectinfo = (TGameCollectInfo) _is.read(cache_stgamecollectinfo, 7, false);
		this.stcgcollect = (TBRCollecInfo) _is.read(cache_stcgcollect, 8, false);
	}

}
