// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.yoooum.tars.account;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class TBoxStateItem {

	@TarsStructProperty(order = 0, isRequire = false)
	public int iBoxId = 0;
	@TarsStructProperty(order = 1, isRequire = false)
	public short iFreeTimes = (short)0;
	@TarsStructProperty(order = 2, isRequire = false)
	public int iNextFreeTM = 0;

	public int getIBoxId() {
		return iBoxId;
	}

	public void setIBoxId(int iBoxId) {
		this.iBoxId = iBoxId;
	}

	public short getIFreeTimes() {
		return iFreeTimes;
	}

	public void setIFreeTimes(short iFreeTimes) {
		this.iFreeTimes = iFreeTimes;
	}

	public int getINextFreeTM() {
		return iNextFreeTM;
	}

	public void setINextFreeTM(int iNextFreeTM) {
		this.iNextFreeTM = iNextFreeTM;
	}

	public TBoxStateItem() {
	}

	public TBoxStateItem(int iBoxId, short iFreeTimes, int iNextFreeTM) {
		this.iBoxId = iBoxId;
		this.iFreeTimes = iFreeTimes;
		this.iNextFreeTM = iNextFreeTM;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(iBoxId);
		result = prime * result + TarsUtil.hashCode(iFreeTimes);
		result = prime * result + TarsUtil.hashCode(iNextFreeTM);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof TBoxStateItem)) {
			return false;
		}
		TBoxStateItem other = (TBoxStateItem) obj;
		return (
			TarsUtil.equals(iBoxId, other.iBoxId) &&
			TarsUtil.equals(iFreeTimes, other.iFreeTimes) &&
			TarsUtil.equals(iNextFreeTM, other.iNextFreeTM) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(iBoxId, 0);
		_os.write(iFreeTimes, 1);
		_os.write(iNextFreeTM, 2);
	}


	public void readFrom(TarsInputStream _is) {
		this.iBoxId = _is.read(iBoxId, 0, false);
		this.iFreeTimes = _is.read(iFreeTimes, 1, false);
		this.iNextFreeTM = _is.read(iNextFreeTM, 2, false);
	}

}
