// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.yoooum.tars.account;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class TBRCollecInfo {

	@TarsStructProperty(order = 1, isRequire = false)
	public java.util.List<java.lang.Integer> veccollect = null;

	public java.util.List<java.lang.Integer> getVeccollect() {
		return veccollect;
	}

	public void setVeccollect(java.util.List<java.lang.Integer> veccollect) {
		this.veccollect = veccollect;
	}

	public TBRCollecInfo() {
	}

	public TBRCollecInfo(java.util.List<java.lang.Integer> veccollect) {
		this.veccollect = veccollect;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(veccollect);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof TBRCollecInfo)) {
			return false;
		}
		TBRCollecInfo other = (TBRCollecInfo) obj;
		return (
			TarsUtil.equals(veccollect, other.veccollect) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		if (null != veccollect) {
			_os.write(veccollect, 1);
		}
	}

	static java.util.List<java.lang.Integer> cache_veccollect;
	static { 
		cache_veccollect = new java.util.ArrayList<java.lang.Integer>();
		int var_111 = 0;
		cache_veccollect.add(var_111);
	}

	public void readFrom(TarsInputStream _is) {
		this.veccollect = (java.util.List<java.lang.Integer>) _is.read(cache_veccollect, 1, false);
	}

}
