// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.yoooum.tars.account;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class TCatEventInfo {

	@TarsStructProperty(order = 0, isRequire = false)
	public long ulasttrigtime = 0L;
	@TarsStructProperty(order = 1, isRequire = false)
	public java.util.List<TCatEventData> veceventcat = null;
	@TarsStructProperty(order = 2, isRequire = false)
	public long ulastentercatbacktrigtime = 0L;
	@TarsStructProperty(order = 3, isRequire = false)
	public long utimerangetrigtime = 0L;
	@TarsStructProperty(order = 4, isRequire = false)
	public short shonlinecomputetime = (short)0;
	@TarsStructProperty(order = 5, isRequire = false)
	public java.util.List<java.lang.Short> veceventid = null;

	public long getUlasttrigtime() {
		return ulasttrigtime;
	}

	public void setUlasttrigtime(long ulasttrigtime) {
		this.ulasttrigtime = ulasttrigtime;
	}

	public java.util.List<TCatEventData> getVeceventcat() {
		return veceventcat;
	}

	public void setVeceventcat(java.util.List<TCatEventData> veceventcat) {
		this.veceventcat = veceventcat;
	}

	public long getUlastentercatbacktrigtime() {
		return ulastentercatbacktrigtime;
	}

	public void setUlastentercatbacktrigtime(long ulastentercatbacktrigtime) {
		this.ulastentercatbacktrigtime = ulastentercatbacktrigtime;
	}

	public long getUtimerangetrigtime() {
		return utimerangetrigtime;
	}

	public void setUtimerangetrigtime(long utimerangetrigtime) {
		this.utimerangetrigtime = utimerangetrigtime;
	}

	public short getShonlinecomputetime() {
		return shonlinecomputetime;
	}

	public void setShonlinecomputetime(short shonlinecomputetime) {
		this.shonlinecomputetime = shonlinecomputetime;
	}

	public java.util.List<java.lang.Short> getVeceventid() {
		return veceventid;
	}

	public void setVeceventid(java.util.List<java.lang.Short> veceventid) {
		this.veceventid = veceventid;
	}

	public TCatEventInfo() {
	}

	public TCatEventInfo(long ulasttrigtime, java.util.List<TCatEventData> veceventcat, long ulastentercatbacktrigtime, long utimerangetrigtime, short shonlinecomputetime, java.util.List<java.lang.Short> veceventid) {
		this.ulasttrigtime = ulasttrigtime;
		this.veceventcat = veceventcat;
		this.ulastentercatbacktrigtime = ulastentercatbacktrigtime;
		this.utimerangetrigtime = utimerangetrigtime;
		this.shonlinecomputetime = shonlinecomputetime;
		this.veceventid = veceventid;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(ulasttrigtime);
		result = prime * result + TarsUtil.hashCode(veceventcat);
		result = prime * result + TarsUtil.hashCode(ulastentercatbacktrigtime);
		result = prime * result + TarsUtil.hashCode(utimerangetrigtime);
		result = prime * result + TarsUtil.hashCode(shonlinecomputetime);
		result = prime * result + TarsUtil.hashCode(veceventid);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof TCatEventInfo)) {
			return false;
		}
		TCatEventInfo other = (TCatEventInfo) obj;
		return (
			TarsUtil.equals(ulasttrigtime, other.ulasttrigtime) &&
			TarsUtil.equals(veceventcat, other.veceventcat) &&
			TarsUtil.equals(ulastentercatbacktrigtime, other.ulastentercatbacktrigtime) &&
			TarsUtil.equals(utimerangetrigtime, other.utimerangetrigtime) &&
			TarsUtil.equals(shonlinecomputetime, other.shonlinecomputetime) &&
			TarsUtil.equals(veceventid, other.veceventid) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(ulasttrigtime, 0);
		if (null != veceventcat) {
			_os.write(veceventcat, 1);
		}
		_os.write(ulastentercatbacktrigtime, 2);
		_os.write(utimerangetrigtime, 3);
		_os.write(shonlinecomputetime, 4);
		if (null != veceventid) {
			_os.write(veceventid, 5);
		}
	}

	static java.util.List<TCatEventData> cache_veceventcat;
	static { 
		cache_veceventcat = new java.util.ArrayList<TCatEventData>();
		TCatEventData var_63 = new TCatEventData();
		cache_veceventcat.add(var_63);
	}
	static java.util.List<java.lang.Short> cache_veceventid;
	static { 
		cache_veceventid = new java.util.ArrayList<java.lang.Short>();
		short var_64 = (short)0;
		cache_veceventid.add(var_64);
	}

	public void readFrom(TarsInputStream _is) {
		this.ulasttrigtime = _is.read(ulasttrigtime, 0, false);
		this.veceventcat = (java.util.List<TCatEventData>) _is.read(cache_veceventcat, 1, false);
		this.ulastentercatbacktrigtime = _is.read(ulastentercatbacktrigtime, 2, false);
		this.utimerangetrigtime = _is.read(utimerangetrigtime, 3, false);
		this.shonlinecomputetime = _is.read(shonlinecomputetime, 4, false);
		this.veceventid = (java.util.List<java.lang.Short>) _is.read(cache_veceventid, 5, false);
	}

}
