// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.yoooum.tars.account;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class TDailyEvent {

	@TarsStructProperty(order = 0, isRequire = false)
	public short uTitleID = (short)0;

	public short getUTitleID() {
		return uTitleID;
	}

	public void setUTitleID(short uTitleID) {
		this.uTitleID = uTitleID;
	}

	public TDailyEvent() {
	}

	public TDailyEvent(short uTitleID) {
		this.uTitleID = uTitleID;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(uTitleID);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof TDailyEvent)) {
			return false;
		}
		TDailyEvent other = (TDailyEvent) obj;
		return (
			TarsUtil.equals(uTitleID, other.uTitleID) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(uTitleID, 0);
	}


	public void readFrom(TarsInputStream _is) {
		this.uTitleID = _is.read(uTitleID, 0, false);
	}

}
