// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.yoooum.tars.account;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class TDBBranchProfile {

	@TarsStructProperty(order = 0, isRequire = false)
	public java.util.List<TProtagProfileData> vprofileinfo = null;
	@TarsStructProperty(order = 1, isRequire = false)
	public java.util.List<TProtagTopicData> vtopicinfo = null;

	public java.util.List<TProtagProfileData> getVprofileinfo() {
		return vprofileinfo;
	}

	public void setVprofileinfo(java.util.List<TProtagProfileData> vprofileinfo) {
		this.vprofileinfo = vprofileinfo;
	}

	public java.util.List<TProtagTopicData> getVtopicinfo() {
		return vtopicinfo;
	}

	public void setVtopicinfo(java.util.List<TProtagTopicData> vtopicinfo) {
		this.vtopicinfo = vtopicinfo;
	}

	public TDBBranchProfile() {
	}

	public TDBBranchProfile(java.util.List<TProtagProfileData> vprofileinfo, java.util.List<TProtagTopicData> vtopicinfo) {
		this.vprofileinfo = vprofileinfo;
		this.vtopicinfo = vtopicinfo;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(vprofileinfo);
		result = prime * result + TarsUtil.hashCode(vtopicinfo);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof TDBBranchProfile)) {
			return false;
		}
		TDBBranchProfile other = (TDBBranchProfile) obj;
		return (
			TarsUtil.equals(vprofileinfo, other.vprofileinfo) &&
			TarsUtil.equals(vtopicinfo, other.vtopicinfo) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		if (null != vprofileinfo) {
			_os.write(vprofileinfo, 0);
		}
		if (null != vtopicinfo) {
			_os.write(vtopicinfo, 1);
		}
	}

	static java.util.List<TProtagProfileData> cache_vprofileinfo;
	static { 
		cache_vprofileinfo = new java.util.ArrayList<TProtagProfileData>();
		TProtagProfileData var_23 = new TProtagProfileData();
		cache_vprofileinfo.add(var_23);
	}
	static java.util.List<TProtagTopicData> cache_vtopicinfo;
	static { 
		cache_vtopicinfo = new java.util.ArrayList<TProtagTopicData>();
		TProtagTopicData var_24 = new TProtagTopicData();
		cache_vtopicinfo.add(var_24);
	}

	public void readFrom(TarsInputStream _is) {
		this.vprofileinfo = (java.util.List<TProtagProfileData>) _is.read(cache_vprofileinfo, 0, false);
		this.vtopicinfo = (java.util.List<TProtagTopicData>) _is.read(cache_vtopicinfo, 1, false);
	}

}
