// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.yoooum.tars.account;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class TDBDailyTaskData {

	@TarsStructProperty(order = 0, isRequire = false)
	public java.util.List<TDBTaskCommonData> vecdata = null;
	@TarsStructProperty(order = 1, isRequire = false)
	public long lupdatetime = 0L;
	@TarsStructProperty(order = 2, isRequire = false)
	public short ndailyactivityvalue = (short)0;
	@TarsStructProperty(order = 3, isRequire = false)
	public java.util.List<java.lang.Integer> vecdailygiftgetid = null;

	public java.util.List<TDBTaskCommonData> getVecdata() {
		return vecdata;
	}

	public void setVecdata(java.util.List<TDBTaskCommonData> vecdata) {
		this.vecdata = vecdata;
	}

	public long getLupdatetime() {
		return lupdatetime;
	}

	public void setLupdatetime(long lupdatetime) {
		this.lupdatetime = lupdatetime;
	}

	public short getNdailyactivityvalue() {
		return ndailyactivityvalue;
	}

	public void setNdailyactivityvalue(short ndailyactivityvalue) {
		this.ndailyactivityvalue = ndailyactivityvalue;
	}

	public java.util.List<java.lang.Integer> getVecdailygiftgetid() {
		return vecdailygiftgetid;
	}

	public void setVecdailygiftgetid(java.util.List<java.lang.Integer> vecdailygiftgetid) {
		this.vecdailygiftgetid = vecdailygiftgetid;
	}

	public TDBDailyTaskData() {
	}

	public TDBDailyTaskData(java.util.List<TDBTaskCommonData> vecdata, long lupdatetime, short ndailyactivityvalue, java.util.List<java.lang.Integer> vecdailygiftgetid) {
		this.vecdata = vecdata;
		this.lupdatetime = lupdatetime;
		this.ndailyactivityvalue = ndailyactivityvalue;
		this.vecdailygiftgetid = vecdailygiftgetid;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(vecdata);
		result = prime * result + TarsUtil.hashCode(lupdatetime);
		result = prime * result + TarsUtil.hashCode(ndailyactivityvalue);
		result = prime * result + TarsUtil.hashCode(vecdailygiftgetid);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof TDBDailyTaskData)) {
			return false;
		}
		TDBDailyTaskData other = (TDBDailyTaskData) obj;
		return (
			TarsUtil.equals(vecdata, other.vecdata) &&
			TarsUtil.equals(lupdatetime, other.lupdatetime) &&
			TarsUtil.equals(ndailyactivityvalue, other.ndailyactivityvalue) &&
			TarsUtil.equals(vecdailygiftgetid, other.vecdailygiftgetid) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		if (null != vecdata) {
			_os.write(vecdata, 0);
		}
		_os.write(lupdatetime, 1);
		_os.write(ndailyactivityvalue, 2);
		if (null != vecdailygiftgetid) {
			_os.write(vecdailygiftgetid, 3);
		}
	}

	static java.util.List<TDBTaskCommonData> cache_vecdata;
	static { 
		cache_vecdata = new java.util.ArrayList<TDBTaskCommonData>();
		TDBTaskCommonData var_25 = new TDBTaskCommonData();
		cache_vecdata.add(var_25);
	}
	static java.util.List<java.lang.Integer> cache_vecdailygiftgetid;
	static { 
		cache_vecdailygiftgetid = new java.util.ArrayList<java.lang.Integer>();
		int var_26 = 0;
		cache_vecdailygiftgetid.add(var_26);
	}

	public void readFrom(TarsInputStream _is) {
		this.vecdata = (java.util.List<TDBTaskCommonData>) _is.read(cache_vecdata, 0, false);
		this.lupdatetime = _is.read(lupdatetime, 1, false);
		this.ndailyactivityvalue = _is.read(ndailyactivityvalue, 2, false);
		this.vecdailygiftgetid = (java.util.List<java.lang.Integer>) _is.read(cache_vecdailygiftgetid, 3, false);
	}

}
