// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.yoooum.tars.account;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class TDBDailyAttr {

	@TarsStructProperty(order = 0, isRequire = false)
	public short utotalsigncount = (short)0;
	@TarsStructProperty(order = 1, isRequire = false)
	public short utotalawardsignday = (short)0;
	@TarsStructProperty(order = 2, isRequire = false)
	public short uphoto = (short)0;
	@TarsStructProperty(order = 3, isRequire = false)
	public int irepairsignstatus = 0;
	@TarsStructProperty(order = 4, isRequire = false)
	public java.util.Map<java.lang.Long, TDailyEvent> mdailyeventinfo = null;

	public short getUtotalsigncount() {
		return utotalsigncount;
	}

	public void setUtotalsigncount(short utotalsigncount) {
		this.utotalsigncount = utotalsigncount;
	}

	public short getUtotalawardsignday() {
		return utotalawardsignday;
	}

	public void setUtotalawardsignday(short utotalawardsignday) {
		this.utotalawardsignday = utotalawardsignday;
	}

	public short getUphoto() {
		return uphoto;
	}

	public void setUphoto(short uphoto) {
		this.uphoto = uphoto;
	}

	public int getIrepairsignstatus() {
		return irepairsignstatus;
	}

	public void setIrepairsignstatus(int irepairsignstatus) {
		this.irepairsignstatus = irepairsignstatus;
	}

	public java.util.Map<java.lang.Long, TDailyEvent> getMdailyeventinfo() {
		return mdailyeventinfo;
	}

	public void setMdailyeventinfo(java.util.Map<java.lang.Long, TDailyEvent> mdailyeventinfo) {
		this.mdailyeventinfo = mdailyeventinfo;
	}

	public TDBDailyAttr() {
	}

	public TDBDailyAttr(short utotalsigncount, short utotalawardsignday, short uphoto, int irepairsignstatus, java.util.Map<java.lang.Long, TDailyEvent> mdailyeventinfo) {
		this.utotalsigncount = utotalsigncount;
		this.utotalawardsignday = utotalawardsignday;
		this.uphoto = uphoto;
		this.irepairsignstatus = irepairsignstatus;
		this.mdailyeventinfo = mdailyeventinfo;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(utotalsigncount);
		result = prime * result + TarsUtil.hashCode(utotalawardsignday);
		result = prime * result + TarsUtil.hashCode(uphoto);
		result = prime * result + TarsUtil.hashCode(irepairsignstatus);
		result = prime * result + TarsUtil.hashCode(mdailyeventinfo);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof TDBDailyAttr)) {
			return false;
		}
		TDBDailyAttr other = (TDBDailyAttr) obj;
		return (
			TarsUtil.equals(utotalsigncount, other.utotalsigncount) &&
			TarsUtil.equals(utotalawardsignday, other.utotalawardsignday) &&
			TarsUtil.equals(uphoto, other.uphoto) &&
			TarsUtil.equals(irepairsignstatus, other.irepairsignstatus) &&
			TarsUtil.equals(mdailyeventinfo, other.mdailyeventinfo) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(utotalsigncount, 0);
		_os.write(utotalawardsignday, 1);
		_os.write(uphoto, 2);
		_os.write(irepairsignstatus, 3);
		if (null != mdailyeventinfo) {
			_os.write(mdailyeventinfo, 4);
		}
	}

	static java.util.Map<java.lang.Long, TDailyEvent> cache_mdailyeventinfo;
	static { 
		cache_mdailyeventinfo = new java.util.HashMap<java.lang.Long, TDailyEvent>();
		long var_2 = 0L;
		TDailyEvent var_3 = new TDailyEvent();
		cache_mdailyeventinfo.put(var_2 ,var_3);
	}

	public void readFrom(TarsInputStream _is) {
		this.utotalsigncount = _is.read(utotalsigncount, 0, false);
		this.utotalawardsignday = _is.read(utotalawardsignday, 1, false);
		this.uphoto = _is.read(uphoto, 2, false);
		this.irepairsignstatus = _is.read(irepairsignstatus, 3, false);
		this.mdailyeventinfo = (java.util.Map<java.lang.Long, TDailyEvent>) _is.read(cache_mdailyeventinfo, 4, false);
	}

}
