// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.yoooum.tars.account;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class TDBGrowTaskData {

	@TarsStructProperty(order = 0, isRequire = true)
	public int icnt = 0;
	@TarsStructProperty(order = 1, isRequire = true)
	public java.util.List<TDBTaskCommonData> vecdata = null;
	@TarsStructProperty(order = 2, isRequire = true)
	public java.util.List<TDBGrowTaskGiftInfo> vecgrowtaskgiftinfo = null;

	public int getIcnt() {
		return icnt;
	}

	public void setIcnt(int icnt) {
		this.icnt = icnt;
	}

	public java.util.List<TDBTaskCommonData> getVecdata() {
		return vecdata;
	}

	public void setVecdata(java.util.List<TDBTaskCommonData> vecdata) {
		this.vecdata = vecdata;
	}

	public java.util.List<TDBGrowTaskGiftInfo> getVecgrowtaskgiftinfo() {
		return vecgrowtaskgiftinfo;
	}

	public void setVecgrowtaskgiftinfo(java.util.List<TDBGrowTaskGiftInfo> vecgrowtaskgiftinfo) {
		this.vecgrowtaskgiftinfo = vecgrowtaskgiftinfo;
	}

	public TDBGrowTaskData() {
	}

	public TDBGrowTaskData(int icnt, java.util.List<TDBTaskCommonData> vecdata, java.util.List<TDBGrowTaskGiftInfo> vecgrowtaskgiftinfo) {
		this.icnt = icnt;
		this.vecdata = vecdata;
		this.vecgrowtaskgiftinfo = vecgrowtaskgiftinfo;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(icnt);
		result = prime * result + TarsUtil.hashCode(vecdata);
		result = prime * result + TarsUtil.hashCode(vecgrowtaskgiftinfo);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof TDBGrowTaskData)) {
			return false;
		}
		TDBGrowTaskData other = (TDBGrowTaskData) obj;
		return (
			TarsUtil.equals(icnt, other.icnt) &&
			TarsUtil.equals(vecdata, other.vecdata) &&
			TarsUtil.equals(vecgrowtaskgiftinfo, other.vecgrowtaskgiftinfo) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(icnt, 0);
		_os.write(vecdata, 1);
		_os.write(vecgrowtaskgiftinfo, 2);
	}

	static java.util.List<TDBTaskCommonData> cache_vecdata;
	static { 
		cache_vecdata = new java.util.ArrayList<TDBTaskCommonData>();
		TDBTaskCommonData var_45 = new TDBTaskCommonData();
		cache_vecdata.add(var_45);
	}
	static java.util.List<TDBGrowTaskGiftInfo> cache_vecgrowtaskgiftinfo;
	static { 
		cache_vecgrowtaskgiftinfo = new java.util.ArrayList<TDBGrowTaskGiftInfo>();
		TDBGrowTaskGiftInfo var_46 = new TDBGrowTaskGiftInfo();
		cache_vecgrowtaskgiftinfo.add(var_46);
	}

	public void readFrom(TarsInputStream _is) {
		this.icnt = _is.read(icnt, 0, true);
		this.vecdata = (java.util.List<TDBTaskCommonData>) _is.read(cache_vecdata, 1, true);
		this.vecgrowtaskgiftinfo = (java.util.List<TDBGrowTaskGiftInfo>) _is.read(cache_vecgrowtaskgiftinfo, 2, true);
	}

}
