// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.yoooum.tars.account;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class TDBGuideTaskData {

	@TarsStructProperty(order = 0, isRequire = false)
	public TDBTaskCommonData stguideawarddata = null;
	@TarsStructProperty(order = 1, isRequire = false)
	public java.util.List<TDBTaskCommonData> vectaskchaindata = null;
	@TarsStructProperty(order = 2, isRequire = false)
	public java.util.List<TDBTaskCommonData> vectaskdata = null;

	public TDBTaskCommonData getStguideawarddata() {
		return stguideawarddata;
	}

	public void setStguideawarddata(TDBTaskCommonData stguideawarddata) {
		this.stguideawarddata = stguideawarddata;
	}

	public java.util.List<TDBTaskCommonData> getVectaskchaindata() {
		return vectaskchaindata;
	}

	public void setVectaskchaindata(java.util.List<TDBTaskCommonData> vectaskchaindata) {
		this.vectaskchaindata = vectaskchaindata;
	}

	public java.util.List<TDBTaskCommonData> getVectaskdata() {
		return vectaskdata;
	}

	public void setVectaskdata(java.util.List<TDBTaskCommonData> vectaskdata) {
		this.vectaskdata = vectaskdata;
	}

	public TDBGuideTaskData() {
	}

	public TDBGuideTaskData(TDBTaskCommonData stguideawarddata, java.util.List<TDBTaskCommonData> vectaskchaindata, java.util.List<TDBTaskCommonData> vectaskdata) {
		this.stguideawarddata = stguideawarddata;
		this.vectaskchaindata = vectaskchaindata;
		this.vectaskdata = vectaskdata;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(stguideawarddata);
		result = prime * result + TarsUtil.hashCode(vectaskchaindata);
		result = prime * result + TarsUtil.hashCode(vectaskdata);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof TDBGuideTaskData)) {
			return false;
		}
		TDBGuideTaskData other = (TDBGuideTaskData) obj;
		return (
			TarsUtil.equals(stguideawarddata, other.stguideawarddata) &&
			TarsUtil.equals(vectaskchaindata, other.vectaskchaindata) &&
			TarsUtil.equals(vectaskdata, other.vectaskdata) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		if (null != stguideawarddata) {
			_os.write(stguideawarddata, 0);
		}
		if (null != vectaskchaindata) {
			_os.write(vectaskchaindata, 1);
		}
		if (null != vectaskdata) {
			_os.write(vectaskdata, 2);
		}
	}

	static TDBTaskCommonData cache_stguideawarddata;
	static { 
		cache_stguideawarddata = new TDBTaskCommonData();
	}
	static java.util.List<TDBTaskCommonData> cache_vectaskchaindata;
	static { 
		cache_vectaskchaindata = new java.util.ArrayList<TDBTaskCommonData>();
		TDBTaskCommonData var_47 = new TDBTaskCommonData();
		cache_vectaskchaindata.add(var_47);
	}
	static java.util.List<TDBTaskCommonData> cache_vectaskdata;
	static { 
		cache_vectaskdata = new java.util.ArrayList<TDBTaskCommonData>();
		TDBTaskCommonData var_48 = new TDBTaskCommonData();
		cache_vectaskdata.add(var_48);
	}

	public void readFrom(TarsInputStream _is) {
		this.stguideawarddata = (TDBTaskCommonData) _is.read(cache_stguideawarddata, 0, false);
		this.vectaskchaindata = (java.util.List<TDBTaskCommonData>) _is.read(cache_vectaskchaindata, 1, false);
		this.vectaskdata = (java.util.List<TDBTaskCommonData>) _is.read(cache_vectaskdata, 2, false);
	}

}
