// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.yoooum.tars.account;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class TDBMainTaskData {

	@TarsStructProperty(order = 0, isRequire = true)
	public java.util.Map<java.lang.Integer, TTaskStatusDb> mapdata = null;
	@TarsStructProperty(order = 1, isRequire = false)
	public java.util.Map<java.lang.Integer, java.lang.Short> mapchapterprogess = null;

	public java.util.Map<java.lang.Integer, TTaskStatusDb> getMapdata() {
		return mapdata;
	}

	public void setMapdata(java.util.Map<java.lang.Integer, TTaskStatusDb> mapdata) {
		this.mapdata = mapdata;
	}

	public java.util.Map<java.lang.Integer, java.lang.Short> getMapchapterprogess() {
		return mapchapterprogess;
	}

	public void setMapchapterprogess(java.util.Map<java.lang.Integer, java.lang.Short> mapchapterprogess) {
		this.mapchapterprogess = mapchapterprogess;
	}

	public TDBMainTaskData() {
	}

	public TDBMainTaskData(java.util.Map<java.lang.Integer, TTaskStatusDb> mapdata, java.util.Map<java.lang.Integer, java.lang.Short> mapchapterprogess) {
		this.mapdata = mapdata;
		this.mapchapterprogess = mapchapterprogess;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(mapdata);
		result = prime * result + TarsUtil.hashCode(mapchapterprogess);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof TDBMainTaskData)) {
			return false;
		}
		TDBMainTaskData other = (TDBMainTaskData) obj;
		return (
			TarsUtil.equals(mapdata, other.mapdata) &&
			TarsUtil.equals(mapchapterprogess, other.mapchapterprogess) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(mapdata, 0);
		if (null != mapchapterprogess) {
			_os.write(mapchapterprogess, 1);
		}
	}

	static java.util.Map<java.lang.Integer, TTaskStatusDb> cache_mapdata;
	static { 
		cache_mapdata = new java.util.HashMap<java.lang.Integer, TTaskStatusDb>();
		int var_29 = 0;
		TTaskStatusDb var_30 = new TTaskStatusDb();
		cache_mapdata.put(var_29 ,var_30);
	}
	static java.util.Map<java.lang.Integer, java.lang.Short> cache_mapchapterprogess;
	static { 
		cache_mapchapterprogess = new java.util.HashMap<java.lang.Integer, java.lang.Short>();
		int var_31 = 0;
		short var_32 = (short)0;
		cache_mapchapterprogess.put(var_31 ,var_32);
	}

	public void readFrom(TarsInputStream _is) {
		this.mapdata = (java.util.Map<java.lang.Integer, TTaskStatusDb>) _is.read(cache_mapdata, 0, true);
		this.mapchapterprogess = (java.util.Map<java.lang.Integer, java.lang.Short>) _is.read(cache_mapchapterprogess, 1, false);
	}

}
