// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.yoooum.tars.account;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class TDBPetInfo {

	@TarsStructProperty(order = 0, isRequire = false)
	public java.util.List<TPetDb> vpetdb = null;
	@TarsStructProperty(order = 1, isRequire = false)
	public TRecruitDb strecruitdb = null;
	@TarsStructProperty(order = 2, isRequire = false)
	public TPetTaskDBInfo stpettaskdb = null;
	@TarsStructProperty(order = 3, isRequire = false)
	public long ubegintm = 0L;
	@TarsStructProperty(order = 4, isRequire = false)
	public short nfeedtimes = (short)0;
	@TarsStructProperty(order = 5, isRequire = false)
	public boolean bfree = false;
	@TarsStructProperty(order = 6, isRequire = false)
	public long uendtm = 0L;

	public java.util.List<TPetDb> getVpetdb() {
		return vpetdb;
	}

	public void setVpetdb(java.util.List<TPetDb> vpetdb) {
		this.vpetdb = vpetdb;
	}

	public TRecruitDb getStrecruitdb() {
		return strecruitdb;
	}

	public void setStrecruitdb(TRecruitDb strecruitdb) {
		this.strecruitdb = strecruitdb;
	}

	public TPetTaskDBInfo getStpettaskdb() {
		return stpettaskdb;
	}

	public void setStpettaskdb(TPetTaskDBInfo stpettaskdb) {
		this.stpettaskdb = stpettaskdb;
	}

	public long getUbegintm() {
		return ubegintm;
	}

	public void setUbegintm(long ubegintm) {
		this.ubegintm = ubegintm;
	}

	public short getNfeedtimes() {
		return nfeedtimes;
	}

	public void setNfeedtimes(short nfeedtimes) {
		this.nfeedtimes = nfeedtimes;
	}

	public boolean getBfree() {
		return bfree;
	}

	public void setBfree(boolean bfree) {
		this.bfree = bfree;
	}

	public long getUendtm() {
		return uendtm;
	}

	public void setUendtm(long uendtm) {
		this.uendtm = uendtm;
	}

	public TDBPetInfo() {
	}

	public TDBPetInfo(java.util.List<TPetDb> vpetdb, TRecruitDb strecruitdb, TPetTaskDBInfo stpettaskdb, long ubegintm, short nfeedtimes, boolean bfree, long uendtm) {
		this.vpetdb = vpetdb;
		this.strecruitdb = strecruitdb;
		this.stpettaskdb = stpettaskdb;
		this.ubegintm = ubegintm;
		this.nfeedtimes = nfeedtimes;
		this.bfree = bfree;
		this.uendtm = uendtm;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(vpetdb);
		result = prime * result + TarsUtil.hashCode(strecruitdb);
		result = prime * result + TarsUtil.hashCode(stpettaskdb);
		result = prime * result + TarsUtil.hashCode(ubegintm);
		result = prime * result + TarsUtil.hashCode(nfeedtimes);
		result = prime * result + TarsUtil.hashCode(bfree);
		result = prime * result + TarsUtil.hashCode(uendtm);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof TDBPetInfo)) {
			return false;
		}
		TDBPetInfo other = (TDBPetInfo) obj;
		return (
			TarsUtil.equals(vpetdb, other.vpetdb) &&
			TarsUtil.equals(strecruitdb, other.strecruitdb) &&
			TarsUtil.equals(stpettaskdb, other.stpettaskdb) &&
			TarsUtil.equals(ubegintm, other.ubegintm) &&
			TarsUtil.equals(nfeedtimes, other.nfeedtimes) &&
			TarsUtil.equals(bfree, other.bfree) &&
			TarsUtil.equals(uendtm, other.uendtm) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		if (null != vpetdb) {
			_os.write(vpetdb, 0);
		}
		if (null != strecruitdb) {
			_os.write(strecruitdb, 1);
		}
		if (null != stpettaskdb) {
			_os.write(stpettaskdb, 2);
		}
		_os.write(ubegintm, 3);
		_os.write(nfeedtimes, 4);
		_os.write(bfree, 5);
		_os.write(uendtm, 6);
	}

	static java.util.List<TPetDb> cache_vpetdb;
	static { 
		cache_vpetdb = new java.util.ArrayList<TPetDb>();
		TPetDb var_90 = new TPetDb();
		cache_vpetdb.add(var_90);
	}
	static TRecruitDb cache_strecruitdb;
	static { 
		cache_strecruitdb = new TRecruitDb();
	}
	static TPetTaskDBInfo cache_stpettaskdb;
	static { 
		cache_stpettaskdb = new TPetTaskDBInfo();
	}

	public void readFrom(TarsInputStream _is) {
		this.vpetdb = (java.util.List<TPetDb>) _is.read(cache_vpetdb, 0, false);
		this.strecruitdb = (TRecruitDb) _is.read(cache_strecruitdb, 1, false);
		this.stpettaskdb = (TPetTaskDBInfo) _is.read(cache_stpettaskdb, 2, false);
		this.ubegintm = _is.read(ubegintm, 3, false);
		this.nfeedtimes = _is.read(nfeedtimes, 4, false);
		this.bfree = _is.read(bfree, 5, false);
		this.uendtm = _is.read(uendtm, 6, false);
	}

}
