// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.yoooum.tars.account;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class TDBStage {

	@TarsStructProperty(order = 0, isRequire = true)
	public java.util.List<TStageInfo> vecstageinfo = null;

	public java.util.List<TStageInfo> getVecstageinfo() {
		return vecstageinfo;
	}

	public void setVecstageinfo(java.util.List<TStageInfo> vecstageinfo) {
		this.vecstageinfo = vecstageinfo;
	}

	public TDBStage() {
	}

	public TDBStage(java.util.List<TStageInfo> vecstageinfo) {
		this.vecstageinfo = vecstageinfo;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(vecstageinfo);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof TDBStage)) {
			return false;
		}
		TDBStage other = (TDBStage) obj;
		return (
			TarsUtil.equals(vecstageinfo, other.vecstageinfo) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(vecstageinfo, 0);
	}

	static java.util.List<TStageInfo> cache_vecstageinfo;
	static { 
		cache_vecstageinfo = new java.util.ArrayList<TStageInfo>();
		TStageInfo var_12 = new TStageInfo();
		cache_vecstageinfo.add(var_12);
	}

	public void readFrom(TarsInputStream _is) {
		this.vecstageinfo = (java.util.List<TStageInfo>) _is.read(cache_vecstageinfo, 0, true);
	}

}
