// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.yoooum.tars.account;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class TDBShoppingTaskData {

	@TarsStructProperty(order = 0, isRequire = false)
	public long urefreshtask = 0;
	@TarsStructProperty(order = 1, isRequire = false)
	public java.util.Map<java.lang.Integer, TTaskStatusDb> mapeightdiagramsdata = null;
	@TarsStructProperty(order = 2, isRequire = false)
	public java.util.Map<java.lang.Integer, TDBExporeTaskData> mapexporedata = null;
	@TarsStructProperty(order = 3, isRequire = false)
	public java.util.List<TEightDiagramsItem> veceightdiagramslist = null;
	@TarsStructProperty(order = 4, isRequire = false)
	public long urefreshpoint = 0;
	@TarsStructProperty(order = 5, isRequire = false)
	public java.util.Map<java.lang.Integer, java.util.Map<java.lang.Integer, java.lang.Short>> mmEightDiagramsDesireNpc = null;
	@TarsStructProperty(order = 6, isRequire = false)
	public long ulastbuypointtime = 0;
	@TarsStructProperty(order = 7, isRequire = false)
	public long ubuynum = 0;
	@TarsStructProperty(order = 8, isRequire = false)
	public short nrefreshtaskcnt = 0;

	public long getUrefreshtask() {
		return urefreshtask;
	}

	public void setUrefreshtask(long urefreshtask) {
		this.urefreshtask = urefreshtask;
	}

	public java.util.Map<java.lang.Integer, TTaskStatusDb> getMapeightdiagramsdata() {
		return mapeightdiagramsdata;
	}

	public void setMapeightdiagramsdata(java.util.Map<java.lang.Integer, TTaskStatusDb> mapeightdiagramsdata) {
		this.mapeightdiagramsdata = mapeightdiagramsdata;
	}

	public java.util.Map<java.lang.Integer, TDBExporeTaskData> getMapexporedata() {
		return mapexporedata;
	}

	public void setMapexporedata(java.util.Map<java.lang.Integer, TDBExporeTaskData> mapexporedata) {
		this.mapexporedata = mapexporedata;
	}

	public java.util.List<TEightDiagramsItem> getVeceightdiagramslist() {
		return veceightdiagramslist;
	}

	public void setVeceightdiagramslist(java.util.List<TEightDiagramsItem> veceightdiagramslist) {
		this.veceightdiagramslist = veceightdiagramslist;
	}

	public long getUrefreshpoint() {
		return urefreshpoint;
	}

	public void setUrefreshpoint(long urefreshpoint) {
		this.urefreshpoint = urefreshpoint;
	}

	public java.util.Map<java.lang.Integer, java.util.Map<java.lang.Integer, java.lang.Short>> getMmEightDiagramsDesireNpc() {
		return mmEightDiagramsDesireNpc;
	}

	public void setMmEightDiagramsDesireNpc(java.util.Map<java.lang.Integer, java.util.Map<java.lang.Integer, java.lang.Short>> mmEightDiagramsDesireNpc) {
		this.mmEightDiagramsDesireNpc = mmEightDiagramsDesireNpc;
	}

	public long getUlastbuypointtime() {
		return ulastbuypointtime;
	}

	public void setUlastbuypointtime(long ulastbuypointtime) {
		this.ulastbuypointtime = ulastbuypointtime;
	}

	public long getUbuynum() {
		return ubuynum;
	}

	public void setUbuynum(long ubuynum) {
		this.ubuynum = ubuynum;
	}

	public short getNrefreshtaskcnt() {
		return nrefreshtaskcnt;
	}

	public void setNrefreshtaskcnt(short nrefreshtaskcnt) {
		this.nrefreshtaskcnt = nrefreshtaskcnt;
	}

	public TDBShoppingTaskData() {
	}

	public TDBShoppingTaskData(long urefreshtask, java.util.Map<java.lang.Integer, TTaskStatusDb> mapeightdiagramsdata, java.util.Map<java.lang.Integer, TDBExporeTaskData> mapexporedata, java.util.List<TEightDiagramsItem> veceightdiagramslist, long urefreshpoint, java.util.Map<java.lang.Integer, java.util.Map<java.lang.Integer, java.lang.Short>> mmEightDiagramsDesireNpc, long ulastbuypointtime, long ubuynum, short nrefreshtaskcnt) {
		this.urefreshtask = urefreshtask;
		this.mapeightdiagramsdata = mapeightdiagramsdata;
		this.mapexporedata = mapexporedata;
		this.veceightdiagramslist = veceightdiagramslist;
		this.urefreshpoint = urefreshpoint;
		this.mmEightDiagramsDesireNpc = mmEightDiagramsDesireNpc;
		this.ulastbuypointtime = ulastbuypointtime;
		this.ubuynum = ubuynum;
		this.nrefreshtaskcnt = nrefreshtaskcnt;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(urefreshtask);
		result = prime * result + TarsUtil.hashCode(mapeightdiagramsdata);
		result = prime * result + TarsUtil.hashCode(mapexporedata);
		result = prime * result + TarsUtil.hashCode(veceightdiagramslist);
		result = prime * result + TarsUtil.hashCode(urefreshpoint);
		result = prime * result + TarsUtil.hashCode(mmEightDiagramsDesireNpc);
		result = prime * result + TarsUtil.hashCode(ulastbuypointtime);
		result = prime * result + TarsUtil.hashCode(ubuynum);
		result = prime * result + TarsUtil.hashCode(nrefreshtaskcnt);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof TDBShoppingTaskData)) {
			return false;
		}
		TDBShoppingTaskData other = (TDBShoppingTaskData) obj;
		return (
			TarsUtil.equals(urefreshtask, other.urefreshtask) &&
			TarsUtil.equals(mapeightdiagramsdata, other.mapeightdiagramsdata) &&
			TarsUtil.equals(mapexporedata, other.mapexporedata) &&
			TarsUtil.equals(veceightdiagramslist, other.veceightdiagramslist) &&
			TarsUtil.equals(urefreshpoint, other.urefreshpoint) &&
			TarsUtil.equals(mmEightDiagramsDesireNpc, other.mmEightDiagramsDesireNpc) &&
			TarsUtil.equals(ulastbuypointtime, other.ulastbuypointtime) &&
			TarsUtil.equals(ubuynum, other.ubuynum) &&
			TarsUtil.equals(nrefreshtaskcnt, other.nrefreshtaskcnt) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(urefreshtask, 0);
		if (null != mapeightdiagramsdata) {
			_os.write(mapeightdiagramsdata, 1);
		}
		if (null != mapexporedata) {
			_os.write(mapexporedata, 2);
		}
		if (null != veceightdiagramslist) {
			_os.write(veceightdiagramslist, 3);
		}
		_os.write(urefreshpoint, 4);
		if (null != mmEightDiagramsDesireNpc) {
			_os.write(mmEightDiagramsDesireNpc, 5);
		}
		_os.write(ulastbuypointtime, 6);
		_os.write(ubuynum, 7);
		_os.write(nrefreshtaskcnt, 8);
	}

	static java.util.Map<java.lang.Integer, TTaskStatusDb> cache_mapeightdiagramsdata;
	static { 
		cache_mapeightdiagramsdata = new java.util.HashMap<java.lang.Integer, TTaskStatusDb>();
		int var_35 = 0;
		TTaskStatusDb var_36 = new TTaskStatusDb();
		cache_mapeightdiagramsdata.put(var_35 ,var_36);
	}
	static java.util.Map<java.lang.Integer, TDBExporeTaskData> cache_mapexporedata;
	static { 
		cache_mapexporedata = new java.util.HashMap<java.lang.Integer, TDBExporeTaskData>();
		int var_37 = 0;
		TDBExporeTaskData var_38 = new TDBExporeTaskData();
		cache_mapexporedata.put(var_37 ,var_38);
	}
	static java.util.List<TEightDiagramsItem> cache_veceightdiagramslist;
	static { 
		cache_veceightdiagramslist = new java.util.ArrayList<TEightDiagramsItem>();
		TEightDiagramsItem var_39 = new TEightDiagramsItem();
		cache_veceightdiagramslist.add(var_39);
	}
	static java.util.Map<java.lang.Integer, java.util.Map<java.lang.Integer, java.lang.Short>> cache_mmEightDiagramsDesireNpc;
	static { 
		cache_mmEightDiagramsDesireNpc = new java.util.HashMap<java.lang.Integer, java.util.Map<java.lang.Integer, java.lang.Short>>();
		int var_40 = 0;
		java.util.Map<java.lang.Integer, java.lang.Short> var_41 = new java.util.HashMap<java.lang.Integer, java.lang.Short>();
		int var_42 = 0;
		short var_43 = (short)0;
		var_41.put(var_42 ,var_43);
		cache_mmEightDiagramsDesireNpc.put(var_40 ,var_41);
	}

	public void readFrom(TarsInputStream _is) {
		this.urefreshtask = _is.read(urefreshtask, 0, false);
		this.mapeightdiagramsdata = (java.util.Map<java.lang.Integer, TTaskStatusDb>) _is.read(cache_mapeightdiagramsdata, 1, false);
		this.mapexporedata = (java.util.Map<java.lang.Integer, TDBExporeTaskData>) _is.read(cache_mapexporedata, 2, false);
		this.veceightdiagramslist = (java.util.List<TEightDiagramsItem>) _is.read(cache_veceightdiagramslist, 3, false);
		this.urefreshpoint = _is.read(urefreshpoint, 4, false);
		this.mmEightDiagramsDesireNpc = (java.util.Map<java.lang.Integer, java.util.Map<java.lang.Integer, java.lang.Short>>) _is.read(cache_mmEightDiagramsDesireNpc, 5, false);
		this.ulastbuypointtime = _is.read(ulastbuypointtime, 6, false);
		this.ubuynum = _is.read(ubuynum, 7, false);
		this.nrefreshtaskcnt = _is.read(nrefreshtaskcnt, 8, false);
	}

}
