// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.yoooum.tars.account;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class TDBStoryStage {

	@TarsStructProperty(order = 0, isRequire = true)
	public java.util.List<TProtagonist> vecprotagonistinfo = null;

	public java.util.List<TProtagonist> getVecprotagonistinfo() {
		return vecprotagonistinfo;
	}

	public void setVecprotagonistinfo(java.util.List<TProtagonist> vecprotagonistinfo) {
		this.vecprotagonistinfo = vecprotagonistinfo;
	}

	public TDBStoryStage() {
	}

	public TDBStoryStage(java.util.List<TProtagonist> vecprotagonistinfo) {
		this.vecprotagonistinfo = vecprotagonistinfo;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(vecprotagonistinfo);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof TDBStoryStage)) {
			return false;
		}
		TDBStoryStage other = (TDBStoryStage) obj;
		return (
			TarsUtil.equals(vecprotagonistinfo, other.vecprotagonistinfo) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(vecprotagonistinfo, 0);
	}

	static java.util.List<TProtagonist> cache_vecprotagonistinfo;
	static { 
		cache_vecprotagonistinfo = new java.util.ArrayList<TProtagonist>();
		TProtagonist var_18 = new TProtagonist();
		cache_vecprotagonistinfo.add(var_18);
	}

	public void readFrom(TarsInputStream _is) {
		this.vecprotagonistinfo = (java.util.List<TProtagonist>) _is.read(cache_vecprotagonistinfo, 0, true);
	}

}
