// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.yoooum.tars.account;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class TDBTimeLimitTaskData {

	@TarsStructProperty(order = 0, isRequire = true)
	public int icnt = 0;
	@TarsStructProperty(order = 1, isRequire = true)
	public java.util.List<TDBTaskCommonData> vecdata = null;
	@TarsStructProperty(order = 2, isRequire = true)
	public int iflag = 0;
	@TarsStructProperty(order = 3, isRequire = true)
	public long lclearhasnewtasktime = 0L;

	public int getIcnt() {
		return icnt;
	}

	public void setIcnt(int icnt) {
		this.icnt = icnt;
	}

	public java.util.List<TDBTaskCommonData> getVecdata() {
		return vecdata;
	}

	public void setVecdata(java.util.List<TDBTaskCommonData> vecdata) {
		this.vecdata = vecdata;
	}

	public int getIflag() {
		return iflag;
	}

	public void setIflag(int iflag) {
		this.iflag = iflag;
	}

	public long getLclearhasnewtasktime() {
		return lclearhasnewtasktime;
	}

	public void setLclearhasnewtasktime(long lclearhasnewtasktime) {
		this.lclearhasnewtasktime = lclearhasnewtasktime;
	}

	public TDBTimeLimitTaskData() {
	}

	public TDBTimeLimitTaskData(int icnt, java.util.List<TDBTaskCommonData> vecdata, int iflag, long lclearhasnewtasktime) {
		this.icnt = icnt;
		this.vecdata = vecdata;
		this.iflag = iflag;
		this.lclearhasnewtasktime = lclearhasnewtasktime;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(icnt);
		result = prime * result + TarsUtil.hashCode(vecdata);
		result = prime * result + TarsUtil.hashCode(iflag);
		result = prime * result + TarsUtil.hashCode(lclearhasnewtasktime);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof TDBTimeLimitTaskData)) {
			return false;
		}
		TDBTimeLimitTaskData other = (TDBTimeLimitTaskData) obj;
		return (
			TarsUtil.equals(icnt, other.icnt) &&
			TarsUtil.equals(vecdata, other.vecdata) &&
			TarsUtil.equals(iflag, other.iflag) &&
			TarsUtil.equals(lclearhasnewtasktime, other.lclearhasnewtasktime) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(icnt, 0);
		_os.write(vecdata, 1);
		_os.write(iflag, 2);
		_os.write(lclearhasnewtasktime, 3);
	}

	static java.util.List<TDBTaskCommonData> cache_vecdata;
	static { 
		cache_vecdata = new java.util.ArrayList<TDBTaskCommonData>();
		TDBTaskCommonData var_44 = new TDBTaskCommonData();
		cache_vecdata.add(var_44);
	}

	public void readFrom(TarsInputStream _is) {
		this.icnt = _is.read(icnt, 0, true);
		this.vecdata = (java.util.List<TDBTaskCommonData>) _is.read(cache_vecdata, 1, true);
		this.iflag = _is.read(iflag, 2, true);
		this.lclearhasnewtasktime = _is.read(lclearhasnewtasktime, 3, true);
	}

}
