// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.yoooum.tars.account;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class TDBTaskCommonData {

	@TarsStructProperty(order = 0, isRequire = true)
	public int iid = 0;
	@TarsStructProperty(order = 1, isRequire = false)
	public long laccepttime = 0L;
	@TarsStructProperty(order = 2, isRequire = false)
	public short nawardflg = (short)0;
	@TarsStructProperty(order = 3, isRequire = false)
	public int itargetprocess = 0;
	@TarsStructProperty(order = 4, isRequire = false)
	public short nchainid = (short)0;
	@TarsStructProperty(order = 5, isRequire = false)
	public byte bytestatus = (byte)0;

	public int getIid() {
		return iid;
	}

	public void setIid(int iid) {
		this.iid = iid;
	}

	public long getLaccepttime() {
		return laccepttime;
	}

	public void setLaccepttime(long laccepttime) {
		this.laccepttime = laccepttime;
	}

	public short getNawardflg() {
		return nawardflg;
	}

	public void setNawardflg(short nawardflg) {
		this.nawardflg = nawardflg;
	}

	public int getItargetprocess() {
		return itargetprocess;
	}

	public void setItargetprocess(int itargetprocess) {
		this.itargetprocess = itargetprocess;
	}

	public short getNchainid() {
		return nchainid;
	}

	public void setNchainid(short nchainid) {
		this.nchainid = nchainid;
	}

	public byte getBytestatus() {
		return bytestatus;
	}

	public void setBytestatus(byte bytestatus) {
		this.bytestatus = bytestatus;
	}

	public TDBTaskCommonData() {
	}

	public TDBTaskCommonData(int iid, long laccepttime, short nawardflg, int itargetprocess, short nchainid, byte bytestatus) {
		this.iid = iid;
		this.laccepttime = laccepttime;
		this.nawardflg = nawardflg;
		this.itargetprocess = itargetprocess;
		this.nchainid = nchainid;
		this.bytestatus = bytestatus;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(iid);
		result = prime * result + TarsUtil.hashCode(laccepttime);
		result = prime * result + TarsUtil.hashCode(nawardflg);
		result = prime * result + TarsUtil.hashCode(itargetprocess);
		result = prime * result + TarsUtil.hashCode(nchainid);
		result = prime * result + TarsUtil.hashCode(bytestatus);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof TDBTaskCommonData)) {
			return false;
		}
		TDBTaskCommonData other = (TDBTaskCommonData) obj;
		return (
			TarsUtil.equals(iid, other.iid) &&
			TarsUtil.equals(laccepttime, other.laccepttime) &&
			TarsUtil.equals(nawardflg, other.nawardflg) &&
			TarsUtil.equals(itargetprocess, other.itargetprocess) &&
			TarsUtil.equals(nchainid, other.nchainid) &&
			TarsUtil.equals(bytestatus, other.bytestatus) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(iid, 0);
		_os.write(laccepttime, 1);
		_os.write(nawardflg, 2);
		_os.write(itargetprocess, 3);
		_os.write(nchainid, 4);
		_os.write(bytestatus, 5);
	}


	public void readFrom(TarsInputStream _is) {
		this.iid = _is.read(iid, 0, true);
		this.laccepttime = _is.read(laccepttime, 1, false);
		this.nawardflg = _is.read(nawardflg, 2, false);
		this.itargetprocess = _is.read(itargetprocess, 3, false);
		this.nchainid = _is.read(nchainid, 4, false);
		this.bytestatus = _is.read(bytestatus, 5, false);
	}

}
