// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.yoooum.tars.account;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class TDBWeekAttr {

	@TarsStructProperty(order = 0, isRequire = false)
	public long ulasttime = 0L;

	public long getUlasttime() {
		return ulasttime;
	}

	public void setUlasttime(long ulasttime) {
		this.ulasttime = ulasttime;
	}

	public TDBWeekAttr() {
	}

	public TDBWeekAttr(long ulasttime) {
		this.ulasttime = ulasttime;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(ulasttime);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof TDBWeekAttr)) {
			return false;
		}
		TDBWeekAttr other = (TDBWeekAttr) obj;
		return (
			TarsUtil.equals(ulasttime, other.ulasttime) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(ulasttime, 0);
	}


	public void readFrom(TarsInputStream _is) {
		this.ulasttime = _is.read(ulasttime, 0, false);
	}

}
