// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.yoooum.tars.account;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class TExplorationDBData {

	@TarsStructProperty(order = 0, isRequire = false)
	public java.util.List<THorseSlotDbData> vhorseslotdata = null;
	@TarsStructProperty(order = 1, isRequire = false)
	public java.util.List<TExplorMapDbData> vmapdata = null;
	@TarsStructProperty(order = 2, isRequire = false)
	public int iexplorscore = 0;

	public java.util.List<THorseSlotDbData> getVhorseslotdata() {
		return vhorseslotdata;
	}

	public void setVhorseslotdata(java.util.List<THorseSlotDbData> vhorseslotdata) {
		this.vhorseslotdata = vhorseslotdata;
	}

	public java.util.List<TExplorMapDbData> getVmapdata() {
		return vmapdata;
	}

	public void setVmapdata(java.util.List<TExplorMapDbData> vmapdata) {
		this.vmapdata = vmapdata;
	}

	public int getIexplorscore() {
		return iexplorscore;
	}

	public void setIexplorscore(int iexplorscore) {
		this.iexplorscore = iexplorscore;
	}

	public TExplorationDBData() {
	}

	public TExplorationDBData(java.util.List<THorseSlotDbData> vhorseslotdata, java.util.List<TExplorMapDbData> vmapdata, int iexplorscore) {
		this.vhorseslotdata = vhorseslotdata;
		this.vmapdata = vmapdata;
		this.iexplorscore = iexplorscore;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(vhorseslotdata);
		result = prime * result + TarsUtil.hashCode(vmapdata);
		result = prime * result + TarsUtil.hashCode(iexplorscore);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof TExplorationDBData)) {
			return false;
		}
		TExplorationDBData other = (TExplorationDBData) obj;
		return (
			TarsUtil.equals(vhorseslotdata, other.vhorseslotdata) &&
			TarsUtil.equals(vmapdata, other.vmapdata) &&
			TarsUtil.equals(iexplorscore, other.iexplorscore) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		if (null != vhorseslotdata) {
			_os.write(vhorseslotdata, 0);
		}
		if (null != vmapdata) {
			_os.write(vmapdata, 1);
		}
		_os.write(iexplorscore, 2);
	}

	static java.util.List<THorseSlotDbData> cache_vhorseslotdata;
	static { 
		cache_vhorseslotdata = new java.util.ArrayList<THorseSlotDbData>();
		THorseSlotDbData var_95 = new THorseSlotDbData();
		cache_vhorseslotdata.add(var_95);
	}
	static java.util.List<TExplorMapDbData> cache_vmapdata;
	static { 
		cache_vmapdata = new java.util.ArrayList<TExplorMapDbData>();
		TExplorMapDbData var_96 = new TExplorMapDbData();
		cache_vmapdata.add(var_96);
	}

	public void readFrom(TarsInputStream _is) {
		this.vhorseslotdata = (java.util.List<THorseSlotDbData>) _is.read(cache_vhorseslotdata, 0, false);
		this.vmapdata = (java.util.List<TExplorMapDbData>) _is.read(cache_vmapdata, 1, false);
		this.iexplorscore = _is.read(iexplorscore, 2, false);
	}

}
