// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.yoooum.tars.account;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class TExplorEventInfo {

	@TarsStructProperty(order = 0, isRequire = false)
	public int iid = 0;
	@TarsStructProperty(order = 1, isRequire = false)
	public byte iresult = (byte)0;
	@TarsStructProperty(order = 2, isRequire = false)
	public java.util.List<TPropDbInfo> vecprop = null;
	@TarsStructProperty(order = 4, isRequire = false)
	public byte cuseprop = (byte)0;
	@TarsStructProperty(order = 5, isRequire = false)
	public short shdelhp = (short)0;
	@TarsStructProperty(order = 6, isRequire = false)
	public short shcurhp = (short)0;

	public int getIid() {
		return iid;
	}

	public void setIid(int iid) {
		this.iid = iid;
	}

	public byte getIresult() {
		return iresult;
	}

	public void setIresult(byte iresult) {
		this.iresult = iresult;
	}

	public java.util.List<TPropDbInfo> getVecprop() {
		return vecprop;
	}

	public void setVecprop(java.util.List<TPropDbInfo> vecprop) {
		this.vecprop = vecprop;
	}

	public byte getCuseprop() {
		return cuseprop;
	}

	public void setCuseprop(byte cuseprop) {
		this.cuseprop = cuseprop;
	}

	public short getShdelhp() {
		return shdelhp;
	}

	public void setShdelhp(short shdelhp) {
		this.shdelhp = shdelhp;
	}

	public short getShcurhp() {
		return shcurhp;
	}

	public void setShcurhp(short shcurhp) {
		this.shcurhp = shcurhp;
	}

	public TExplorEventInfo() {
	}

	public TExplorEventInfo(int iid, byte iresult, java.util.List<TPropDbInfo> vecprop, byte cuseprop, short shdelhp, short shcurhp) {
		this.iid = iid;
		this.iresult = iresult;
		this.vecprop = vecprop;
		this.cuseprop = cuseprop;
		this.shdelhp = shdelhp;
		this.shcurhp = shcurhp;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(iid);
		result = prime * result + TarsUtil.hashCode(iresult);
		result = prime * result + TarsUtil.hashCode(vecprop);
		result = prime * result + TarsUtil.hashCode(cuseprop);
		result = prime * result + TarsUtil.hashCode(shdelhp);
		result = prime * result + TarsUtil.hashCode(shcurhp);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof TExplorEventInfo)) {
			return false;
		}
		TExplorEventInfo other = (TExplorEventInfo) obj;
		return (
			TarsUtil.equals(iid, other.iid) &&
			TarsUtil.equals(iresult, other.iresult) &&
			TarsUtil.equals(vecprop, other.vecprop) &&
			TarsUtil.equals(cuseprop, other.cuseprop) &&
			TarsUtil.equals(shdelhp, other.shdelhp) &&
			TarsUtil.equals(shcurhp, other.shcurhp) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(iid, 0);
		_os.write(iresult, 1);
		if (null != vecprop) {
			_os.write(vecprop, 2);
		}
		_os.write(cuseprop, 4);
		_os.write(shdelhp, 5);
		_os.write(shcurhp, 6);
	}

	static java.util.List<TPropDbInfo> cache_vecprop;
	static { 
		cache_vecprop = new java.util.ArrayList<TPropDbInfo>();
		TPropDbInfo var_91 = new TPropDbInfo();
		cache_vecprop.add(var_91);
	}

	public void readFrom(TarsInputStream _is) {
		this.iid = _is.read(iid, 0, false);
		this.iresult = _is.read(iresult, 1, false);
		this.vecprop = (java.util.List<TPropDbInfo>) _is.read(cache_vecprop, 2, false);
		this.cuseprop = _is.read(cuseprop, 4, false);
		this.shdelhp = _is.read(shdelhp, 5, false);
		this.shcurhp = _is.read(shcurhp, 6, false);
	}

}
