// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.yoooum.tars.account;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class TExtData1 {

	@TarsStructProperty(order = 0, isRequire = false)
	public TActiveCodeDb stActiveCodeDb = null;
	@TarsStructProperty(order = 1, isRequire = false)
	public java.util.Map<java.lang.Integer, TBuyStatusDb> mBuyItemStatDb = null;
	@TarsStructProperty(order = 2, isRequire = false)
	public java.util.List<java.lang.Integer> vecDaySelectionSaleItem = null;
	@TarsStructProperty(order = 3, isRequire = false)
	public long lDaySelectionTM = 0L;
	@TarsStructProperty(order = 4, isRequire = false)
	public short nSilverBoxFreeTimes = (short)0;
	@TarsStructProperty(order = 5, isRequire = false)
	public long lDrawSilverBoxTM = 0L;
	@TarsStructProperty(order = 6, isRequire = false)
	public short nGoldBoxFreeTimes = (short)0;
	@TarsStructProperty(order = 7, isRequire = false)
	public long lDrawGoldBoxTM = 0L;
	@TarsStructProperty(order = 8, isRequire = false)
	public short nPurpleBoxFreeTimes = (short)0;
	@TarsStructProperty(order = 9, isRequire = false)
	public long lDrawPurpleBoxTM = 0L;
	@TarsStructProperty(order = 10, isRequire = false)
	public int iResumeVitNumByAD = 0;
	@TarsStructProperty(order = 11, isRequire = false)
	public long lLastResumeVitTM = 0L;
	@TarsStructProperty(order = 12, isRequire = false)
	public TDBNewbieData stNewbieData = null;
	@TarsStructProperty(order = 13, isRequire = false)
	public short nADTurnTableCnt = (short)0;
	@TarsStructProperty(order = 14, isRequire = false)
	public int iADPoolID = 0;
	@TarsStructProperty(order = 15, isRequire = false)
	public long lLastResumeADCntTM = 0L;
	@TarsStructProperty(order = 16, isRequire = false)
	public java.util.List<TBuyLimitItemStatusDb> vecLimitSaleItem = null;
	@TarsStructProperty(order = 17, isRequire = false)
	public java.util.Map<java.lang.Integer, java.lang.Integer> mOpenBoxHistory = null;
	@TarsStructProperty(order = 18, isRequire = false)
	public java.util.List<java.lang.Integer> vecAllSvrMailRecord = null;
	@TarsStructProperty(order = 19, isRequire = false)
	public java.util.Map<java.lang.Integer, TBuyStatusDb> mFirstBuyItemStatDb = null;

	public TActiveCodeDb getStActiveCodeDb() {
		return stActiveCodeDb;
	}

	public void setStActiveCodeDb(TActiveCodeDb stActiveCodeDb) {
		this.stActiveCodeDb = stActiveCodeDb;
	}

	public java.util.Map<java.lang.Integer, TBuyStatusDb> getMBuyItemStatDb() {
		return mBuyItemStatDb;
	}

	public void setMBuyItemStatDb(java.util.Map<java.lang.Integer, TBuyStatusDb> mBuyItemStatDb) {
		this.mBuyItemStatDb = mBuyItemStatDb;
	}

	public java.util.List<java.lang.Integer> getVecDaySelectionSaleItem() {
		return vecDaySelectionSaleItem;
	}

	public void setVecDaySelectionSaleItem(java.util.List<java.lang.Integer> vecDaySelectionSaleItem) {
		this.vecDaySelectionSaleItem = vecDaySelectionSaleItem;
	}

	public long getLDaySelectionTM() {
		return lDaySelectionTM;
	}

	public void setLDaySelectionTM(long lDaySelectionTM) {
		this.lDaySelectionTM = lDaySelectionTM;
	}

	public short getNSilverBoxFreeTimes() {
		return nSilverBoxFreeTimes;
	}

	public void setNSilverBoxFreeTimes(short nSilverBoxFreeTimes) {
		this.nSilverBoxFreeTimes = nSilverBoxFreeTimes;
	}

	public long getLDrawSilverBoxTM() {
		return lDrawSilverBoxTM;
	}

	public void setLDrawSilverBoxTM(long lDrawSilverBoxTM) {
		this.lDrawSilverBoxTM = lDrawSilverBoxTM;
	}

	public short getNGoldBoxFreeTimes() {
		return nGoldBoxFreeTimes;
	}

	public void setNGoldBoxFreeTimes(short nGoldBoxFreeTimes) {
		this.nGoldBoxFreeTimes = nGoldBoxFreeTimes;
	}

	public long getLDrawGoldBoxTM() {
		return lDrawGoldBoxTM;
	}

	public void setLDrawGoldBoxTM(long lDrawGoldBoxTM) {
		this.lDrawGoldBoxTM = lDrawGoldBoxTM;
	}

	public short getNPurpleBoxFreeTimes() {
		return nPurpleBoxFreeTimes;
	}

	public void setNPurpleBoxFreeTimes(short nPurpleBoxFreeTimes) {
		this.nPurpleBoxFreeTimes = nPurpleBoxFreeTimes;
	}

	public long getLDrawPurpleBoxTM() {
		return lDrawPurpleBoxTM;
	}

	public void setLDrawPurpleBoxTM(long lDrawPurpleBoxTM) {
		this.lDrawPurpleBoxTM = lDrawPurpleBoxTM;
	}

	public int getIResumeVitNumByAD() {
		return iResumeVitNumByAD;
	}

	public void setIResumeVitNumByAD(int iResumeVitNumByAD) {
		this.iResumeVitNumByAD = iResumeVitNumByAD;
	}

	public long getLLastResumeVitTM() {
		return lLastResumeVitTM;
	}

	public void setLLastResumeVitTM(long lLastResumeVitTM) {
		this.lLastResumeVitTM = lLastResumeVitTM;
	}

	public TDBNewbieData getStNewbieData() {
		return stNewbieData;
	}

	public void setStNewbieData(TDBNewbieData stNewbieData) {
		this.stNewbieData = stNewbieData;
	}

	public short getNADTurnTableCnt() {
		return nADTurnTableCnt;
	}

	public void setNADTurnTableCnt(short nADTurnTableCnt) {
		this.nADTurnTableCnt = nADTurnTableCnt;
	}

	public int getIADPoolID() {
		return iADPoolID;
	}

	public void setIADPoolID(int iADPoolID) {
		this.iADPoolID = iADPoolID;
	}

	public long getLLastResumeADCntTM() {
		return lLastResumeADCntTM;
	}

	public void setLLastResumeADCntTM(long lLastResumeADCntTM) {
		this.lLastResumeADCntTM = lLastResumeADCntTM;
	}

	public java.util.List<TBuyLimitItemStatusDb> getVecLimitSaleItem() {
		return vecLimitSaleItem;
	}

	public void setVecLimitSaleItem(java.util.List<TBuyLimitItemStatusDb> vecLimitSaleItem) {
		this.vecLimitSaleItem = vecLimitSaleItem;
	}

	public java.util.Map<java.lang.Integer, java.lang.Integer> getMOpenBoxHistory() {
		return mOpenBoxHistory;
	}

	public void setMOpenBoxHistory(java.util.Map<java.lang.Integer, java.lang.Integer> mOpenBoxHistory) {
		this.mOpenBoxHistory = mOpenBoxHistory;
	}

	public java.util.List<java.lang.Integer> getVecAllSvrMailRecord() {
		return vecAllSvrMailRecord;
	}

	public void setVecAllSvrMailRecord(java.util.List<java.lang.Integer> vecAllSvrMailRecord) {
		this.vecAllSvrMailRecord = vecAllSvrMailRecord;
	}

	public java.util.Map<java.lang.Integer, TBuyStatusDb> getMFirstBuyItemStatDb() {
		return mFirstBuyItemStatDb;
	}

	public void setMFirstBuyItemStatDb(java.util.Map<java.lang.Integer, TBuyStatusDb> mFirstBuyItemStatDb) {
		this.mFirstBuyItemStatDb = mFirstBuyItemStatDb;
	}

	public TExtData1() {
	}

	public TExtData1(TActiveCodeDb stActiveCodeDb, java.util.Map<java.lang.Integer, TBuyStatusDb> mBuyItemStatDb, java.util.List<java.lang.Integer> vecDaySelectionSaleItem, long lDaySelectionTM, short nSilverBoxFreeTimes, long lDrawSilverBoxTM, short nGoldBoxFreeTimes, long lDrawGoldBoxTM, short nPurpleBoxFreeTimes, long lDrawPurpleBoxTM, int iResumeVitNumByAD, long lLastResumeVitTM, TDBNewbieData stNewbieData, short nADTurnTableCnt, int iADPoolID, long lLastResumeADCntTM, java.util.List<TBuyLimitItemStatusDb> vecLimitSaleItem, java.util.Map<java.lang.Integer, java.lang.Integer> mOpenBoxHistory, java.util.List<java.lang.Integer> vecAllSvrMailRecord, java.util.Map<java.lang.Integer, TBuyStatusDb> mFirstBuyItemStatDb) {
		this.stActiveCodeDb = stActiveCodeDb;
		this.mBuyItemStatDb = mBuyItemStatDb;
		this.vecDaySelectionSaleItem = vecDaySelectionSaleItem;
		this.lDaySelectionTM = lDaySelectionTM;
		this.nSilverBoxFreeTimes = nSilverBoxFreeTimes;
		this.lDrawSilverBoxTM = lDrawSilverBoxTM;
		this.nGoldBoxFreeTimes = nGoldBoxFreeTimes;
		this.lDrawGoldBoxTM = lDrawGoldBoxTM;
		this.nPurpleBoxFreeTimes = nPurpleBoxFreeTimes;
		this.lDrawPurpleBoxTM = lDrawPurpleBoxTM;
		this.iResumeVitNumByAD = iResumeVitNumByAD;
		this.lLastResumeVitTM = lLastResumeVitTM;
		this.stNewbieData = stNewbieData;
		this.nADTurnTableCnt = nADTurnTableCnt;
		this.iADPoolID = iADPoolID;
		this.lLastResumeADCntTM = lLastResumeADCntTM;
		this.vecLimitSaleItem = vecLimitSaleItem;
		this.mOpenBoxHistory = mOpenBoxHistory;
		this.vecAllSvrMailRecord = vecAllSvrMailRecord;
		this.mFirstBuyItemStatDb = mFirstBuyItemStatDb;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(stActiveCodeDb);
		result = prime * result + TarsUtil.hashCode(mBuyItemStatDb);
		result = prime * result + TarsUtil.hashCode(vecDaySelectionSaleItem);
		result = prime * result + TarsUtil.hashCode(lDaySelectionTM);
		result = prime * result + TarsUtil.hashCode(nSilverBoxFreeTimes);
		result = prime * result + TarsUtil.hashCode(lDrawSilverBoxTM);
		result = prime * result + TarsUtil.hashCode(nGoldBoxFreeTimes);
		result = prime * result + TarsUtil.hashCode(lDrawGoldBoxTM);
		result = prime * result + TarsUtil.hashCode(nPurpleBoxFreeTimes);
		result = prime * result + TarsUtil.hashCode(lDrawPurpleBoxTM);
		result = prime * result + TarsUtil.hashCode(iResumeVitNumByAD);
		result = prime * result + TarsUtil.hashCode(lLastResumeVitTM);
		result = prime * result + TarsUtil.hashCode(stNewbieData);
		result = prime * result + TarsUtil.hashCode(nADTurnTableCnt);
		result = prime * result + TarsUtil.hashCode(iADPoolID);
		result = prime * result + TarsUtil.hashCode(lLastResumeADCntTM);
		result = prime * result + TarsUtil.hashCode(vecLimitSaleItem);
		result = prime * result + TarsUtil.hashCode(mOpenBoxHistory);
		result = prime * result + TarsUtil.hashCode(vecAllSvrMailRecord);
		result = prime * result + TarsUtil.hashCode(mFirstBuyItemStatDb);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof TExtData1)) {
			return false;
		}
		TExtData1 other = (TExtData1) obj;
		return (
			TarsUtil.equals(stActiveCodeDb, other.stActiveCodeDb) &&
			TarsUtil.equals(mBuyItemStatDb, other.mBuyItemStatDb) &&
			TarsUtil.equals(vecDaySelectionSaleItem, other.vecDaySelectionSaleItem) &&
			TarsUtil.equals(lDaySelectionTM, other.lDaySelectionTM) &&
			TarsUtil.equals(nSilverBoxFreeTimes, other.nSilverBoxFreeTimes) &&
			TarsUtil.equals(lDrawSilverBoxTM, other.lDrawSilverBoxTM) &&
			TarsUtil.equals(nGoldBoxFreeTimes, other.nGoldBoxFreeTimes) &&
			TarsUtil.equals(lDrawGoldBoxTM, other.lDrawGoldBoxTM) &&
			TarsUtil.equals(nPurpleBoxFreeTimes, other.nPurpleBoxFreeTimes) &&
			TarsUtil.equals(lDrawPurpleBoxTM, other.lDrawPurpleBoxTM) &&
			TarsUtil.equals(iResumeVitNumByAD, other.iResumeVitNumByAD) &&
			TarsUtil.equals(lLastResumeVitTM, other.lLastResumeVitTM) &&
			TarsUtil.equals(stNewbieData, other.stNewbieData) &&
			TarsUtil.equals(nADTurnTableCnt, other.nADTurnTableCnt) &&
			TarsUtil.equals(iADPoolID, other.iADPoolID) &&
			TarsUtil.equals(lLastResumeADCntTM, other.lLastResumeADCntTM) &&
			TarsUtil.equals(vecLimitSaleItem, other.vecLimitSaleItem) &&
			TarsUtil.equals(mOpenBoxHistory, other.mOpenBoxHistory) &&
			TarsUtil.equals(vecAllSvrMailRecord, other.vecAllSvrMailRecord) &&
			TarsUtil.equals(mFirstBuyItemStatDb, other.mFirstBuyItemStatDb) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		if (null != stActiveCodeDb) {
			_os.write(stActiveCodeDb, 0);
		}
		if (null != mBuyItemStatDb) {
			_os.write(mBuyItemStatDb, 1);
		}
		if (null != vecDaySelectionSaleItem) {
			_os.write(vecDaySelectionSaleItem, 2);
		}
		_os.write(lDaySelectionTM, 3);
		_os.write(nSilverBoxFreeTimes, 4);
		_os.write(lDrawSilverBoxTM, 5);
		_os.write(nGoldBoxFreeTimes, 6);
		_os.write(lDrawGoldBoxTM, 7);
		_os.write(nPurpleBoxFreeTimes, 8);
		_os.write(lDrawPurpleBoxTM, 9);
		_os.write(iResumeVitNumByAD, 10);
		_os.write(lLastResumeVitTM, 11);
		if (null != stNewbieData) {
			_os.write(stNewbieData, 12);
		}
		_os.write(nADTurnTableCnt, 13);
		_os.write(iADPoolID, 14);
		_os.write(lLastResumeADCntTM, 15);
		if (null != vecLimitSaleItem) {
			_os.write(vecLimitSaleItem, 16);
		}
		if (null != mOpenBoxHistory) {
			_os.write(mOpenBoxHistory, 17);
		}
		if (null != vecAllSvrMailRecord) {
			_os.write(vecAllSvrMailRecord, 18);
		}
		if (null != mFirstBuyItemStatDb) {
			_os.write(mFirstBuyItemStatDb, 19);
		}
	}

	static TActiveCodeDb cache_stActiveCodeDb;
	static { 
		cache_stActiveCodeDb = new TActiveCodeDb();
	}
	static java.util.Map<java.lang.Integer, TBuyStatusDb> cache_mBuyItemStatDb;
	static { 
		cache_mBuyItemStatDb = new java.util.HashMap<java.lang.Integer, TBuyStatusDb>();
		int var_9 = 0;
		TBuyStatusDb var_10 = new TBuyStatusDb();
		cache_mBuyItemStatDb.put(var_9 ,var_10);
	}
	static java.util.List<java.lang.Integer> cache_vecDaySelectionSaleItem;
	static { 
		cache_vecDaySelectionSaleItem = new java.util.ArrayList<java.lang.Integer>();
		int var_11 = 0;
		cache_vecDaySelectionSaleItem.add(var_11);
	}
	static TDBNewbieData cache_stNewbieData;
	static { 
		cache_stNewbieData = new TDBNewbieData();
	}
	static java.util.List<TBuyLimitItemStatusDb> cache_vecLimitSaleItem;
	static { 
		cache_vecLimitSaleItem = new java.util.ArrayList<TBuyLimitItemStatusDb>();
		TBuyLimitItemStatusDb var_12 = new TBuyLimitItemStatusDb();
		cache_vecLimitSaleItem.add(var_12);
	}
	static java.util.Map<java.lang.Integer, java.lang.Integer> cache_mOpenBoxHistory;
	static { 
		cache_mOpenBoxHistory = new java.util.HashMap<java.lang.Integer, java.lang.Integer>();
		int var_13 = 0;
		int var_14 = 0;
		cache_mOpenBoxHistory.put(var_13 ,var_14);
	}
	static java.util.List<java.lang.Integer> cache_vecAllSvrMailRecord;
	static { 
		cache_vecAllSvrMailRecord = new java.util.ArrayList<java.lang.Integer>();
		int var_15 = 0;
		cache_vecAllSvrMailRecord.add(var_15);
	}
	static java.util.Map<java.lang.Integer, TBuyStatusDb> cache_mFirstBuyItemStatDb;
	static { 
		cache_mFirstBuyItemStatDb = new java.util.HashMap<java.lang.Integer, TBuyStatusDb>();
		int var_16 = 0;
		TBuyStatusDb var_17 = new TBuyStatusDb();
		cache_mFirstBuyItemStatDb.put(var_16 ,var_17);
	}

	public void readFrom(TarsInputStream _is) {
		this.stActiveCodeDb = (TActiveCodeDb) _is.read(cache_stActiveCodeDb, 0, false);
		this.mBuyItemStatDb = (java.util.Map<java.lang.Integer, TBuyStatusDb>) _is.read(cache_mBuyItemStatDb, 1, false);
		this.vecDaySelectionSaleItem = (java.util.List<java.lang.Integer>) _is.read(cache_vecDaySelectionSaleItem, 2, false);
		this.lDaySelectionTM = _is.read(lDaySelectionTM, 3, false);
		this.nSilverBoxFreeTimes = _is.read(nSilverBoxFreeTimes, 4, false);
		this.lDrawSilverBoxTM = _is.read(lDrawSilverBoxTM, 5, false);
		this.nGoldBoxFreeTimes = _is.read(nGoldBoxFreeTimes, 6, false);
		this.lDrawGoldBoxTM = _is.read(lDrawGoldBoxTM, 7, false);
		this.nPurpleBoxFreeTimes = _is.read(nPurpleBoxFreeTimes, 8, false);
		this.lDrawPurpleBoxTM = _is.read(lDrawPurpleBoxTM, 9, false);
		this.iResumeVitNumByAD = _is.read(iResumeVitNumByAD, 10, false);
		this.lLastResumeVitTM = _is.read(lLastResumeVitTM, 11, false);
		this.stNewbieData = (TDBNewbieData) _is.read(cache_stNewbieData, 12, false);
		this.nADTurnTableCnt = _is.read(nADTurnTableCnt, 13, false);
		this.iADPoolID = _is.read(iADPoolID, 14, false);
		this.lLastResumeADCntTM = _is.read(lLastResumeADCntTM, 15, false);
		this.vecLimitSaleItem = (java.util.List<TBuyLimitItemStatusDb>) _is.read(cache_vecLimitSaleItem, 16, false);
		this.mOpenBoxHistory = (java.util.Map<java.lang.Integer, java.lang.Integer>) _is.read(cache_mOpenBoxHistory, 17, false);
		this.vecAllSvrMailRecord = (java.util.List<java.lang.Integer>) _is.read(cache_vecAllSvrMailRecord, 18, false);
		this.mFirstBuyItemStatDb = (java.util.Map<java.lang.Integer, TBuyStatusDb>) _is.read(cache_mFirstBuyItemStatDb, 19, false);
	}

}
