// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.yoooum.tars.account;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class TFormulationDBInfo {

	@TarsStructProperty(order = 0, isRequire = false)
	public java.util.List<TFormulationDb> vecformulationdb = null;

	public java.util.List<TFormulationDb> getVecformulationdb() {
		return vecformulationdb;
	}

	public void setVecformulationdb(java.util.List<TFormulationDb> vecformulationdb) {
		this.vecformulationdb = vecformulationdb;
	}

	public TFormulationDBInfo() {
	}

	public TFormulationDBInfo(java.util.List<TFormulationDb> vecformulationdb) {
		this.vecformulationdb = vecformulationdb;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(vecformulationdb);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof TFormulationDBInfo)) {
			return false;
		}
		TFormulationDBInfo other = (TFormulationDBInfo) obj;
		return (
			TarsUtil.equals(vecformulationdb, other.vecformulationdb) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		if (null != vecformulationdb) {
			_os.write(vecformulationdb, 0);
		}
	}

	static java.util.List<TFormulationDb> cache_vecformulationdb;
	static { 
		cache_vecformulationdb = new java.util.ArrayList<TFormulationDb>();
		TFormulationDb var_80 = new TFormulationDb();
		cache_vecformulationdb.add(var_80);
	}

	public void readFrom(TarsInputStream _is) {
		this.vecformulationdb = (java.util.List<TFormulationDb>) _is.read(cache_vecformulationdb, 0, false);
	}

}
