// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.yoooum.tars.account;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class TFormulationDb {

	@TarsStructProperty(order = 0, isRequire = true)
	public int nid = 0;
	@TarsStructProperty(order = 1, isRequire = false)
	public long uproficiency = 0L;

	public int getNid() {
		return nid;
	}

	public void setNid(int nid) {
		this.nid = nid;
	}

	public long getUproficiency() {
		return uproficiency;
	}

	public void setUproficiency(long uproficiency) {
		this.uproficiency = uproficiency;
	}

	public TFormulationDb() {
	}

	public TFormulationDb(int nid, long uproficiency) {
		this.nid = nid;
		this.uproficiency = uproficiency;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(nid);
		result = prime * result + TarsUtil.hashCode(uproficiency);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof TFormulationDb)) {
			return false;
		}
		TFormulationDb other = (TFormulationDb) obj;
		return (
			TarsUtil.equals(nid, other.nid) &&
			TarsUtil.equals(uproficiency, other.uproficiency) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(nid, 0);
		_os.write(uproficiency, 1);
	}


	public void readFrom(TarsInputStream _is) {
		this.nid = _is.read(nid, 0, true);
		this.uproficiency = _is.read(uproficiency, 1, false);
	}

}
