// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.yoooum.tars.account;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class TFriendRecruitInfo {

	@TarsStructProperty(order = 0, isRequire = false)
	public TAccountID stfriendid = null;
	@TarsStructProperty(order = 1, isRequire = false)
	public int iitemid = 0;
	@TarsStructProperty(order = 2, isRequire = false)
	public int iitemcnt = 0;
	@TarsStructProperty(order = 3, isRequire = false)
	public short ntimes = (short)0;
	@TarsStructProperty(order = 4, isRequire = false)
	public byte cstatus = (byte)0;

	public TAccountID getStfriendid() {
		return stfriendid;
	}

	public void setStfriendid(TAccountID stfriendid) {
		this.stfriendid = stfriendid;
	}

	public int getIitemid() {
		return iitemid;
	}

	public void setIitemid(int iitemid) {
		this.iitemid = iitemid;
	}

	public int getIitemcnt() {
		return iitemcnt;
	}

	public void setIitemcnt(int iitemcnt) {
		this.iitemcnt = iitemcnt;
	}

	public short getNtimes() {
		return ntimes;
	}

	public void setNtimes(short ntimes) {
		this.ntimes = ntimes;
	}

	public byte getCstatus() {
		return cstatus;
	}

	public void setCstatus(byte cstatus) {
		this.cstatus = cstatus;
	}

	public TFriendRecruitInfo() {
	}

	public TFriendRecruitInfo(TAccountID stfriendid, int iitemid, int iitemcnt, short ntimes, byte cstatus) {
		this.stfriendid = stfriendid;
		this.iitemid = iitemid;
		this.iitemcnt = iitemcnt;
		this.ntimes = ntimes;
		this.cstatus = cstatus;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(stfriendid);
		result = prime * result + TarsUtil.hashCode(iitemid);
		result = prime * result + TarsUtil.hashCode(iitemcnt);
		result = prime * result + TarsUtil.hashCode(ntimes);
		result = prime * result + TarsUtil.hashCode(cstatus);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof TFriendRecruitInfo)) {
			return false;
		}
		TFriendRecruitInfo other = (TFriendRecruitInfo) obj;
		return (
			TarsUtil.equals(stfriendid, other.stfriendid) &&
			TarsUtil.equals(iitemid, other.iitemid) &&
			TarsUtil.equals(iitemcnt, other.iitemcnt) &&
			TarsUtil.equals(ntimes, other.ntimes) &&
			TarsUtil.equals(cstatus, other.cstatus) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		if (null != stfriendid) {
			_os.write(stfriendid, 0);
		}
		_os.write(iitemid, 1);
		_os.write(iitemcnt, 2);
		_os.write(ntimes, 3);
		_os.write(cstatus, 4);
	}

	static TAccountID cache_stfriendid;
	static { 
		cache_stfriendid = new TAccountID();
	}

	public void readFrom(TarsInputStream _is) {
		this.stfriendid = (TAccountID) _is.read(cache_stfriendid, 0, false);
		this.iitemid = _is.read(iitemid, 1, false);
		this.iitemcnt = _is.read(iitemcnt, 2, false);
		this.ntimes = _is.read(ntimes, 3, false);
		this.cstatus = _is.read(cstatus, 4, false);
	}

}
