// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.yoooum.tars.account;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class TFriendListDB {

	@TarsStructProperty(order = 0, isRequire = false)
	public java.util.List<TAccountID> vFriendList = null;

	public java.util.List<TAccountID> getVFriendList() {
		return vFriendList;
	}

	public void setVFriendList(java.util.List<TAccountID> vFriendList) {
		this.vFriendList = vFriendList;
	}

	public TFriendListDB() {
	}

	public TFriendListDB(java.util.List<TAccountID> vFriendList) {
		this.vFriendList = vFriendList;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(vFriendList);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof TFriendListDB)) {
			return false;
		}
		TFriendListDB other = (TFriendListDB) obj;
		return (
			TarsUtil.equals(vFriendList, other.vFriendList) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		if (null != vFriendList) {
			_os.write(vFriendList, 0);
		}
	}

	static java.util.List<TAccountID> cache_vFriendList;
	static { 
		cache_vFriendList = new java.util.ArrayList<TAccountID>();
		TAccountID var_46 = new TAccountID();
		cache_vFriendList.add(var_46);
	}

	public void readFrom(TarsInputStream _is) {
		this.vFriendList = (java.util.List<TAccountID>) _is.read(cache_vFriendList, 0, false);
	}

}
