// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.yoooum.tars.account;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class TFriendDB {

	@TarsStructProperty(order = 0, isRequire = false)
	public TFriendListDB stFriendList = null;

	public TFriendListDB getStFriendList() {
		return stFriendList;
	}

	public void setStFriendList(TFriendListDB stFriendList) {
		this.stFriendList = stFriendList;
	}

	public TFriendDB() {
	}

	public TFriendDB(TFriendListDB stFriendList) {
		this.stFriendList = stFriendList;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(stFriendList);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof TFriendDB)) {
			return false;
		}
		TFriendDB other = (TFriendDB) obj;
		return (
			TarsUtil.equals(stFriendList, other.stFriendList) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		if (null != stFriendList) {
			_os.write(stFriendList, 0);
		}
	}

	static TFriendListDB cache_stFriendList;
	static { 
		cache_stFriendList = new TFriendListDB();
	}

	public void readFrom(TarsInputStream _is) {
		this.stFriendList = (TFriendListDB) _is.read(cache_stFriendList, 0, false);
	}

}
