// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.yoooum.tars.account;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class TFriendRecruitDB {

	@TarsStructProperty(order = 0, isRequire = false)
	public java.util.Map<java.lang.Short, java.util.List<TFriendRecruitInfo>> mrecruitfrilist = null;

	public java.util.Map<java.lang.Short, java.util.List<TFriendRecruitInfo>> getMrecruitfrilist() {
		return mrecruitfrilist;
	}

	public void setMrecruitfrilist(java.util.Map<java.lang.Short, java.util.List<TFriendRecruitInfo>> mrecruitfrilist) {
		this.mrecruitfrilist = mrecruitfrilist;
	}

	public TFriendRecruitDB() {
	}

	public TFriendRecruitDB(java.util.Map<java.lang.Short, java.util.List<TFriendRecruitInfo>> mrecruitfrilist) {
		this.mrecruitfrilist = mrecruitfrilist;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(mrecruitfrilist);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof TFriendRecruitDB)) {
			return false;
		}
		TFriendRecruitDB other = (TFriendRecruitDB) obj;
		return (
			TarsUtil.equals(mrecruitfrilist, other.mrecruitfrilist) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		if (null != mrecruitfrilist) {
			_os.write(mrecruitfrilist, 0);
		}
	}

	static java.util.Map<java.lang.Short, java.util.List<TFriendRecruitInfo>> cache_mrecruitfrilist;
	static { 
		cache_mrecruitfrilist = new java.util.HashMap<java.lang.Short, java.util.List<TFriendRecruitInfo>>();
		short var_114 = (short)0;
		java.util.List<TFriendRecruitInfo> var_115 = new java.util.ArrayList<TFriendRecruitInfo>();
		TFriendRecruitInfo var_116 = new TFriendRecruitInfo();
		var_115.add(var_116);
		cache_mrecruitfrilist.put(var_114 ,var_115);
	}

	public void readFrom(TarsInputStream _is) {
		this.mrecruitfrilist = (java.util.Map<java.lang.Short, java.util.List<TFriendRecruitInfo>>) _is.read(cache_mrecruitfrilist, 0, false);
	}

}
