// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.yoooum.tars.account;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class TGameCollectInfo {

	@TarsStructProperty(order = 1, isRequire = false)
	public java.util.List<TBackRoomGameInfo> vecbrgameinfo = null;

	public java.util.List<TBackRoomGameInfo> getVecbrgameinfo() {
		return vecbrgameinfo;
	}

	public void setVecbrgameinfo(java.util.List<TBackRoomGameInfo> vecbrgameinfo) {
		this.vecbrgameinfo = vecbrgameinfo;
	}

	public TGameCollectInfo() {
	}

	public TGameCollectInfo(java.util.List<TBackRoomGameInfo> vecbrgameinfo) {
		this.vecbrgameinfo = vecbrgameinfo;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(vecbrgameinfo);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof TGameCollectInfo)) {
			return false;
		}
		TGameCollectInfo other = (TGameCollectInfo) obj;
		return (
			TarsUtil.equals(vecbrgameinfo, other.vecbrgameinfo) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		if (null != vecbrgameinfo) {
			_os.write(vecbrgameinfo, 1);
		}
	}

	static java.util.List<TBackRoomGameInfo> cache_vecbrgameinfo;
	static { 
		cache_vecbrgameinfo = new java.util.ArrayList<TBackRoomGameInfo>();
		TBackRoomGameInfo var_110 = new TBackRoomGameInfo();
		cache_vecbrgameinfo.add(var_110);
	}

	public void readFrom(TarsInputStream _is) {
		this.vecbrgameinfo = (java.util.List<TBackRoomGameInfo>) _is.read(cache_vecbrgameinfo, 1, false);
	}

}
