// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.yoooum.tars.account;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class THeroInfo {

	@TarsStructProperty(order = 0, isRequire = false)
	public short nCurHeroID = (short)0;
	@TarsStructProperty(order = 1, isRequire = false)
	public java.util.List<THeroDB> vecHeroList = null;
	@TarsStructProperty(order = 2, isRequire = false)
	public short nPlayerState = (short)0;
	@TarsStructProperty(order = 3, isRequire = false)
	public short nReviveCnt = (short)0;
	@TarsStructProperty(order = 4, isRequire = false)
	public int iStageLevel = 0;
	@TarsStructProperty(order = 5, isRequire = false)
	public short nStageCnt = (short)0;
	@TarsStructProperty(order = 6, isRequire = false)
	public int iPassStageLevel = 0;
	@TarsStructProperty(order = 7, isRequire = false)
	public long lReviveTM = 0L;
	@TarsStructProperty(order = 8, isRequire = false)
	public short nDayReviveCnt = (short)0;
	@TarsStructProperty(order = 9, isRequire = false)
	public short nDayReviveTotalCnt = (short)0;

	public short getNCurHeroID() {
		return nCurHeroID;
	}

	public void setNCurHeroID(short nCurHeroID) {
		this.nCurHeroID = nCurHeroID;
	}

	public java.util.List<THeroDB> getVecHeroList() {
		return vecHeroList;
	}

	public void setVecHeroList(java.util.List<THeroDB> vecHeroList) {
		this.vecHeroList = vecHeroList;
	}

	public short getNPlayerState() {
		return nPlayerState;
	}

	public void setNPlayerState(short nPlayerState) {
		this.nPlayerState = nPlayerState;
	}

	public short getNReviveCnt() {
		return nReviveCnt;
	}

	public void setNReviveCnt(short nReviveCnt) {
		this.nReviveCnt = nReviveCnt;
	}

	public int getIStageLevel() {
		return iStageLevel;
	}

	public void setIStageLevel(int iStageLevel) {
		this.iStageLevel = iStageLevel;
	}

	public short getNStageCnt() {
		return nStageCnt;
	}

	public void setNStageCnt(short nStageCnt) {
		this.nStageCnt = nStageCnt;
	}

	public int getIPassStageLevel() {
		return iPassStageLevel;
	}

	public void setIPassStageLevel(int iPassStageLevel) {
		this.iPassStageLevel = iPassStageLevel;
	}

	public long getLReviveTM() {
		return lReviveTM;
	}

	public void setLReviveTM(long lReviveTM) {
		this.lReviveTM = lReviveTM;
	}

	public short getNDayReviveCnt() {
		return nDayReviveCnt;
	}

	public void setNDayReviveCnt(short nDayReviveCnt) {
		this.nDayReviveCnt = nDayReviveCnt;
	}

	public short getNDayReviveTotalCnt() {
		return nDayReviveTotalCnt;
	}

	public void setNDayReviveTotalCnt(short nDayReviveTotalCnt) {
		this.nDayReviveTotalCnt = nDayReviveTotalCnt;
	}

	public THeroInfo() {
	}

	public THeroInfo(short nCurHeroID, java.util.List<THeroDB> vecHeroList, short nPlayerState, short nReviveCnt, int iStageLevel, short nStageCnt, int iPassStageLevel, long lReviveTM, short nDayReviveCnt, short nDayReviveTotalCnt) {
		this.nCurHeroID = nCurHeroID;
		this.vecHeroList = vecHeroList;
		this.nPlayerState = nPlayerState;
		this.nReviveCnt = nReviveCnt;
		this.iStageLevel = iStageLevel;
		this.nStageCnt = nStageCnt;
		this.iPassStageLevel = iPassStageLevel;
		this.lReviveTM = lReviveTM;
		this.nDayReviveCnt = nDayReviveCnt;
		this.nDayReviveTotalCnt = nDayReviveTotalCnt;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(nCurHeroID);
		result = prime * result + TarsUtil.hashCode(vecHeroList);
		result = prime * result + TarsUtil.hashCode(nPlayerState);
		result = prime * result + TarsUtil.hashCode(nReviveCnt);
		result = prime * result + TarsUtil.hashCode(iStageLevel);
		result = prime * result + TarsUtil.hashCode(nStageCnt);
		result = prime * result + TarsUtil.hashCode(iPassStageLevel);
		result = prime * result + TarsUtil.hashCode(lReviveTM);
		result = prime * result + TarsUtil.hashCode(nDayReviveCnt);
		result = prime * result + TarsUtil.hashCode(nDayReviveTotalCnt);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof THeroInfo)) {
			return false;
		}
		THeroInfo other = (THeroInfo) obj;
		return (
			TarsUtil.equals(nCurHeroID, other.nCurHeroID) &&
			TarsUtil.equals(vecHeroList, other.vecHeroList) &&
			TarsUtil.equals(nPlayerState, other.nPlayerState) &&
			TarsUtil.equals(nReviveCnt, other.nReviveCnt) &&
			TarsUtil.equals(iStageLevel, other.iStageLevel) &&
			TarsUtil.equals(nStageCnt, other.nStageCnt) &&
			TarsUtil.equals(iPassStageLevel, other.iPassStageLevel) &&
			TarsUtil.equals(lReviveTM, other.lReviveTM) &&
			TarsUtil.equals(nDayReviveCnt, other.nDayReviveCnt) &&
			TarsUtil.equals(nDayReviveTotalCnt, other.nDayReviveTotalCnt) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(nCurHeroID, 0);
		if (null != vecHeroList) {
			_os.write(vecHeroList, 1);
		}
		_os.write(nPlayerState, 2);
		_os.write(nReviveCnt, 3);
		_os.write(iStageLevel, 4);
		_os.write(nStageCnt, 5);
		_os.write(iPassStageLevel, 6);
		_os.write(lReviveTM, 7);
		_os.write(nDayReviveCnt, 8);
		_os.write(nDayReviveTotalCnt, 9);
	}

	static java.util.List<THeroDB> cache_vecHeroList;
	static { 
		cache_vecHeroList = new java.util.ArrayList<THeroDB>();
		THeroDB var_34 = new THeroDB();
		cache_vecHeroList.add(var_34);
	}

	public void readFrom(TarsInputStream _is) {
		this.nCurHeroID = _is.read(nCurHeroID, 0, false);
		this.vecHeroList = (java.util.List<THeroDB>) _is.read(cache_vecHeroList, 1, false);
		this.nPlayerState = _is.read(nPlayerState, 2, false);
		this.nReviveCnt = _is.read(nReviveCnt, 3, false);
		this.iStageLevel = _is.read(iStageLevel, 4, false);
		this.nStageCnt = _is.read(nStageCnt, 5, false);
		this.iPassStageLevel = _is.read(iPassStageLevel, 6, false);
		this.lReviveTM = _is.read(lReviveTM, 7, false);
		this.nDayReviveCnt = _is.read(nDayReviveCnt, 8, false);
		this.nDayReviveTotalCnt = _is.read(nDayReviveTotalCnt, 9, false);
	}

}
