// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.yoooum.tars.account;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class THorseSlotCatData {

	@TarsStructProperty(order = 0, isRequire = false)
	public short shcatid = (short)0;
	@TarsStructProperty(order = 1, isRequire = false)
	public byte cpos = (byte)0;

	public short getShcatid() {
		return shcatid;
	}

	public void setShcatid(short shcatid) {
		this.shcatid = shcatid;
	}

	public byte getCpos() {
		return cpos;
	}

	public void setCpos(byte cpos) {
		this.cpos = cpos;
	}

	public THorseSlotCatData() {
	}

	public THorseSlotCatData(short shcatid, byte cpos) {
		this.shcatid = shcatid;
		this.cpos = cpos;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(shcatid);
		result = prime * result + TarsUtil.hashCode(cpos);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof THorseSlotCatData)) {
			return false;
		}
		THorseSlotCatData other = (THorseSlotCatData) obj;
		return (
			TarsUtil.equals(shcatid, other.shcatid) &&
			TarsUtil.equals(cpos, other.cpos) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(shcatid, 0);
		_os.write(cpos, 1);
	}


	public void readFrom(TarsInputStream _is) {
		this.shcatid = _is.read(shcatid, 0, false);
		this.cpos = _is.read(cpos, 1, false);
	}

}
