// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.yoooum.tars.account;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class THorseSlotDbData {

	@TarsStructProperty(order = 0, isRequire = false)
	public short shid = (short)0;
	@TarsStructProperty(order = 1, isRequire = false)
	public short shlvl = (short)0;
	@TarsStructProperty(order = 2, isRequire = false)
	public short shmapid = (short)0;
	@TarsStructProperty(order = 3, isRequire = false)
	public java.util.List<THorseSlotCatData> vpet = null;
	@TarsStructProperty(order = 4, isRequire = false)
	public java.util.List<THorseSlotProp> vpropinfo = null;
	@TarsStructProperty(order = 5, isRequire = false)
	public long ustarttime = 0L;
	@TarsStructProperty(order = 6, isRequire = false)
	public long uendtime = 0L;
	@TarsStructProperty(order = 7, isRequire = false)
	public java.util.List<TExplorEventInfo> veventinfo = null;

	public short getShid() {
		return shid;
	}

	public void setShid(short shid) {
		this.shid = shid;
	}

	public short getShlvl() {
		return shlvl;
	}

	public void setShlvl(short shlvl) {
		this.shlvl = shlvl;
	}

	public short getShmapid() {
		return shmapid;
	}

	public void setShmapid(short shmapid) {
		this.shmapid = shmapid;
	}

	public java.util.List<THorseSlotCatData> getVpet() {
		return vpet;
	}

	public void setVpet(java.util.List<THorseSlotCatData> vpet) {
		this.vpet = vpet;
	}

	public java.util.List<THorseSlotProp> getVpropinfo() {
		return vpropinfo;
	}

	public void setVpropinfo(java.util.List<THorseSlotProp> vpropinfo) {
		this.vpropinfo = vpropinfo;
	}

	public long getUstarttime() {
		return ustarttime;
	}

	public void setUstarttime(long ustarttime) {
		this.ustarttime = ustarttime;
	}

	public long getUendtime() {
		return uendtime;
	}

	public void setUendtime(long uendtime) {
		this.uendtime = uendtime;
	}

	public java.util.List<TExplorEventInfo> getVeventinfo() {
		return veventinfo;
	}

	public void setVeventinfo(java.util.List<TExplorEventInfo> veventinfo) {
		this.veventinfo = veventinfo;
	}

	public THorseSlotDbData() {
	}

	public THorseSlotDbData(short shid, short shlvl, short shmapid, java.util.List<THorseSlotCatData> vpet, java.util.List<THorseSlotProp> vpropinfo, long ustarttime, long uendtime, java.util.List<TExplorEventInfo> veventinfo) {
		this.shid = shid;
		this.shlvl = shlvl;
		this.shmapid = shmapid;
		this.vpet = vpet;
		this.vpropinfo = vpropinfo;
		this.ustarttime = ustarttime;
		this.uendtime = uendtime;
		this.veventinfo = veventinfo;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(shid);
		result = prime * result + TarsUtil.hashCode(shlvl);
		result = prime * result + TarsUtil.hashCode(shmapid);
		result = prime * result + TarsUtil.hashCode(vpet);
		result = prime * result + TarsUtil.hashCode(vpropinfo);
		result = prime * result + TarsUtil.hashCode(ustarttime);
		result = prime * result + TarsUtil.hashCode(uendtime);
		result = prime * result + TarsUtil.hashCode(veventinfo);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof THorseSlotDbData)) {
			return false;
		}
		THorseSlotDbData other = (THorseSlotDbData) obj;
		return (
			TarsUtil.equals(shid, other.shid) &&
			TarsUtil.equals(shlvl, other.shlvl) &&
			TarsUtil.equals(shmapid, other.shmapid) &&
			TarsUtil.equals(vpet, other.vpet) &&
			TarsUtil.equals(vpropinfo, other.vpropinfo) &&
			TarsUtil.equals(ustarttime, other.ustarttime) &&
			TarsUtil.equals(uendtime, other.uendtime) &&
			TarsUtil.equals(veventinfo, other.veventinfo) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(shid, 0);
		_os.write(shlvl, 1);
		_os.write(shmapid, 2);
		if (null != vpet) {
			_os.write(vpet, 3);
		}
		if (null != vpropinfo) {
			_os.write(vpropinfo, 4);
		}
		_os.write(ustarttime, 5);
		_os.write(uendtime, 6);
		if (null != veventinfo) {
			_os.write(veventinfo, 7);
		}
	}

	static java.util.List<THorseSlotCatData> cache_vpet;
	static { 
		cache_vpet = new java.util.ArrayList<THorseSlotCatData>();
		THorseSlotCatData var_92 = new THorseSlotCatData();
		cache_vpet.add(var_92);
	}
	static java.util.List<THorseSlotProp> cache_vpropinfo;
	static { 
		cache_vpropinfo = new java.util.ArrayList<THorseSlotProp>();
		THorseSlotProp var_93 = new THorseSlotProp();
		cache_vpropinfo.add(var_93);
	}
	static java.util.List<TExplorEventInfo> cache_veventinfo;
	static { 
		cache_veventinfo = new java.util.ArrayList<TExplorEventInfo>();
		TExplorEventInfo var_94 = new TExplorEventInfo();
		cache_veventinfo.add(var_94);
	}

	public void readFrom(TarsInputStream _is) {
		this.shid = _is.read(shid, 0, false);
		this.shlvl = _is.read(shlvl, 1, false);
		this.shmapid = _is.read(shmapid, 2, false);
		this.vpet = (java.util.List<THorseSlotCatData>) _is.read(cache_vpet, 3, false);
		this.vpropinfo = (java.util.List<THorseSlotProp>) _is.read(cache_vpropinfo, 4, false);
		this.ustarttime = _is.read(ustarttime, 5, false);
		this.uendtime = _is.read(uendtime, 6, false);
		this.veventinfo = (java.util.List<TExplorEventInfo>) _is.read(cache_veventinfo, 7, false);
	}

}
