// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.yoooum.tars.account;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class THorseSlotProp {

	@TarsStructProperty(order = 0, isRequire = false)
	public TPropDbInfo stpropinfo = null;
	@TarsStructProperty(order = 1, isRequire = false)
	public byte cpos = (byte)0;

	public TPropDbInfo getStpropinfo() {
		return stpropinfo;
	}

	public void setStpropinfo(TPropDbInfo stpropinfo) {
		this.stpropinfo = stpropinfo;
	}

	public byte getCpos() {
		return cpos;
	}

	public void setCpos(byte cpos) {
		this.cpos = cpos;
	}

	public THorseSlotProp() {
	}

	public THorseSlotProp(TPropDbInfo stpropinfo, byte cpos) {
		this.stpropinfo = stpropinfo;
		this.cpos = cpos;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(stpropinfo);
		result = prime * result + TarsUtil.hashCode(cpos);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof THorseSlotProp)) {
			return false;
		}
		THorseSlotProp other = (THorseSlotProp) obj;
		return (
			TarsUtil.equals(stpropinfo, other.stpropinfo) &&
			TarsUtil.equals(cpos, other.cpos) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		if (null != stpropinfo) {
			_os.write(stpropinfo, 0);
		}
		_os.write(cpos, 1);
	}

	static TPropDbInfo cache_stpropinfo;
	static { 
		cache_stpropinfo = new TPropDbInfo();
	}

	public void readFrom(TarsInputStream _is) {
		this.stpropinfo = (TPropDbInfo) _is.read(cache_stpropinfo, 0, false);
		this.cpos = _is.read(cpos, 1, false);
	}

}
