// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.yoooum.tars.account;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class TMainDialogueData {

	@TarsStructProperty(order = 0, isRequire = false)
	public short iid = (short)0;

	public short getIid() {
		return iid;
	}

	public void setIid(short iid) {
		this.iid = iid;
	}

	public TMainDialogueData() {
	}

	public TMainDialogueData(short iid) {
		this.iid = iid;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(iid);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof TMainDialogueData)) {
			return false;
		}
		TMainDialogueData other = (TMainDialogueData) obj;
		return (
			TarsUtil.equals(iid, other.iid) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(iid, 0);
	}


	public void readFrom(TarsInputStream _is) {
		this.iid = _is.read(iid, 0, false);
	}

}
