// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.yoooum.tars.account;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class TMainSectionData {

	@TarsStructProperty(order = 0, isRequire = false)
	public int iid = 0;
	@TarsStructProperty(order = 2, isRequire = false)
	public java.util.List<TMainDialogueData> vecdialoguedata = null;
	@TarsStructProperty(order = 3, isRequire = false)
	public int ibreakoffdialogueid = 0;
	@TarsStructProperty(order = 4, isRequire = false)
	public java.util.List<TCatPropDialogueData> veccatpropdiadata = null;
	@TarsStructProperty(order = 5, isRequire = false)
	public byte cfinish = (byte)0;

	public int getIid() {
		return iid;
	}

	public void setIid(int iid) {
		this.iid = iid;
	}

	public java.util.List<TMainDialogueData> getVecdialoguedata() {
		return vecdialoguedata;
	}

	public void setVecdialoguedata(java.util.List<TMainDialogueData> vecdialoguedata) {
		this.vecdialoguedata = vecdialoguedata;
	}

	public int getIbreakoffdialogueid() {
		return ibreakoffdialogueid;
	}

	public void setIbreakoffdialogueid(int ibreakoffdialogueid) {
		this.ibreakoffdialogueid = ibreakoffdialogueid;
	}

	public java.util.List<TCatPropDialogueData> getVeccatpropdiadata() {
		return veccatpropdiadata;
	}

	public void setVeccatpropdiadata(java.util.List<TCatPropDialogueData> veccatpropdiadata) {
		this.veccatpropdiadata = veccatpropdiadata;
	}

	public byte getCfinish() {
		return cfinish;
	}

	public void setCfinish(byte cfinish) {
		this.cfinish = cfinish;
	}

	public TMainSectionData() {
	}

	public TMainSectionData(int iid, java.util.List<TMainDialogueData> vecdialoguedata, int ibreakoffdialogueid, java.util.List<TCatPropDialogueData> veccatpropdiadata, byte cfinish) {
		this.iid = iid;
		this.vecdialoguedata = vecdialoguedata;
		this.ibreakoffdialogueid = ibreakoffdialogueid;
		this.veccatpropdiadata = veccatpropdiadata;
		this.cfinish = cfinish;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(iid);
		result = prime * result + TarsUtil.hashCode(vecdialoguedata);
		result = prime * result + TarsUtil.hashCode(ibreakoffdialogueid);
		result = prime * result + TarsUtil.hashCode(veccatpropdiadata);
		result = prime * result + TarsUtil.hashCode(cfinish);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof TMainSectionData)) {
			return false;
		}
		TMainSectionData other = (TMainSectionData) obj;
		return (
			TarsUtil.equals(iid, other.iid) &&
			TarsUtil.equals(vecdialoguedata, other.vecdialoguedata) &&
			TarsUtil.equals(ibreakoffdialogueid, other.ibreakoffdialogueid) &&
			TarsUtil.equals(veccatpropdiadata, other.veccatpropdiadata) &&
			TarsUtil.equals(cfinish, other.cfinish) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(iid, 0);
		if (null != vecdialoguedata) {
			_os.write(vecdialoguedata, 2);
		}
		_os.write(ibreakoffdialogueid, 3);
		if (null != veccatpropdiadata) {
			_os.write(veccatpropdiadata, 4);
		}
		_os.write(cfinish, 5);
	}

	static java.util.List<TMainDialogueData> cache_vecdialoguedata;
	static { 
		cache_vecdialoguedata = new java.util.ArrayList<TMainDialogueData>();
		TMainDialogueData var_8 = new TMainDialogueData();
		cache_vecdialoguedata.add(var_8);
	}
	static java.util.List<TCatPropDialogueData> cache_veccatpropdiadata;
	static { 
		cache_veccatpropdiadata = new java.util.ArrayList<TCatPropDialogueData>();
		TCatPropDialogueData var_9 = new TCatPropDialogueData();
		cache_veccatpropdiadata.add(var_9);
	}

	public void readFrom(TarsInputStream _is) {
		this.iid = _is.read(iid, 0, false);
		this.vecdialoguedata = (java.util.List<TMainDialogueData>) _is.read(cache_vecdialoguedata, 2, false);
		this.ibreakoffdialogueid = _is.read(ibreakoffdialogueid, 3, false);
		this.veccatpropdiadata = (java.util.List<TCatPropDialogueData>) _is.read(cache_veccatpropdiadata, 4, false);
		this.cfinish = _is.read(cfinish, 5, false);
	}

}
