// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.yoooum.tars.account;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class TMobilePhoneInfo {

	@TarsStructProperty(order = 0, isRequire = false)
	public String sOSType = "";
	@TarsStructProperty(order = 1, isRequire = false)
	public String sOSVersion = "";
	@TarsStructProperty(order = 2, isRequire = false)
	public String sPhoneMode = "";
	@TarsStructProperty(order = 3, isRequire = false)
	public String sTeleComOper = "";
	@TarsStructProperty(order = 4, isRequire = false)
	public int iNetworkType = 0;
	@TarsStructProperty(order = 5, isRequire = false)
	public int iScreenHight = 0;
	@TarsStructProperty(order = 6, isRequire = false)
	public int iScreenWidth = 0;
	@TarsStructProperty(order = 7, isRequire = false)
	public int iScreenDensity = 0;
	@TarsStructProperty(order = 8, isRequire = false)
	public String strCpuHardware = "";
	@TarsStructProperty(order = 9, isRequire = false)
	public int iMemory = 0;
	@TarsStructProperty(order = 10, isRequire = false)
	public String sMacAddr = "";
	@TarsStructProperty(order = 11, isRequire = false)
	public String sIMEI = "";
	@TarsStructProperty(order = 12, isRequire = false)
	public int iDeviceQuality = 0;

	public String getSOSType() {
		return sOSType;
	}

	public void setSOSType(String sOSType) {
		this.sOSType = sOSType;
	}

	public String getSOSVersion() {
		return sOSVersion;
	}

	public void setSOSVersion(String sOSVersion) {
		this.sOSVersion = sOSVersion;
	}

	public String getSPhoneMode() {
		return sPhoneMode;
	}

	public void setSPhoneMode(String sPhoneMode) {
		this.sPhoneMode = sPhoneMode;
	}

	public String getSTeleComOper() {
		return sTeleComOper;
	}

	public void setSTeleComOper(String sTeleComOper) {
		this.sTeleComOper = sTeleComOper;
	}

	public int getINetworkType() {
		return iNetworkType;
	}

	public void setINetworkType(int iNetworkType) {
		this.iNetworkType = iNetworkType;
	}

	public int getIScreenHight() {
		return iScreenHight;
	}

	public void setIScreenHight(int iScreenHight) {
		this.iScreenHight = iScreenHight;
	}

	public int getIScreenWidth() {
		return iScreenWidth;
	}

	public void setIScreenWidth(int iScreenWidth) {
		this.iScreenWidth = iScreenWidth;
	}

	public int getIScreenDensity() {
		return iScreenDensity;
	}

	public void setIScreenDensity(int iScreenDensity) {
		this.iScreenDensity = iScreenDensity;
	}

	public String getStrCpuHardware() {
		return strCpuHardware;
	}

	public void setStrCpuHardware(String strCpuHardware) {
		this.strCpuHardware = strCpuHardware;
	}

	public int getIMemory() {
		return iMemory;
	}

	public void setIMemory(int iMemory) {
		this.iMemory = iMemory;
	}

	public String getSMacAddr() {
		return sMacAddr;
	}

	public void setSMacAddr(String sMacAddr) {
		this.sMacAddr = sMacAddr;
	}

	public String getSIMEI() {
		return sIMEI;
	}

	public void setSIMEI(String sIMEI) {
		this.sIMEI = sIMEI;
	}

	public int getIDeviceQuality() {
		return iDeviceQuality;
	}

	public void setIDeviceQuality(int iDeviceQuality) {
		this.iDeviceQuality = iDeviceQuality;
	}

	public TMobilePhoneInfo() {
	}

	public TMobilePhoneInfo(String sOSType, String sOSVersion, String sPhoneMode, String sTeleComOper, int iNetworkType, int iScreenHight, int iScreenWidth, int iScreenDensity, String strCpuHardware, int iMemory, String sMacAddr, String sIMEI, int iDeviceQuality) {
		this.sOSType = sOSType;
		this.sOSVersion = sOSVersion;
		this.sPhoneMode = sPhoneMode;
		this.sTeleComOper = sTeleComOper;
		this.iNetworkType = iNetworkType;
		this.iScreenHight = iScreenHight;
		this.iScreenWidth = iScreenWidth;
		this.iScreenDensity = iScreenDensity;
		this.strCpuHardware = strCpuHardware;
		this.iMemory = iMemory;
		this.sMacAddr = sMacAddr;
		this.sIMEI = sIMEI;
		this.iDeviceQuality = iDeviceQuality;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(sOSType);
		result = prime * result + TarsUtil.hashCode(sOSVersion);
		result = prime * result + TarsUtil.hashCode(sPhoneMode);
		result = prime * result + TarsUtil.hashCode(sTeleComOper);
		result = prime * result + TarsUtil.hashCode(iNetworkType);
		result = prime * result + TarsUtil.hashCode(iScreenHight);
		result = prime * result + TarsUtil.hashCode(iScreenWidth);
		result = prime * result + TarsUtil.hashCode(iScreenDensity);
		result = prime * result + TarsUtil.hashCode(strCpuHardware);
		result = prime * result + TarsUtil.hashCode(iMemory);
		result = prime * result + TarsUtil.hashCode(sMacAddr);
		result = prime * result + TarsUtil.hashCode(sIMEI);
		result = prime * result + TarsUtil.hashCode(iDeviceQuality);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof TMobilePhoneInfo)) {
			return false;
		}
		TMobilePhoneInfo other = (TMobilePhoneInfo) obj;
		return (
			TarsUtil.equals(sOSType, other.sOSType) &&
			TarsUtil.equals(sOSVersion, other.sOSVersion) &&
			TarsUtil.equals(sPhoneMode, other.sPhoneMode) &&
			TarsUtil.equals(sTeleComOper, other.sTeleComOper) &&
			TarsUtil.equals(iNetworkType, other.iNetworkType) &&
			TarsUtil.equals(iScreenHight, other.iScreenHight) &&
			TarsUtil.equals(iScreenWidth, other.iScreenWidth) &&
			TarsUtil.equals(iScreenDensity, other.iScreenDensity) &&
			TarsUtil.equals(strCpuHardware, other.strCpuHardware) &&
			TarsUtil.equals(iMemory, other.iMemory) &&
			TarsUtil.equals(sMacAddr, other.sMacAddr) &&
			TarsUtil.equals(sIMEI, other.sIMEI) &&
			TarsUtil.equals(iDeviceQuality, other.iDeviceQuality) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		if (null != sOSType) {
			_os.write(sOSType, 0);
		}
		if (null != sOSVersion) {
			_os.write(sOSVersion, 1);
		}
		if (null != sPhoneMode) {
			_os.write(sPhoneMode, 2);
		}
		if (null != sTeleComOper) {
			_os.write(sTeleComOper, 3);
		}
		_os.write(iNetworkType, 4);
		_os.write(iScreenHight, 5);
		_os.write(iScreenWidth, 6);
		_os.write(iScreenDensity, 7);
		if (null != strCpuHardware) {
			_os.write(strCpuHardware, 8);
		}
		_os.write(iMemory, 9);
		if (null != sMacAddr) {
			_os.write(sMacAddr, 10);
		}
		if (null != sIMEI) {
			_os.write(sIMEI, 11);
		}
		_os.write(iDeviceQuality, 12);
	}


	public void readFrom(TarsInputStream _is) {
		this.sOSType = _is.readString(0, false);
		this.sOSVersion = _is.readString(1, false);
		this.sPhoneMode = _is.readString(2, false);
		this.sTeleComOper = _is.readString(3, false);
		this.iNetworkType = _is.read(iNetworkType, 4, false);
		this.iScreenHight = _is.read(iScreenHight, 5, false);
		this.iScreenWidth = _is.read(iScreenWidth, 6, false);
		this.iScreenDensity = _is.read(iScreenDensity, 7, false);
		this.strCpuHardware = _is.readString(8, false);
		this.iMemory = _is.read(iMemory, 9, false);
		this.sMacAddr = _is.readString(10, false);
		this.sIMEI = _is.readString(11, false);
		this.iDeviceQuality = _is.read(iDeviceQuality, 12, false);
	}

}
