// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.yoooum.tars.account;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class TNaturalItemInfo {

	@TarsStructProperty(order = 0, isRequire = false)
	public int iID = 0;
	@TarsStructProperty(order = 1, isRequire = false)
	public short nLvl = 0;

	public int getIID() {
		return iID;
	}

	public void setIID(int iID) {
		this.iID = iID;
	}

	public short getNLvl() {
		return nLvl;
	}

	public void setNLvl(short nLvl) {
		this.nLvl = nLvl;
	}

	public TNaturalItemInfo() {
	}

	public TNaturalItemInfo(int iID, short nLvl) {
		this.iID = iID;
		this.nLvl = nLvl;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(iID);
		result = prime * result + TarsUtil.hashCode(nLvl);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof TNaturalItemInfo)) {
			return false;
		}
		TNaturalItemInfo other = (TNaturalItemInfo) obj;
		return (
			TarsUtil.equals(iID, other.iID) &&
			TarsUtil.equals(nLvl, other.nLvl) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(iID, 0);
		_os.write(nLvl, 1);
	}


	public void readFrom(TarsInputStream _is) {
		this.iID = _is.read(iID, 0, false);
		this.nLvl = _is.read(nLvl, 1, false);
	}

}
