// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.yoooum.tars.account;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class TNpcDBInfo {

	@TarsStructProperty(order = 0, isRequire = false)
	public long ufreshtime = 0L;
	@TarsStructProperty(order = 1, isRequire = false)
	public java.util.List<TSpecailNpc> vecspecailnpc = null;
	@TarsStructProperty(order = 2, isRequire = false)
	public java.util.List<TShopNpc> veccommshopnpc = null;
	@TarsStructProperty(order = 3, isRequire = false)
	public java.util.List<TShopNpc> vecrareshopnpc = null;
	@TarsStructProperty(order = 4, isRequire = false)
	public java.util.List<TFunctionNpc> vecfunctionnpc = null;

	public long getUfreshtime() {
		return ufreshtime;
	}

	public void setUfreshtime(long ufreshtime) {
		this.ufreshtime = ufreshtime;
	}

	public java.util.List<TSpecailNpc> getVecspecailnpc() {
		return vecspecailnpc;
	}

	public void setVecspecailnpc(java.util.List<TSpecailNpc> vecspecailnpc) {
		this.vecspecailnpc = vecspecailnpc;
	}

	public java.util.List<TShopNpc> getVeccommshopnpc() {
		return veccommshopnpc;
	}

	public void setVeccommshopnpc(java.util.List<TShopNpc> veccommshopnpc) {
		this.veccommshopnpc = veccommshopnpc;
	}

	public java.util.List<TShopNpc> getVecrareshopnpc() {
		return vecrareshopnpc;
	}

	public void setVecrareshopnpc(java.util.List<TShopNpc> vecrareshopnpc) {
		this.vecrareshopnpc = vecrareshopnpc;
	}

	public java.util.List<TFunctionNpc> getVecfunctionnpc() {
		return vecfunctionnpc;
	}

	public void setVecfunctionnpc(java.util.List<TFunctionNpc> vecfunctionnpc) {
		this.vecfunctionnpc = vecfunctionnpc;
	}

	public TNpcDBInfo() {
	}

	public TNpcDBInfo(long ufreshtime, java.util.List<TSpecailNpc> vecspecailnpc, java.util.List<TShopNpc> veccommshopnpc, java.util.List<TShopNpc> vecrareshopnpc, java.util.List<TFunctionNpc> vecfunctionnpc) {
		this.ufreshtime = ufreshtime;
		this.vecspecailnpc = vecspecailnpc;
		this.veccommshopnpc = veccommshopnpc;
		this.vecrareshopnpc = vecrareshopnpc;
		this.vecfunctionnpc = vecfunctionnpc;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(ufreshtime);
		result = prime * result + TarsUtil.hashCode(vecspecailnpc);
		result = prime * result + TarsUtil.hashCode(veccommshopnpc);
		result = prime * result + TarsUtil.hashCode(vecrareshopnpc);
		result = prime * result + TarsUtil.hashCode(vecfunctionnpc);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof TNpcDBInfo)) {
			return false;
		}
		TNpcDBInfo other = (TNpcDBInfo) obj;
		return (
			TarsUtil.equals(ufreshtime, other.ufreshtime) &&
			TarsUtil.equals(vecspecailnpc, other.vecspecailnpc) &&
			TarsUtil.equals(veccommshopnpc, other.veccommshopnpc) &&
			TarsUtil.equals(vecrareshopnpc, other.vecrareshopnpc) &&
			TarsUtil.equals(vecfunctionnpc, other.vecfunctionnpc) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(ufreshtime, 0);
		if (null != vecspecailnpc) {
			_os.write(vecspecailnpc, 1);
		}
		if (null != veccommshopnpc) {
			_os.write(veccommshopnpc, 2);
		}
		if (null != vecrareshopnpc) {
			_os.write(vecrareshopnpc, 3);
		}
		if (null != vecfunctionnpc) {
			_os.write(vecfunctionnpc, 4);
		}
	}

	static java.util.List<TSpecailNpc> cache_vecspecailnpc;
	static { 
		cache_vecspecailnpc = new java.util.ArrayList<TSpecailNpc>();
		TSpecailNpc var_106 = new TSpecailNpc();
		cache_vecspecailnpc.add(var_106);
	}
	static java.util.List<TShopNpc> cache_veccommshopnpc;
	static { 
		cache_veccommshopnpc = new java.util.ArrayList<TShopNpc>();
		TShopNpc var_107 = new TShopNpc();
		cache_veccommshopnpc.add(var_107);
	}
	static java.util.List<TShopNpc> cache_vecrareshopnpc;
	static { 
		cache_vecrareshopnpc = new java.util.ArrayList<TShopNpc>();
		TShopNpc var_108 = new TShopNpc();
		cache_vecrareshopnpc.add(var_108);
	}
	static java.util.List<TFunctionNpc> cache_vecfunctionnpc;
	static { 
		cache_vecfunctionnpc = new java.util.ArrayList<TFunctionNpc>();
		TFunctionNpc var_109 = new TFunctionNpc();
		cache_vecfunctionnpc.add(var_109);
	}

	public void readFrom(TarsInputStream _is) {
		this.ufreshtime = _is.read(ufreshtime, 0, false);
		this.vecspecailnpc = (java.util.List<TSpecailNpc>) _is.read(cache_vecspecailnpc, 1, false);
		this.veccommshopnpc = (java.util.List<TShopNpc>) _is.read(cache_veccommshopnpc, 2, false);
		this.vecrareshopnpc = (java.util.List<TShopNpc>) _is.read(cache_vecrareshopnpc, 3, false);
		this.vecfunctionnpc = (java.util.List<TFunctionNpc>) _is.read(cache_vecfunctionnpc, 4, false);
	}

}
