// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.yoooum.tars.account;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class TPetDb {

	@TarsStructProperty(order = 0, isRequire = true)
	public short npetid = (short)0;
	@TarsStructProperty(order = 1, isRequire = true)
	public short nlvl = (short)0;
	@TarsStructProperty(order = 2, isRequire = true)
	public int icookabil = 0;
	@TarsStructProperty(order = 3, isRequire = true)
	public int idressabil = 0;
	@TarsStructProperty(order = 4, isRequire = true)
	public int igardenabil = 0;
	@TarsStructProperty(order = 5, isRequire = true)
	public int ipharmacologyabil = 0;
	@TarsStructProperty(order = 6, isRequire = true)
	public int istar = 0;
	@TarsStructProperty(order = 7, isRequire = false)
	public int estatus = 0;
	@TarsStructProperty(order = 8, isRequire = false)
	public java.util.List<TPetSkillDb> vskill = null;
	@TarsStructProperty(order = 9, isRequire = false)
	public java.util.List<TSkillBuffer> vskillbuffer = null;
	@TarsStructProperty(order = 10, isRequire = false)
	public String sname = "";
	@TarsStructProperty(order = 11, isRequire = false)
	public int iexp = 0;

	public short getNpetid() {
		return npetid;
	}

	public void setNpetid(short npetid) {
		this.npetid = npetid;
	}

	public short getNlvl() {
		return nlvl;
	}

	public void setNlvl(short nlvl) {
		this.nlvl = nlvl;
	}

	public int getIcookabil() {
		return icookabil;
	}

	public void setIcookabil(int icookabil) {
		this.icookabil = icookabil;
	}

	public int getIdressabil() {
		return idressabil;
	}

	public void setIdressabil(int idressabil) {
		this.idressabil = idressabil;
	}

	public int getIgardenabil() {
		return igardenabil;
	}

	public void setIgardenabil(int igardenabil) {
		this.igardenabil = igardenabil;
	}

	public int getIpharmacologyabil() {
		return ipharmacologyabil;
	}

	public void setIpharmacologyabil(int ipharmacologyabil) {
		this.ipharmacologyabil = ipharmacologyabil;
	}

	public int getIstar() {
		return istar;
	}

	public void setIstar(int istar) {
		this.istar = istar;
	}

	public int getEstatus() {
		return estatus;
	}

	public void setEstatus(int estatus) {
		this.estatus = estatus;
	}

	public java.util.List<TPetSkillDb> getVskill() {
		return vskill;
	}

	public void setVskill(java.util.List<TPetSkillDb> vskill) {
		this.vskill = vskill;
	}

	public java.util.List<TSkillBuffer> getVskillbuffer() {
		return vskillbuffer;
	}

	public void setVskillbuffer(java.util.List<TSkillBuffer> vskillbuffer) {
		this.vskillbuffer = vskillbuffer;
	}

	public String getSname() {
		return sname;
	}

	public void setSname(String sname) {
		this.sname = sname;
	}

	public int getIexp() {
		return iexp;
	}

	public void setIexp(int iexp) {
		this.iexp = iexp;
	}

	public TPetDb() {
	}

	public TPetDb(short npetid, short nlvl, int icookabil, int idressabil, int igardenabil, int ipharmacologyabil, int istar, int estatus, java.util.List<TPetSkillDb> vskill, java.util.List<TSkillBuffer> vskillbuffer, String sname, int iexp) {
		this.npetid = npetid;
		this.nlvl = nlvl;
		this.icookabil = icookabil;
		this.idressabil = idressabil;
		this.igardenabil = igardenabil;
		this.ipharmacologyabil = ipharmacologyabil;
		this.istar = istar;
		this.estatus = estatus;
		this.vskill = vskill;
		this.vskillbuffer = vskillbuffer;
		this.sname = sname;
		this.iexp = iexp;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(npetid);
		result = prime * result + TarsUtil.hashCode(nlvl);
		result = prime * result + TarsUtil.hashCode(icookabil);
		result = prime * result + TarsUtil.hashCode(idressabil);
		result = prime * result + TarsUtil.hashCode(igardenabil);
		result = prime * result + TarsUtil.hashCode(ipharmacologyabil);
		result = prime * result + TarsUtil.hashCode(istar);
		result = prime * result + TarsUtil.hashCode(estatus);
		result = prime * result + TarsUtil.hashCode(vskill);
		result = prime * result + TarsUtil.hashCode(vskillbuffer);
		result = prime * result + TarsUtil.hashCode(sname);
		result = prime * result + TarsUtil.hashCode(iexp);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof TPetDb)) {
			return false;
		}
		TPetDb other = (TPetDb) obj;
		return (
			TarsUtil.equals(npetid, other.npetid) &&
			TarsUtil.equals(nlvl, other.nlvl) &&
			TarsUtil.equals(icookabil, other.icookabil) &&
			TarsUtil.equals(idressabil, other.idressabil) &&
			TarsUtil.equals(igardenabil, other.igardenabil) &&
			TarsUtil.equals(ipharmacologyabil, other.ipharmacologyabil) &&
			TarsUtil.equals(istar, other.istar) &&
			TarsUtil.equals(estatus, other.estatus) &&
			TarsUtil.equals(vskill, other.vskill) &&
			TarsUtil.equals(vskillbuffer, other.vskillbuffer) &&
			TarsUtil.equals(sname, other.sname) &&
			TarsUtil.equals(iexp, other.iexp) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(npetid, 0);
		_os.write(nlvl, 1);
		_os.write(icookabil, 2);
		_os.write(idressabil, 3);
		_os.write(igardenabil, 4);
		_os.write(ipharmacologyabil, 5);
		_os.write(istar, 6);
		_os.write(estatus, 7);
		if (null != vskill) {
			_os.write(vskill, 8);
		}
		if (null != vskillbuffer) {
			_os.write(vskillbuffer, 9);
		}
		if (null != sname) {
			_os.write(sname, 10);
		}
		_os.write(iexp, 11);
	}

	static java.util.List<TPetSkillDb> cache_vskill;
	static { 
		cache_vskill = new java.util.ArrayList<TPetSkillDb>();
		TPetSkillDb var_72 = new TPetSkillDb();
		cache_vskill.add(var_72);
	}
	static java.util.List<TSkillBuffer> cache_vskillbuffer;
	static { 
		cache_vskillbuffer = new java.util.ArrayList<TSkillBuffer>();
		TSkillBuffer var_73 = new TSkillBuffer();
		cache_vskillbuffer.add(var_73);
	}

	public void readFrom(TarsInputStream _is) {
		this.npetid = _is.read(npetid, 0, true);
		this.nlvl = _is.read(nlvl, 1, true);
		this.icookabil = _is.read(icookabil, 2, true);
		this.idressabil = _is.read(idressabil, 3, true);
		this.igardenabil = _is.read(igardenabil, 4, true);
		this.ipharmacologyabil = _is.read(ipharmacologyabil, 5, true);
		this.istar = _is.read(istar, 6, true);
		this.estatus = _is.read(estatus, 7, false);
		this.vskill = (java.util.List<TPetSkillDb>) _is.read(cache_vskill, 8, false);
		this.vskillbuffer = (java.util.List<TSkillBuffer>) _is.read(cache_vskillbuffer, 9, false);
		this.sname = _is.readString(10, false);
		this.iexp = _is.read(iexp, 11, false);
	}

}
