// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.yoooum.tars.account;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class TPetTaskDBInfo {

	@TarsStructProperty(order = 0, isRequire = false)
	public java.util.Map<java.lang.Short, java.lang.Byte> mtaskdb = null;

	public java.util.Map<java.lang.Short, java.lang.Byte> getMtaskdb() {
		return mtaskdb;
	}

	public void setMtaskdb(java.util.Map<java.lang.Short, java.lang.Byte> mtaskdb) {
		this.mtaskdb = mtaskdb;
	}

	public TPetTaskDBInfo() {
	}

	public TPetTaskDBInfo(java.util.Map<java.lang.Short, java.lang.Byte> mtaskdb) {
		this.mtaskdb = mtaskdb;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(mtaskdb);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof TPetTaskDBInfo)) {
			return false;
		}
		TPetTaskDBInfo other = (TPetTaskDBInfo) obj;
		return (
			TarsUtil.equals(mtaskdb, other.mtaskdb) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		if (null != mtaskdb) {
			_os.write(mtaskdb, 0);
		}
	}

	static java.util.Map<java.lang.Short, java.lang.Byte> cache_mtaskdb;
	static { 
		cache_mtaskdb = new java.util.HashMap<java.lang.Short, java.lang.Byte>();
		short var_84 = (short)0;
		byte var_85 = (byte)0;
		cache_mtaskdb.put(var_84 ,var_85);
	}

	public void readFrom(TarsInputStream _is) {
		this.mtaskdb = (java.util.Map<java.lang.Short, java.lang.Byte>) _is.read(cache_mtaskdb, 0, false);
	}

}
