// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.yoooum.tars.account;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class TProtagonistChapter {

	@TarsStructProperty(order = 0, isRequire = false)
	public int iid = 0;
	@TarsStructProperty(order = 1, isRequire = false)
	public byte cnormalbox = (byte)0;
	@TarsStructProperty(order = 2, isRequire = false)
	public byte chidebox = (byte)0;
	@TarsStructProperty(order = 3, isRequire = false)
	public java.util.List<TProtagonistSection> vecsection = null;
	@TarsStructProperty(order = 4, isRequire = false)
	public java.util.List<TProtagonistSection> vechidesection = null;

	public int getIid() {
		return iid;
	}

	public void setIid(int iid) {
		this.iid = iid;
	}

	public byte getCnormalbox() {
		return cnormalbox;
	}

	public void setCnormalbox(byte cnormalbox) {
		this.cnormalbox = cnormalbox;
	}

	public byte getChidebox() {
		return chidebox;
	}

	public void setChidebox(byte chidebox) {
		this.chidebox = chidebox;
	}

	public java.util.List<TProtagonistSection> getVecsection() {
		return vecsection;
	}

	public void setVecsection(java.util.List<TProtagonistSection> vecsection) {
		this.vecsection = vecsection;
	}

	public java.util.List<TProtagonistSection> getVechidesection() {
		return vechidesection;
	}

	public void setVechidesection(java.util.List<TProtagonistSection> vechidesection) {
		this.vechidesection = vechidesection;
	}

	public TProtagonistChapter() {
	}

	public TProtagonistChapter(int iid, byte cnormalbox, byte chidebox, java.util.List<TProtagonistSection> vecsection, java.util.List<TProtagonistSection> vechidesection) {
		this.iid = iid;
		this.cnormalbox = cnormalbox;
		this.chidebox = chidebox;
		this.vecsection = vecsection;
		this.vechidesection = vechidesection;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(iid);
		result = prime * result + TarsUtil.hashCode(cnormalbox);
		result = prime * result + TarsUtil.hashCode(chidebox);
		result = prime * result + TarsUtil.hashCode(vecsection);
		result = prime * result + TarsUtil.hashCode(vechidesection);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof TProtagonistChapter)) {
			return false;
		}
		TProtagonistChapter other = (TProtagonistChapter) obj;
		return (
			TarsUtil.equals(iid, other.iid) &&
			TarsUtil.equals(cnormalbox, other.cnormalbox) &&
			TarsUtil.equals(chidebox, other.chidebox) &&
			TarsUtil.equals(vecsection, other.vecsection) &&
			TarsUtil.equals(vechidesection, other.vechidesection) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(iid, 0);
		_os.write(cnormalbox, 1);
		_os.write(chidebox, 2);
		if (null != vecsection) {
			_os.write(vecsection, 3);
		}
		if (null != vechidesection) {
			_os.write(vechidesection, 4);
		}
	}

	static java.util.List<TProtagonistSection> cache_vecsection;
	static { 
		cache_vecsection = new java.util.ArrayList<TProtagonistSection>();
		TProtagonistSection var_15 = new TProtagonistSection();
		cache_vecsection.add(var_15);
	}
	static java.util.List<TProtagonistSection> cache_vechidesection;
	static { 
		cache_vechidesection = new java.util.ArrayList<TProtagonistSection>();
		TProtagonistSection var_16 = new TProtagonistSection();
		cache_vechidesection.add(var_16);
	}

	public void readFrom(TarsInputStream _is) {
		this.iid = _is.read(iid, 0, false);
		this.cnormalbox = _is.read(cnormalbox, 1, false);
		this.chidebox = _is.read(chidebox, 2, false);
		this.vecsection = (java.util.List<TProtagonistSection>) _is.read(cache_vecsection, 3, false);
		this.vechidesection = (java.util.List<TProtagonistSection>) _is.read(cache_vechidesection, 4, false);
	}

}
