// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.yoooum.tars.account;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class TPropDbInfo {

	@TarsStructProperty(order = 0, isRequire = false)
	public int iResID = 0;
	@TarsStructProperty(order = 1, isRequire = false)
	public int iUkey = 0;
	@TarsStructProperty(order = 2, isRequire = false)
	public long uCount = 0L;

	public int getIResID() {
		return iResID;
	}

	public void setIResID(int iResID) {
		this.iResID = iResID;
	}

	public int getIUkey() {
		return iUkey;
	}

	public void setIUkey(int iUkey) {
		this.iUkey = iUkey;
	}

	public long getUCount() {
		return uCount;
	}

	public void setUCount(long uCount) {
		this.uCount = uCount;
	}

	public TPropDbInfo() {
	}

	public TPropDbInfo(int iResID, int iUkey, long uCount) {
		this.iResID = iResID;
		this.iUkey = iUkey;
		this.uCount = uCount;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(iResID);
		result = prime * result + TarsUtil.hashCode(iUkey);
		result = prime * result + TarsUtil.hashCode(uCount);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof TPropDbInfo)) {
			return false;
		}
		TPropDbInfo other = (TPropDbInfo) obj;
		return (
			TarsUtil.equals(iResID, other.iResID) &&
			TarsUtil.equals(iUkey, other.iUkey) &&
			TarsUtil.equals(uCount, other.uCount) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(iResID, 0);
		_os.write(iUkey, 1);
		_os.write(uCount, 2);
	}


	public void readFrom(TarsInputStream _is) {
		this.iResID = _is.read(iResID, 0, false);
		this.iUkey = _is.read(iUkey, 1, false);
		this.uCount = _is.read(uCount, 2, false);
	}

}
