// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.yoooum.tars.account;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class TProduceData {

	@TarsStructProperty(order = 0, isRequire = false)
	public short isubid = (short)0;
	@TarsStructProperty(order = 1, isRequire = false)
	public long llastmaketime = 0L;
	@TarsStructProperty(order = 2, isRequire = false)
	public int iprogress = 0;
	@TarsStructProperty(order = 3, isRequire = false)
	public java.util.List<java.lang.Short> veccatid = null;
	@TarsStructProperty(order = 4, isRequire = false)
	public java.util.List<TDBBagResource> veccontent = null;
	@TarsStructProperty(order = 5, isRequire = false)
	public int ispeed = 0;

	public short getIsubid() {
		return isubid;
	}

	public void setIsubid(short isubid) {
		this.isubid = isubid;
	}

	public long getLlastmaketime() {
		return llastmaketime;
	}

	public void setLlastmaketime(long llastmaketime) {
		this.llastmaketime = llastmaketime;
	}

	public int getIprogress() {
		return iprogress;
	}

	public void setIprogress(int iprogress) {
		this.iprogress = iprogress;
	}

	public java.util.List<java.lang.Short> getVeccatid() {
		return veccatid;
	}

	public void setVeccatid(java.util.List<java.lang.Short> veccatid) {
		this.veccatid = veccatid;
	}

	public java.util.List<TDBBagResource> getVeccontent() {
		return veccontent;
	}

	public void setVeccontent(java.util.List<TDBBagResource> veccontent) {
		this.veccontent = veccontent;
	}

	public int getIspeed() {
		return ispeed;
	}

	public void setIspeed(int ispeed) {
		this.ispeed = ispeed;
	}

	public TProduceData() {
	}

	public TProduceData(short isubid, long llastmaketime, int iprogress, java.util.List<java.lang.Short> veccatid, java.util.List<TDBBagResource> veccontent, int ispeed) {
		this.isubid = isubid;
		this.llastmaketime = llastmaketime;
		this.iprogress = iprogress;
		this.veccatid = veccatid;
		this.veccontent = veccontent;
		this.ispeed = ispeed;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(isubid);
		result = prime * result + TarsUtil.hashCode(llastmaketime);
		result = prime * result + TarsUtil.hashCode(iprogress);
		result = prime * result + TarsUtil.hashCode(veccatid);
		result = prime * result + TarsUtil.hashCode(veccontent);
		result = prime * result + TarsUtil.hashCode(ispeed);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof TProduceData)) {
			return false;
		}
		TProduceData other = (TProduceData) obj;
		return (
			TarsUtil.equals(isubid, other.isubid) &&
			TarsUtil.equals(llastmaketime, other.llastmaketime) &&
			TarsUtil.equals(iprogress, other.iprogress) &&
			TarsUtil.equals(veccatid, other.veccatid) &&
			TarsUtil.equals(veccontent, other.veccontent) &&
			TarsUtil.equals(ispeed, other.ispeed) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(isubid, 0);
		_os.write(llastmaketime, 1);
		_os.write(iprogress, 2);
		if (null != veccatid) {
			_os.write(veccatid, 3);
		}
		if (null != veccontent) {
			_os.write(veccontent, 4);
		}
		_os.write(ispeed, 5);
	}

	static java.util.List<java.lang.Short> cache_veccatid;
	static { 
		cache_veccatid = new java.util.ArrayList<java.lang.Short>();
		short var_98 = (short)0;
		cache_veccatid.add(var_98);
	}
	static java.util.List<TDBBagResource> cache_veccontent;
	static { 
		cache_veccontent = new java.util.ArrayList<TDBBagResource>();
		TDBBagResource var_99 = new TDBBagResource();
		cache_veccontent.add(var_99);
	}

	public void readFrom(TarsInputStream _is) {
		this.isubid = _is.read(isubid, 0, false);
		this.llastmaketime = _is.read(llastmaketime, 1, false);
		this.iprogress = _is.read(iprogress, 2, false);
		this.veccatid = (java.util.List<java.lang.Short>) _is.read(cache_veccatid, 3, false);
		this.veccontent = (java.util.List<TDBBagResource>) _is.read(cache_veccontent, 4, false);
		this.ispeed = _is.read(ispeed, 5, false);
	}

}
