// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.yoooum.tars.account;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class TRecruitDb {

	@TarsStructProperty(order = 0, isRequire = false)
	public java.util.List<TRecruitPetDb> vrecruitpetlist = null;
	@TarsStructProperty(order = 1, isRequire = false)
	public long lbegintm = 0L;
	@TarsStructProperty(order = 2, isRequire = false)
	public long lendtm = 0L;
	@TarsStructProperty(order = 3, isRequire = false)
	public short ntodayrefreshtime = (short)0;
	@TarsStructProperty(order = 4, isRequire = false)
	public long llastrefreshtm = 0L;
	@TarsStructProperty(order = 5, isRequire = false)
	public short nsysrefreshtime = (short)0;
	@TarsStructProperty(order = 6, isRequire = false)
	public long llastsysrefreshtm = 0L;
	@TarsStructProperty(order = 7, isRequire = false)
	public java.util.Map<java.lang.Short, java.lang.Integer> mpetfavor = null;
	@TarsStructProperty(order = 8, isRequire = false)
	public java.util.List<java.lang.Integer> vecpettool = null;

	public java.util.List<TRecruitPetDb> getVrecruitpetlist() {
		return vrecruitpetlist;
	}

	public void setVrecruitpetlist(java.util.List<TRecruitPetDb> vrecruitpetlist) {
		this.vrecruitpetlist = vrecruitpetlist;
	}

	public long getLbegintm() {
		return lbegintm;
	}

	public void setLbegintm(long lbegintm) {
		this.lbegintm = lbegintm;
	}

	public long getLendtm() {
		return lendtm;
	}

	public void setLendtm(long lendtm) {
		this.lendtm = lendtm;
	}

	public short getNtodayrefreshtime() {
		return ntodayrefreshtime;
	}

	public void setNtodayrefreshtime(short ntodayrefreshtime) {
		this.ntodayrefreshtime = ntodayrefreshtime;
	}

	public long getLlastrefreshtm() {
		return llastrefreshtm;
	}

	public void setLlastrefreshtm(long llastrefreshtm) {
		this.llastrefreshtm = llastrefreshtm;
	}

	public short getNsysrefreshtime() {
		return nsysrefreshtime;
	}

	public void setNsysrefreshtime(short nsysrefreshtime) {
		this.nsysrefreshtime = nsysrefreshtime;
	}

	public long getLlastsysrefreshtm() {
		return llastsysrefreshtm;
	}

	public void setLlastsysrefreshtm(long llastsysrefreshtm) {
		this.llastsysrefreshtm = llastsysrefreshtm;
	}

	public java.util.Map<java.lang.Short, java.lang.Integer> getMpetfavor() {
		return mpetfavor;
	}

	public void setMpetfavor(java.util.Map<java.lang.Short, java.lang.Integer> mpetfavor) {
		this.mpetfavor = mpetfavor;
	}

	public java.util.List<java.lang.Integer> getVecpettool() {
		return vecpettool;
	}

	public void setVecpettool(java.util.List<java.lang.Integer> vecpettool) {
		this.vecpettool = vecpettool;
	}

	public TRecruitDb() {
	}

	public TRecruitDb(java.util.List<TRecruitPetDb> vrecruitpetlist, long lbegintm, long lendtm, short ntodayrefreshtime, long llastrefreshtm, short nsysrefreshtime, long llastsysrefreshtm, java.util.Map<java.lang.Short, java.lang.Integer> mpetfavor, java.util.List<java.lang.Integer> vecpettool) {
		this.vrecruitpetlist = vrecruitpetlist;
		this.lbegintm = lbegintm;
		this.lendtm = lendtm;
		this.ntodayrefreshtime = ntodayrefreshtime;
		this.llastrefreshtm = llastrefreshtm;
		this.nsysrefreshtime = nsysrefreshtime;
		this.llastsysrefreshtm = llastsysrefreshtm;
		this.mpetfavor = mpetfavor;
		this.vecpettool = vecpettool;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(vrecruitpetlist);
		result = prime * result + TarsUtil.hashCode(lbegintm);
		result = prime * result + TarsUtil.hashCode(lendtm);
		result = prime * result + TarsUtil.hashCode(ntodayrefreshtime);
		result = prime * result + TarsUtil.hashCode(llastrefreshtm);
		result = prime * result + TarsUtil.hashCode(nsysrefreshtime);
		result = prime * result + TarsUtil.hashCode(llastsysrefreshtm);
		result = prime * result + TarsUtil.hashCode(mpetfavor);
		result = prime * result + TarsUtil.hashCode(vecpettool);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof TRecruitDb)) {
			return false;
		}
		TRecruitDb other = (TRecruitDb) obj;
		return (
			TarsUtil.equals(vrecruitpetlist, other.vrecruitpetlist) &&
			TarsUtil.equals(lbegintm, other.lbegintm) &&
			TarsUtil.equals(lendtm, other.lendtm) &&
			TarsUtil.equals(ntodayrefreshtime, other.ntodayrefreshtime) &&
			TarsUtil.equals(llastrefreshtm, other.llastrefreshtm) &&
			TarsUtil.equals(nsysrefreshtime, other.nsysrefreshtime) &&
			TarsUtil.equals(llastsysrefreshtm, other.llastsysrefreshtm) &&
			TarsUtil.equals(mpetfavor, other.mpetfavor) &&
			TarsUtil.equals(vecpettool, other.vecpettool) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		if (null != vrecruitpetlist) {
			_os.write(vrecruitpetlist, 0);
		}
		_os.write(lbegintm, 1);
		_os.write(lendtm, 2);
		_os.write(ntodayrefreshtime, 3);
		_os.write(llastrefreshtm, 4);
		_os.write(nsysrefreshtime, 5);
		_os.write(llastsysrefreshtm, 6);
		if (null != mpetfavor) {
			_os.write(mpetfavor, 7);
		}
		if (null != vecpettool) {
			_os.write(vecpettool, 8);
		}
	}

	static java.util.List<TRecruitPetDb> cache_vrecruitpetlist;
	static { 
		cache_vrecruitpetlist = new java.util.ArrayList<TRecruitPetDb>();
		TRecruitPetDb var_86 = new TRecruitPetDb();
		cache_vrecruitpetlist.add(var_86);
	}
	static java.util.Map<java.lang.Short, java.lang.Integer> cache_mpetfavor;
	static { 
		cache_mpetfavor = new java.util.HashMap<java.lang.Short, java.lang.Integer>();
		short var_87 = (short)0;
		int var_88 = 0;
		cache_mpetfavor.put(var_87 ,var_88);
	}
	static java.util.List<java.lang.Integer> cache_vecpettool;
	static { 
		cache_vecpettool = new java.util.ArrayList<java.lang.Integer>();
		int var_89 = 0;
		cache_vecpettool.add(var_89);
	}

	public void readFrom(TarsInputStream _is) {
		this.vrecruitpetlist = (java.util.List<TRecruitPetDb>) _is.read(cache_vrecruitpetlist, 0, false);
		this.lbegintm = _is.read(lbegintm, 1, false);
		this.lendtm = _is.read(lendtm, 2, false);
		this.ntodayrefreshtime = _is.read(ntodayrefreshtime, 3, false);
		this.llastrefreshtm = _is.read(llastrefreshtm, 4, false);
		this.nsysrefreshtime = _is.read(nsysrefreshtime, 5, false);
		this.llastsysrefreshtm = _is.read(llastsysrefreshtm, 6, false);
		this.mpetfavor = (java.util.Map<java.lang.Short, java.lang.Integer>) _is.read(cache_mpetfavor, 7, false);
		this.vecpettool = (java.util.List<java.lang.Integer>) _is.read(cache_vecpettool, 8, false);
	}

}
