// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.yoooum.tars.account;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class TRoleStoryEvent {

	@TarsStructProperty(order = 0, isRequire = false)
	public java.util.List<TRoleEventData> vecnotvieweventdata = null;

	public java.util.List<TRoleEventData> getVecnotvieweventdata() {
		return vecnotvieweventdata;
	}

	public void setVecnotvieweventdata(java.util.List<TRoleEventData> vecnotvieweventdata) {
		this.vecnotvieweventdata = vecnotvieweventdata;
	}

	public TRoleStoryEvent() {
	}

	public TRoleStoryEvent(java.util.List<TRoleEventData> vecnotvieweventdata) {
		this.vecnotvieweventdata = vecnotvieweventdata;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(vecnotvieweventdata);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof TRoleStoryEvent)) {
			return false;
		}
		TRoleStoryEvent other = (TRoleStoryEvent) obj;
		return (
			TarsUtil.equals(vecnotvieweventdata, other.vecnotvieweventdata) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		if (null != vecnotvieweventdata) {
			_os.write(vecnotvieweventdata, 0);
		}
	}

	static java.util.List<TRoleEventData> cache_vecnotvieweventdata;
	static { 
		cache_vecnotvieweventdata = new java.util.ArrayList<TRoleEventData>();
		TRoleEventData var_58 = new TRoleEventData();
		cache_vecnotvieweventdata.add(var_58);
	}

	public void readFrom(TarsInputStream _is) {
		this.vecnotvieweventdata = (java.util.List<TRoleEventData>) _is.read(cache_vecnotvieweventdata, 0, false);
	}

}
