// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.yoooum.tars.account;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class TRoleEventData {

	@TarsStructProperty(order = 0, isRequire = false)
	public short ieventid = (short)0;
	@TarsStructProperty(order = 1, isRequire = false)
	public long utrigtime = 0L;
	@TarsStructProperty(order = 2, isRequire = false)
	public long ueventexpiretime = 0L;
	@TarsStructProperty(order = 3, isRequire = false)
	public byte cstatus = (byte)0;

	public short getIeventid() {
		return ieventid;
	}

	public void setIeventid(short ieventid) {
		this.ieventid = ieventid;
	}

	public long getUtrigtime() {
		return utrigtime;
	}

	public void setUtrigtime(long utrigtime) {
		this.utrigtime = utrigtime;
	}

	public long getUeventexpiretime() {
		return ueventexpiretime;
	}

	public void setUeventexpiretime(long ueventexpiretime) {
		this.ueventexpiretime = ueventexpiretime;
	}

	public byte getCstatus() {
		return cstatus;
	}

	public void setCstatus(byte cstatus) {
		this.cstatus = cstatus;
	}

	public TRoleEventData() {
	}

	public TRoleEventData(short ieventid, long utrigtime, long ueventexpiretime, byte cstatus) {
		this.ieventid = ieventid;
		this.utrigtime = utrigtime;
		this.ueventexpiretime = ueventexpiretime;
		this.cstatus = cstatus;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(ieventid);
		result = prime * result + TarsUtil.hashCode(utrigtime);
		result = prime * result + TarsUtil.hashCode(ueventexpiretime);
		result = prime * result + TarsUtil.hashCode(cstatus);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof TRoleEventData)) {
			return false;
		}
		TRoleEventData other = (TRoleEventData) obj;
		return (
			TarsUtil.equals(ieventid, other.ieventid) &&
			TarsUtil.equals(utrigtime, other.utrigtime) &&
			TarsUtil.equals(ueventexpiretime, other.ueventexpiretime) &&
			TarsUtil.equals(cstatus, other.cstatus) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(ieventid, 0);
		_os.write(utrigtime, 1);
		_os.write(ueventexpiretime, 2);
		_os.write(cstatus, 3);
	}


	public void readFrom(TarsInputStream _is) {
		this.ieventid = _is.read(ieventid, 0, false);
		this.utrigtime = _is.read(utrigtime, 1, false);
		this.ueventexpiretime = _is.read(ueventexpiretime, 2, false);
		this.cstatus = _is.read(cstatus, 3, false);
	}

}
