// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.yoooum.tars.account;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class TShopNpc {

	@TarsStructProperty(order = 0, isRequire = false)
	public short ushnpcid = (short)0;
	@TarsStructProperty(order = 1, isRequire = false)
	public byte cstatus = (byte)0;
	@TarsStructProperty(order = 2, isRequire = false)
	public int ifriendprogress = 0;
	@TarsStructProperty(order = 3, isRequire = false)
	public java.util.List<TTradeItemInfo> vecresource = null;
	@TarsStructProperty(order = 4, isRequire = false)
	public long ufinishtime = 0L;

	public short getUshnpcid() {
		return ushnpcid;
	}

	public void setUshnpcid(short ushnpcid) {
		this.ushnpcid = ushnpcid;
	}

	public byte getCstatus() {
		return cstatus;
	}

	public void setCstatus(byte cstatus) {
		this.cstatus = cstatus;
	}

	public int getIfriendprogress() {
		return ifriendprogress;
	}

	public void setIfriendprogress(int ifriendprogress) {
		this.ifriendprogress = ifriendprogress;
	}

	public java.util.List<TTradeItemInfo> getVecresource() {
		return vecresource;
	}

	public void setVecresource(java.util.List<TTradeItemInfo> vecresource) {
		this.vecresource = vecresource;
	}

	public long getUfinishtime() {
		return ufinishtime;
	}

	public void setUfinishtime(long ufinishtime) {
		this.ufinishtime = ufinishtime;
	}

	public TShopNpc() {
	}

	public TShopNpc(short ushnpcid, byte cstatus, int ifriendprogress, java.util.List<TTradeItemInfo> vecresource, long ufinishtime) {
		this.ushnpcid = ushnpcid;
		this.cstatus = cstatus;
		this.ifriendprogress = ifriendprogress;
		this.vecresource = vecresource;
		this.ufinishtime = ufinishtime;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(ushnpcid);
		result = prime * result + TarsUtil.hashCode(cstatus);
		result = prime * result + TarsUtil.hashCode(ifriendprogress);
		result = prime * result + TarsUtil.hashCode(vecresource);
		result = prime * result + TarsUtil.hashCode(ufinishtime);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof TShopNpc)) {
			return false;
		}
		TShopNpc other = (TShopNpc) obj;
		return (
			TarsUtil.equals(ushnpcid, other.ushnpcid) &&
			TarsUtil.equals(cstatus, other.cstatus) &&
			TarsUtil.equals(ifriendprogress, other.ifriendprogress) &&
			TarsUtil.equals(vecresource, other.vecresource) &&
			TarsUtil.equals(ufinishtime, other.ufinishtime) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(ushnpcid, 0);
		_os.write(cstatus, 1);
		_os.write(ifriendprogress, 2);
		if (null != vecresource) {
			_os.write(vecresource, 3);
		}
		_os.write(ufinishtime, 4);
	}

	static java.util.List<TTradeItemInfo> cache_vecresource;
	static { 
		cache_vecresource = new java.util.ArrayList<TTradeItemInfo>();
		TTradeItemInfo var_105 = new TTradeItemInfo();
		cache_vecresource.add(var_105);
	}

	public void readFrom(TarsInputStream _is) {
		this.ushnpcid = _is.read(ushnpcid, 0, false);
		this.cstatus = _is.read(cstatus, 1, false);
		this.ifriendprogress = _is.read(ifriendprogress, 2, false);
		this.vecresource = (java.util.List<TTradeItemInfo>) _is.read(cache_vecresource, 3, false);
		this.ufinishtime = _is.read(ufinishtime, 4, false);
	}

}
