// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.yoooum.tars.account;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class TSkillBuffer {

	@TarsStructProperty(order = 0, isRequire = false)
	public short nbufferid = (short)0;
	@TarsStructProperty(order = 1, isRequire = false)
	public long ltime = 0L;
	@TarsStructProperty(order = 2, isRequire = false)
	public int ivalue = 0;

	public short getNbufferid() {
		return nbufferid;
	}

	public void setNbufferid(short nbufferid) {
		this.nbufferid = nbufferid;
	}

	public long getLtime() {
		return ltime;
	}

	public void setLtime(long ltime) {
		this.ltime = ltime;
	}

	public int getIvalue() {
		return ivalue;
	}

	public void setIvalue(int ivalue) {
		this.ivalue = ivalue;
	}

	public TSkillBuffer() {
	}

	public TSkillBuffer(short nbufferid, long ltime, int ivalue) {
		this.nbufferid = nbufferid;
		this.ltime = ltime;
		this.ivalue = ivalue;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(nbufferid);
		result = prime * result + TarsUtil.hashCode(ltime);
		result = prime * result + TarsUtil.hashCode(ivalue);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof TSkillBuffer)) {
			return false;
		}
		TSkillBuffer other = (TSkillBuffer) obj;
		return (
			TarsUtil.equals(nbufferid, other.nbufferid) &&
			TarsUtil.equals(ltime, other.ltime) &&
			TarsUtil.equals(ivalue, other.ivalue) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(nbufferid, 0);
		_os.write(ltime, 1);
		_os.write(ivalue, 2);
	}


	public void readFrom(TarsInputStream _is) {
		this.nbufferid = _is.read(nbufferid, 0, false);
		this.ltime = _is.read(ltime, 1, false);
		this.ivalue = _is.read(ivalue, 2, false);
	}

}
