// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.yoooum.tars.account;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class TSoldierDB {

	@TarsStructProperty(order = 0, isRequire = false)
	public int iID = 0;
	@TarsStructProperty(order = 1, isRequire = false)
	public long lCatchTM = 0L;

	public int getIID() {
		return iID;
	}

	public void setIID(int iID) {
		this.iID = iID;
	}

	public long getLCatchTM() {
		return lCatchTM;
	}

	public void setLCatchTM(long lCatchTM) {
		this.lCatchTM = lCatchTM;
	}

	public TSoldierDB() {
	}

	public TSoldierDB(int iID, long lCatchTM) {
		this.iID = iID;
		this.lCatchTM = lCatchTM;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(iID);
		result = prime * result + TarsUtil.hashCode(lCatchTM);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof TSoldierDB)) {
			return false;
		}
		TSoldierDB other = (TSoldierDB) obj;
		return (
			TarsUtil.equals(iID, other.iID) &&
			TarsUtil.equals(lCatchTM, other.lCatchTM) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(iID, 0);
		_os.write(lCatchTM, 1);
	}


	public void readFrom(TarsInputStream _is) {
		this.iID = _is.read(iID, 0, false);
		this.lCatchTM = _is.read(lCatchTM, 1, false);
	}

}
