// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.yoooum.tars.account;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class TSoldierInfo {

	@TarsStructProperty(order = 0, isRequire = false)
	public java.util.List<TSoldierDB> vecSoldierList = null;
	@TarsStructProperty(order = 1, isRequire = false)
	public java.util.List<com.yoooum.tars.commdata.TItemParam> vecAwardList = null;
	@TarsStructProperty(order = 2, isRequire = false)
	public java.util.List<TSoldierCollectData> vecSoldierCollectData = null;
	@TarsStructProperty(order = 3, isRequire = false)
	public long lCalculateTM = 0L;
	@TarsStructProperty(order = 4, isRequire = false)
	public long lLastDrawAwardTM = 0L;

	public java.util.List<TSoldierDB> getVecSoldierList() {
		return vecSoldierList;
	}

	public void setVecSoldierList(java.util.List<TSoldierDB> vecSoldierList) {
		this.vecSoldierList = vecSoldierList;
	}

	public java.util.List<com.yoooum.tars.commdata.TItemParam> getVecAwardList() {
		return vecAwardList;
	}

	public void setVecAwardList(java.util.List<com.yoooum.tars.commdata.TItemParam> vecAwardList) {
		this.vecAwardList = vecAwardList;
	}

	public java.util.List<TSoldierCollectData> getVecSoldierCollectData() {
		return vecSoldierCollectData;
	}

	public void setVecSoldierCollectData(java.util.List<TSoldierCollectData> vecSoldierCollectData) {
		this.vecSoldierCollectData = vecSoldierCollectData;
	}

	public long getLCalculateTM() {
		return lCalculateTM;
	}

	public void setLCalculateTM(long lCalculateTM) {
		this.lCalculateTM = lCalculateTM;
	}

	public long getLLastDrawAwardTM() {
		return lLastDrawAwardTM;
	}

	public void setLLastDrawAwardTM(long lLastDrawAwardTM) {
		this.lLastDrawAwardTM = lLastDrawAwardTM;
	}

	public TSoldierInfo() {
	}

	public TSoldierInfo(java.util.List<TSoldierDB> vecSoldierList, java.util.List<com.yoooum.tars.commdata.TItemParam> vecAwardList, java.util.List<TSoldierCollectData> vecSoldierCollectData, long lCalculateTM, long lLastDrawAwardTM) {
		this.vecSoldierList = vecSoldierList;
		this.vecAwardList = vecAwardList;
		this.vecSoldierCollectData = vecSoldierCollectData;
		this.lCalculateTM = lCalculateTM;
		this.lLastDrawAwardTM = lLastDrawAwardTM;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(vecSoldierList);
		result = prime * result + TarsUtil.hashCode(vecAwardList);
		result = prime * result + TarsUtil.hashCode(vecSoldierCollectData);
		result = prime * result + TarsUtil.hashCode(lCalculateTM);
		result = prime * result + TarsUtil.hashCode(lLastDrawAwardTM);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof TSoldierInfo)) {
			return false;
		}
		TSoldierInfo other = (TSoldierInfo) obj;
		return (
			TarsUtil.equals(vecSoldierList, other.vecSoldierList) &&
			TarsUtil.equals(vecAwardList, other.vecAwardList) &&
			TarsUtil.equals(vecSoldierCollectData, other.vecSoldierCollectData) &&
			TarsUtil.equals(lCalculateTM, other.lCalculateTM) &&
			TarsUtil.equals(lLastDrawAwardTM, other.lLastDrawAwardTM) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		if (null != vecSoldierList) {
			_os.write(vecSoldierList, 0);
		}
		if (null != vecAwardList) {
			_os.write(vecAwardList, 1);
		}
		if (null != vecSoldierCollectData) {
			_os.write(vecSoldierCollectData, 2);
		}
		_os.write(lCalculateTM, 3);
		_os.write(lLastDrawAwardTM, 4);
	}

	static java.util.List<TSoldierDB> cache_vecSoldierList;
	static { 
		cache_vecSoldierList = new java.util.ArrayList<TSoldierDB>();
		TSoldierDB var_29 = new TSoldierDB();
		cache_vecSoldierList.add(var_29);
	}
	static java.util.List<com.yoooum.tars.commdata.TItemParam> cache_vecAwardList;
	static { 
		cache_vecAwardList = new java.util.ArrayList<com.yoooum.tars.commdata.TItemParam>();
		com.yoooum.tars.commdata.TItemParam var_30 = new com.yoooum.tars.commdata.TItemParam();
		cache_vecAwardList.add(var_30);
	}
	static java.util.List<TSoldierCollectData> cache_vecSoldierCollectData;
	static { 
		cache_vecSoldierCollectData = new java.util.ArrayList<TSoldierCollectData>();
		TSoldierCollectData var_31 = new TSoldierCollectData();
		cache_vecSoldierCollectData.add(var_31);
	}

	public void readFrom(TarsInputStream _is) {
		this.vecSoldierList = (java.util.List<TSoldierDB>) _is.read(cache_vecSoldierList, 0, false);
		this.vecAwardList = (java.util.List<com.yoooum.tars.commdata.TItemParam>) _is.read(cache_vecAwardList, 1, false);
		this.vecSoldierCollectData = (java.util.List<TSoldierCollectData>) _is.read(cache_vecSoldierCollectData, 2, false);
		this.lCalculateTM = _is.read(lCalculateTM, 3, false);
		this.lLastDrawAwardTM = _is.read(lLastDrawAwardTM, 4, false);
	}

}
