// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.yoooum.tars.account;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class TSpecailNpc {

	@TarsStructProperty(order = 0, isRequire = false)
	public short ushnpcid = (short)0;
	@TarsStructProperty(order = 1, isRequire = false)
	public byte cstatus = (byte)0;

	public short getUshnpcid() {
		return ushnpcid;
	}

	public void setUshnpcid(short ushnpcid) {
		this.ushnpcid = ushnpcid;
	}

	public byte getCstatus() {
		return cstatus;
	}

	public void setCstatus(byte cstatus) {
		this.cstatus = cstatus;
	}

	public TSpecailNpc() {
	}

	public TSpecailNpc(short ushnpcid, byte cstatus) {
		this.ushnpcid = ushnpcid;
		this.cstatus = cstatus;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(ushnpcid);
		result = prime * result + TarsUtil.hashCode(cstatus);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof TSpecailNpc)) {
			return false;
		}
		TSpecailNpc other = (TSpecailNpc) obj;
		return (
			TarsUtil.equals(ushnpcid, other.ushnpcid) &&
			TarsUtil.equals(cstatus, other.cstatus) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(ushnpcid, 0);
		_os.write(cstatus, 1);
	}


	public void readFrom(TarsInputStream _is) {
		this.ushnpcid = _is.read(ushnpcid, 0, false);
		this.cstatus = _is.read(cstatus, 1, false);
	}

}
