// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.yoooum.tars.account;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class TStageInfo {

	@TarsStructProperty(order = 0, isRequire = false)
	public java.util.List<TStageDB> vecStageDB = null;
	@TarsStructProperty(order = 1, isRequire = false)
	public java.util.List<java.lang.Integer> vecStageChapter = null;
	@TarsStructProperty(order = 2, isRequire = false)
	public java.util.Map<java.lang.Integer, TBoxState> mBoxAwardInfo = null;
	@TarsStructProperty(order = 3, isRequire = false)
	public int iClearingState = 0;
	@TarsStructProperty(order = 4, isRequire = false)
	public int iDropCount = 0;
	@TarsStructProperty(order = 5, isRequire = false)
	public int iNewStageChapterId = 0;
	@TarsStructProperty(order = 6, isRequire = false)
	public int iNewStageLevelId = 0;
	@TarsStructProperty(order = 7, isRequire = false)
	public long lCurrRoundBeginTM = 0;

	public java.util.List<TStageDB> getVecStageDB() {
		return vecStageDB;
	}

	public void setVecStageDB(java.util.List<TStageDB> vecStageDB) {
		this.vecStageDB = vecStageDB;
	}

	public java.util.List<java.lang.Integer> getVecStageChapter() {
		return vecStageChapter;
	}

	public void setVecStageChapter(java.util.List<java.lang.Integer> vecStageChapter) {
		this.vecStageChapter = vecStageChapter;
	}

	public java.util.Map<java.lang.Integer, TBoxState> getMBoxAwardInfo() {
		return mBoxAwardInfo;
	}

	public void setMBoxAwardInfo(java.util.Map<java.lang.Integer, TBoxState> mBoxAwardInfo) {
		this.mBoxAwardInfo = mBoxAwardInfo;
	}

	public int getIClearingState() {
		return iClearingState;
	}

	public void setIClearingState(int iClearingState) {
		this.iClearingState = iClearingState;
	}

	public int getIDropCount() {
		return iDropCount;
	}

	public void setIDropCount(int iDropCount) {
		this.iDropCount = iDropCount;
	}

	public int getINewStageChapterId() {
		return iNewStageChapterId;
	}

	public void setINewStageChapterId(int iNewStageChapterId) {
		this.iNewStageChapterId = iNewStageChapterId;
	}

	public int getINewStageLevelId() {
		return iNewStageLevelId;
	}

	public void setINewStageLevelId(int iNewStageLevelId) {
		this.iNewStageLevelId = iNewStageLevelId;
	}

	public long getLCurrRoundBeginTM() {
		return lCurrRoundBeginTM;
	}

	public void setLCurrRoundBeginTM(long lCurrRoundBeginTM) {
		this.lCurrRoundBeginTM = lCurrRoundBeginTM;
	}

	public TStageInfo() {
	}

	public TStageInfo(java.util.List<TStageDB> vecStageDB, java.util.List<java.lang.Integer> vecStageChapter, java.util.Map<java.lang.Integer, TBoxState> mBoxAwardInfo, int iClearingState, int iDropCount, int iNewStageChapterId, int iNewStageLevelId, long lCurrRoundBeginTM) {
		this.vecStageDB = vecStageDB;
		this.vecStageChapter = vecStageChapter;
		this.mBoxAwardInfo = mBoxAwardInfo;
		this.iClearingState = iClearingState;
		this.iDropCount = iDropCount;
		this.iNewStageChapterId = iNewStageChapterId;
		this.iNewStageLevelId = iNewStageLevelId;
		this.lCurrRoundBeginTM = lCurrRoundBeginTM;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(vecStageDB);
		result = prime * result + TarsUtil.hashCode(vecStageChapter);
		result = prime * result + TarsUtil.hashCode(mBoxAwardInfo);
		result = prime * result + TarsUtil.hashCode(iClearingState);
		result = prime * result + TarsUtil.hashCode(iDropCount);
		result = prime * result + TarsUtil.hashCode(iNewStageChapterId);
		result = prime * result + TarsUtil.hashCode(iNewStageLevelId);
		result = prime * result + TarsUtil.hashCode(lCurrRoundBeginTM);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof TStageInfo)) {
			return false;
		}
		TStageInfo other = (TStageInfo) obj;
		return (
			TarsUtil.equals(vecStageDB, other.vecStageDB) &&
			TarsUtil.equals(vecStageChapter, other.vecStageChapter) &&
			TarsUtil.equals(mBoxAwardInfo, other.mBoxAwardInfo) &&
			TarsUtil.equals(iClearingState, other.iClearingState) &&
			TarsUtil.equals(iDropCount, other.iDropCount) &&
			TarsUtil.equals(iNewStageChapterId, other.iNewStageChapterId) &&
			TarsUtil.equals(iNewStageLevelId, other.iNewStageLevelId) &&
			TarsUtil.equals(lCurrRoundBeginTM, other.lCurrRoundBeginTM) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		if (null != vecStageDB) {
			_os.write(vecStageDB, 0);
		}
		if (null != vecStageChapter) {
			_os.write(vecStageChapter, 1);
		}
		if (null != mBoxAwardInfo) {
			_os.write(mBoxAwardInfo, 2);
		}
		_os.write(iClearingState, 3);
		_os.write(iDropCount, 4);
		_os.write(iNewStageChapterId, 5);
		_os.write(iNewStageLevelId, 6);
		_os.write(lCurrRoundBeginTM, 7);
	}

	static java.util.List<TStageDB> cache_vecStageDB;
	static { 
		cache_vecStageDB = new java.util.ArrayList<TStageDB>();
		TStageDB var_42 = new TStageDB();
		cache_vecStageDB.add(var_42);
	}
	static java.util.List<java.lang.Integer> cache_vecStageChapter;
	static { 
		cache_vecStageChapter = new java.util.ArrayList<java.lang.Integer>();
		int var_43 = 0;
		cache_vecStageChapter.add(var_43);
	}
	static java.util.Map<java.lang.Integer, TBoxState> cache_mBoxAwardInfo;
	static { 
		cache_mBoxAwardInfo = new java.util.HashMap<java.lang.Integer, TBoxState>();
		int var_44 = 0;
		TBoxState var_45 = new TBoxState();
		cache_mBoxAwardInfo.put(var_44 ,var_45);
	}

	public void readFrom(TarsInputStream _is) {
		this.vecStageDB = (java.util.List<TStageDB>) _is.read(cache_vecStageDB, 0, false);
		this.vecStageChapter = (java.util.List<java.lang.Integer>) _is.read(cache_vecStageChapter, 1, false);
		this.mBoxAwardInfo = (java.util.Map<java.lang.Integer, TBoxState>) _is.read(cache_mBoxAwardInfo, 2, false);
		this.iClearingState = _is.read(iClearingState, 3, false);
		this.iDropCount = _is.read(iDropCount, 4, false);
		this.iNewStageChapterId = _is.read(iNewStageChapterId, 5, false);
		this.iNewStageLevelId = _is.read(iNewStageLevelId, 6, false);
		this.lCurrRoundBeginTM = _is.read(lCurrRoundBeginTM, 7, false);
	}

}
