// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.yoooum.tars.account;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class TStorageInfo {

	@TarsStructProperty(order = 0, isRequire = false)
	public java.util.List<TDBBagResource> vecResource = null;

	public java.util.List<TDBBagResource> getVecResource() {
		return vecResource;
	}

	public void setVecResource(java.util.List<TDBBagResource> vecResource) {
		this.vecResource = vecResource;
	}

	public TStorageInfo() {
	}

	public TStorageInfo(java.util.List<TDBBagResource> vecResource) {
		this.vecResource = vecResource;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(vecResource);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof TStorageInfo)) {
			return false;
		}
		TStorageInfo other = (TStorageInfo) obj;
		return (
			TarsUtil.equals(vecResource, other.vecResource) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		if (null != vecResource) {
			_os.write(vecResource, 0);
		}
	}

	static java.util.List<TDBBagResource> cache_vecResource;
	static { 
		cache_vecResource = new java.util.ArrayList<TDBBagResource>();
		TDBBagResource var_18 = new TDBBagResource();
		cache_vecResource.add(var_18);
	}

	public void readFrom(TarsInputStream _is) {
		this.vecResource = (java.util.List<TDBBagResource>) _is.read(cache_vecResource, 0, false);
	}

}
