// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.yoooum.tars.account;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class TStoryGameDb {

	@TarsStructProperty(order = 0, isRequire = false)
	public short shgameid = (short)0;
	@TarsStructProperty(order = 1, isRequire = false)
	public short shsubid = (short)0;
	@TarsStructProperty(order = 2, isRequire = false)
	public long llastplaytime = 0L;
	@TarsStructProperty(order = 3, isRequire = false)
	public short shplaycount = (short)0;
	@TarsStructProperty(order = 4, isRequire = false)
	public byte cstatus = (byte)0;
	@TarsStructProperty(order = 5, isRequire = false)
	public java.util.List<java.lang.Integer> vecparam = null;

	public short getShgameid() {
		return shgameid;
	}

	public void setShgameid(short shgameid) {
		this.shgameid = shgameid;
	}

	public short getShsubid() {
		return shsubid;
	}

	public void setShsubid(short shsubid) {
		this.shsubid = shsubid;
	}

	public long getLlastplaytime() {
		return llastplaytime;
	}

	public void setLlastplaytime(long llastplaytime) {
		this.llastplaytime = llastplaytime;
	}

	public short getShplaycount() {
		return shplaycount;
	}

	public void setShplaycount(short shplaycount) {
		this.shplaycount = shplaycount;
	}

	public byte getCstatus() {
		return cstatus;
	}

	public void setCstatus(byte cstatus) {
		this.cstatus = cstatus;
	}

	public java.util.List<java.lang.Integer> getVecparam() {
		return vecparam;
	}

	public void setVecparam(java.util.List<java.lang.Integer> vecparam) {
		this.vecparam = vecparam;
	}

	public TStoryGameDb() {
	}

	public TStoryGameDb(short shgameid, short shsubid, long llastplaytime, short shplaycount, byte cstatus, java.util.List<java.lang.Integer> vecparam) {
		this.shgameid = shgameid;
		this.shsubid = shsubid;
		this.llastplaytime = llastplaytime;
		this.shplaycount = shplaycount;
		this.cstatus = cstatus;
		this.vecparam = vecparam;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(shgameid);
		result = prime * result + TarsUtil.hashCode(shsubid);
		result = prime * result + TarsUtil.hashCode(llastplaytime);
		result = prime * result + TarsUtil.hashCode(shplaycount);
		result = prime * result + TarsUtil.hashCode(cstatus);
		result = prime * result + TarsUtil.hashCode(vecparam);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof TStoryGameDb)) {
			return false;
		}
		TStoryGameDb other = (TStoryGameDb) obj;
		return (
			TarsUtil.equals(shgameid, other.shgameid) &&
			TarsUtil.equals(shsubid, other.shsubid) &&
			TarsUtil.equals(llastplaytime, other.llastplaytime) &&
			TarsUtil.equals(shplaycount, other.shplaycount) &&
			TarsUtil.equals(cstatus, other.cstatus) &&
			TarsUtil.equals(vecparam, other.vecparam) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(shgameid, 0);
		_os.write(shsubid, 1);
		_os.write(llastplaytime, 2);
		_os.write(shplaycount, 3);
		_os.write(cstatus, 4);
		if (null != vecparam) {
			_os.write(vecparam, 5);
		}
	}

	static java.util.List<java.lang.Integer> cache_vecparam;
	static { 
		cache_vecparam = new java.util.ArrayList<java.lang.Integer>();
		int var_50 = 0;
		cache_vecparam.add(var_50);
	}

	public void readFrom(TarsInputStream _is) {
		this.shgameid = _is.read(shgameid, 0, false);
		this.shsubid = _is.read(shsubid, 1, false);
		this.llastplaytime = _is.read(llastplaytime, 2, false);
		this.shplaycount = _is.read(shplaycount, 3, false);
		this.cstatus = _is.read(cstatus, 4, false);
		this.vecparam = (java.util.List<java.lang.Integer>) _is.read(cache_vecparam, 5, false);
	}

}
