// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.yoooum.tars.commdata;

public enum E_EXPLORA_STATUS {

	E_EXPLORA_STATUS_FREE(0),
	E_EXPLORA_STATUS_EXPLORA(1),
	E_EXPLORA_STATUS_FINISH(2),
	E_EXPLORA_STATUS_END(3);

	private final int value;

	private E_EXPLORA_STATUS(int value) {
		this.value = value;
	}

	public int value() {
		return this.value;
	}

	@Override
	public String toString() {
		return this.name() + ":" + this.value;
	}

	public static E_EXPLORA_STATUS convert(int value) {
		for(E_EXPLORA_STATUS v : values()) {
			if(v.value() == value) {
				return v;
			}
		}
		return null;
	}
}
