// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.yoooum.tars.commdata;

public enum E_EXPLOR_EVENT_TYPE {

	E_EXPLOR_EVENT_INVAILD(0),
	E_EXPLOR_EVENT_FIGHT(1),
	E_EXPLOR_EVENT_COLLET(2),
	E_EXPLOR_EVENT_TREASURE(3),
	E_EXPLOR_EVENT_BOSS(4);

	private final int value;

	private E_EXPLOR_EVENT_TYPE(int value) {
		this.value = value;
	}

	public int value() {
		return this.value;
	}

	@Override
	public String toString() {
		return this.name() + ":" + this.value;
	}

	public static E_EXPLOR_EVENT_TYPE convert(int value) {
		for(E_EXPLOR_EVENT_TYPE v : values()) {
			if(v.value() == value) {
				return v;
			}
		}
		return null;
	}
}
