// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.yoooum.tars.commdata;

public enum E_PET_TASK_CONDITION_TYPE {

	E_PET_TASK_CONDITION_TYPE_TOTAL_ATTR(1),
	E_PET_TASK_CONDITION_TYPE_NUM(2),
	E_PET_TASK_CONDITION_TYPE_WORK_COUNT(3),
	E_PET_TASK_CONDITION_TYPE_WORK_TIME(4);

	private final int value;

	private E_PET_TASK_CONDITION_TYPE(int value) {
		this.value = value;
	}

	public int value() {
		return this.value;
	}

	@Override
	public String toString() {
		return this.name() + ":" + this.value;
	}

	public static E_PET_TASK_CONDITION_TYPE convert(int value) {
		for(E_PET_TASK_CONDITION_TYPE v : values()) {
			if(v.value() == value) {
				return v;
			}
		}
		return null;
	}
}
