// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.yoooum.tars.commdata;

public enum E_ROLE_TRIGGER_TYPE {

	E_ROLE_TRIGGER_COMMON(0),
	E_ROLE_TRIGGER_LOGIN(1),
	E_ROLE_TRIGGER_ONLINE(2),
	E_ROLE_TRIGGER_TIME_RANGE(3),
	E_ROLE_TRIGGER_MAINSTORY(4),
	E_ROLE_TRIGGER_BRANCHSTORY(5);

	private final int value;

	private E_ROLE_TRIGGER_TYPE(int value) {
		this.value = value;
	}

	public int value() {
		return this.value;
	}

	@Override
	public String toString() {
		return this.name() + ":" + this.value;
	}

	public static E_ROLE_TRIGGER_TYPE convert(int value) {
		for(E_ROLE_TRIGGER_TYPE v : values()) {
			if(v.value() == value) {
				return v;
			}
		}
		return null;
	}
}
