// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.yoooum.tars.commdata;

public enum E_SOURCE_TYPE {

	E_SOURCE_COMM(0),
	E_SOURCE_UPGRADE_EQUIPMENT(1),
	E_SOURCE_EVALUATION_EQUIPMENT(2),
	E_SOURCE_SALE_EQUIPMENT(3),
	E_SOURCE_DRAW_NATURAL(4),
	E_SOURCE_OFFLINE_AWARD(5),
	E_SOURCE_COLLECT_SOLDIER_AWARD(6),
	E_SOURCE_CHAPTER_BOX_AWARD(7),
	E_SOURCE_BUY_ITEM(8),
	E_SOURCE_OPEN_BOX(9),
	E_SOURCE_BATTLE(10),
	E_SOURCE_UPGRADE(11),
	E_SOURCE_REVIVE(12),
	E_SOURCE_ADD_VIT_BY_AD(13),
	E_SOURCE_ADD_VIT_OTHER_DAY(14),
	E_SOURCE_START_BATTLE(15),
	E_SOURCE_EVENT(16),
	E_SOURCE_GAME_OVER_CLEARING(17),
	E_SOURCE_AD_DRAW(18),
	E_SOURCE_GET_MAIL_ACCESSORY(19),
	E_SOURCE_CHARGE(20),
	E_SOURCE_EXCHANGE(21),
	E_SOURCE_GM(1000);

	private final int value;

	private E_SOURCE_TYPE(int value) {
		this.value = value;
	}

	public int value() {
		return this.value;
	}

	@Override
	public String toString() {
		return this.name() + ":" + this.value;
	}

	public static E_SOURCE_TYPE convert(int value) {
		for(E_SOURCE_TYPE v : values()) {
			if(v.value() == value) {
				return v;
			}
		}
		return null;
	}
}
