// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.yoooum.tars.commdata;

public enum E_TASK_LIMIT_TYPE {

	E_TASK_LIMIT_TYPE_MAIN_STORY(101),
	E_TASK_LIMIT_TYPE_FAVOR(102),
	E_TASK_LIMIT_TYPE_TASK(103),
	E_TASK_LIMIT_TYPE_PROTAGONIST(104),
	E_TASK_LIMIT_TYPE_PROPERTY(105),
	E_TASK_LIMIT_TYPE_COST_ITEM(106);

	private final int value;

	private E_TASK_LIMIT_TYPE(int value) {
		this.value = value;
	}

	public int value() {
		return this.value;
	}

	@Override
	public String toString() {
		return this.name() + ":" + this.value;
	}

	public static E_TASK_LIMIT_TYPE convert(int value) {
		for(E_TASK_LIMIT_TYPE v : values()) {
			if(v.value() == value) {
				return v;
			}
		}
		return null;
	}
}
