// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.yoooum.tars.commdata;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class TRecruitPetInfoOut {

	@TarsStructProperty(order = 0, isRequire = false)
	public short nPetID = (short)0;
	@TarsStructProperty(order = 1, isRequire = false)
	public String sPetName = "";
	@TarsStructProperty(order = 2, isRequire = false)
	public String sPicUrl = "";
	@TarsStructProperty(order = 3, isRequire = false)
	public short nTimes = (short)0;
	@TarsStructProperty(order = 4, isRequire = false)
	public byte cStatus = (byte)0;

	public short getNPetID() {
		return nPetID;
	}

	public void setNPetID(short nPetID) {
		this.nPetID = nPetID;
	}

	public String getSPetName() {
		return sPetName;
	}

	public void setSPetName(String sPetName) {
		this.sPetName = sPetName;
	}

	public String getSPicUrl() {
		return sPicUrl;
	}

	public void setSPicUrl(String sPicUrl) {
		this.sPicUrl = sPicUrl;
	}

	public short getNTimes() {
		return nTimes;
	}

	public void setNTimes(short nTimes) {
		this.nTimes = nTimes;
	}

	public byte getCStatus() {
		return cStatus;
	}

	public void setCStatus(byte cStatus) {
		this.cStatus = cStatus;
	}

	public TRecruitPetInfoOut() {
	}

	public TRecruitPetInfoOut(short nPetID, String sPetName, String sPicUrl, short nTimes, byte cStatus) {
		this.nPetID = nPetID;
		this.sPetName = sPetName;
		this.sPicUrl = sPicUrl;
		this.nTimes = nTimes;
		this.cStatus = cStatus;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(nPetID);
		result = prime * result + TarsUtil.hashCode(sPetName);
		result = prime * result + TarsUtil.hashCode(sPicUrl);
		result = prime * result + TarsUtil.hashCode(nTimes);
		result = prime * result + TarsUtil.hashCode(cStatus);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof TRecruitPetInfoOut)) {
			return false;
		}
		TRecruitPetInfoOut other = (TRecruitPetInfoOut) obj;
		return (
			TarsUtil.equals(nPetID, other.nPetID) &&
			TarsUtil.equals(sPetName, other.sPetName) &&
			TarsUtil.equals(sPicUrl, other.sPicUrl) &&
			TarsUtil.equals(nTimes, other.nTimes) &&
			TarsUtil.equals(cStatus, other.cStatus) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(nPetID, 0);
		if (null != sPetName) {
			_os.write(sPetName, 1);
		}
		if (null != sPicUrl) {
			_os.write(sPicUrl, 2);
		}
		_os.write(nTimes, 3);
		_os.write(cStatus, 4);
	}


	public void readFrom(TarsInputStream _is) {
		this.nPetID = _is.read(nPetID, 0, false);
		this.sPetName = _is.readString(1, false);
		this.sPicUrl = _is.readString(2, false);
		this.nTimes = _is.read(nTimes, 3, false);
		this.cStatus = _is.read(cStatus, 4, false);
	}

}
